### ISSUE TITLE
i am getting blank screen.

### ISSUE THREAD

**Issue by mehulTank** [stripe/stripe-terminal-android#103]
I am implementing stripe terminal SDK for the BBPOS device I have downloaded a given demo and run I configured key as well create Token successfully from the back end. I am getting blank screen only not getting anything. How can't check is that n any simulator?

![device-2020-03-21-171031](https://user-images.githubusercontent.com/15247268/77225654-f3eec780-6b96-11ea-90ec-41182ccea423.png)

**Comment by chander-stripe** [comment]
@mehulTank couple follow up questions
1. when you say "I have downloaded a given demo", is this the backend demo code, or the Android demo code, or both?
2. which version of the SDK are you using?
3. do you see any errors in the logcat?

**Comment by mehulTank** [comment]
@chander-stripe  Thanks For Your replay I am using an android demo code.
I am cloning this repo.

**Comment by RosilBelli** [comment]
It is happening the same with me. 
On the debug console I can find this error regarding strict mode:


`I/System.out: debugger has settled (1304)
I/Perf: Connecting to perf service.
D/LeakCanary: Installing AppWatcher
I/stetho: Listening on @stetho_com.stripe.example.javaapp_devtools_remote
D/StrictMode: StrictMode policy violation; ~duration=19 ms: android.os.strictmode.DiskReadViolation
        at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1504)
        at java.io.FileInputStream.<init>(FileInputStream.java:163)
        at java.io.FileInputStream.<init>(FileInputStream.java:112)
        at com.facebook.stetho.common.ProcessUtil.readProcessName(ProcessUtil.java:49)
        at com.facebook.stetho.common.ProcessUtil.getProcessName(ProcessUtil.java:38)
        at com.facebook.stetho.server.AddressNameHelper.createCustomAddress(AddressNameHelper.java:20)
        at com.facebook.stetho.Stetho$Initializer.start(Stetho.java:449)
        at com.facebook.stetho.Stetho.initialize(Stetho.java:134)
        at com.facebook.stetho.Stetho.initializeWithDefaults(Stetho.java:105)
        at com.stripe.example.javaapp.StripeTerminalApplication.onCreate(StripeTerminalApplication.java:34)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1165)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6074)
        at android.app.ActivityThread.access$1300(ActivityThread.java:207)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1758)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)`

**Comment by RosilBelli** [comment]
After executing a clean project and running the kotlin app it worked, but I still had no success with the java app.

**Comment by aliriaz-stripe** [comment]
Hello @RosilBelli , @mehulTank 

Could you write in to https://support.stripe.com/contact? The team there can help you out!

Please include the following details when you write in: 
1) The SDK version you are on
2) Any errors you see in Logcat
3) Is this on simulated reader or physical reader
4) Reproduction steps on how you get to the blank screen

Going to close this as Github Issues should be reserved for SDK feature requests or bugs.
Looking forward to helping you out once you write in!
