### ISSUE TITLE
Application is crash while app put in background

### ISSUE THREAD

**Issue by mehulTank** [stripe/stripe-terminal-android#109]
I am implementing stripe terminal with bbpos reader I clone this repo but I am getting issue while the app is put on the background here I added a log of that why getting crash no reason found in that we are not using local DB 

2020-04-14 15:38:28.235 14243-14290/com.example.myapplication E/ROOM: Invalidation tracker is initialized twice :/.
2020-04-14 15:38:28.249 14243-14320/com.example.myapplication E/ROOM: Cannot run invalidation tracker. Is the db closed?
    java.lang.IllegalStateException: The database '/data/user/0/com.example.myapplication/databases/stripe_terminal.db' is not open.
        at android.database.sqlite.SQLiteDatabase.throwIfNotOpenLocked(SQLiteDatabase.java:2368)
        at android.database.sqlite.SQLiteDatabase.createSession(SQLiteDatabase.java:427)
        at android.database.sqlite.-$$Lambda$RBWjWVyGrOTsQrLCYzJ_G8Uk25Q.get(Unknown Source:2)
        at java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:284)
        at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
        at java.lang.ThreadLocal.get(ThreadLocal.java:170)
        at android.database.sqlite.SQLiteDatabase.getThreadSession(SQLiteDatabase.java:421)

**Comment by chander-stripe** [comment]
Is this with the java or kotlin example app?

**Comment by mehulTank** [comment]
in both java & Kotlin getting the same issue.
I am getting other logs also posting here 

2020-04-21 00:48:30.582 18604-18604/com.example.myapplication I/SQLiteConnectionPool: The connection pool for /data/user/0/com.example.myapplication/databases/stripe_terminal.db has been closed but there are still 1 connections in use.  They will be closed as they are released back to the pool.
2020-04-21 00:48:30.627 18604-18827/com.example.myapplication E/ROOM: Invalidation tracker is initialized twice :/.
2020-04-21 00:48:30.669 18604-18827/com.example.myapplication E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-3
    Process: com.example.myapplication, PID: 18604
    java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
        at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:917)
        at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:400)
        at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:585)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
        at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:266)
        at com.stripe.stripeterminal.storage.LogPointDao_Impl.insertAll(LogPointDao_Impl.java:85)
        at com.stripe.stripeterminal.Terminal$Companion$cleanupTerminal$1.invokeSuspend(Terminal.kt:519)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)


while the app goes in to background at that Terminl.cleanupTerminal called somewhere but didn't figure it out wherefrom it is calling

**Comment by chander-stripe** [comment]
This will be fixed in the next release (v1.0.16)

**Comment by mehulTank** [comment]
may I know when can I get the next release?

**Comment by chander-stripe** [comment]
End of the week, around thursday or friday.

**Comment by mehulTank** [comment]
is there any update fix bug or any alternative solution for that?

**Comment by chander-stripe** [comment]
@mehulTank apologies for the delay - I have a semi urgent deadline due next week, will release the next SDK version right after , sorry again!

**Comment by mehulTank** [comment]
@chander-stripe Thanks For Replay & support. I am waiting for an Update.

**Comment by mehulTank** [comment]
@chander-stripe is there any update fix bug or any alternative solution for that?

**Comment by chander-stripe** [comment]
@mehulTank Hi the fix has been uploaded to Sonatype as part of *1.0.17* - feel free to re-open the issue if you're still encountering it on the latest version.

**Comment by mehulTank** [comment]
@chander-stripe  Thanks it is working fine.
