### ISSUE TITLE
Application Crash while put in background

### ISSUE THREAD

**Issue by mehulTank** [stripe/stripe-terminal-android#110]
I am implementing stripe terminal with bbpos reader I clone this repo but I am getting issue while the app is put on the background here I added a log of that why getting crash no reason found in that we are not using local DB

 E/ROOM: Invalidation tracker is initialized twice :/.
2020-04-18 18:40:38.379 31857-31893/com.stripe.example E/AndroidRuntime: FATAL EXCEPTION: DefaultDispatcher-worker-1
    Process: com.stripe.example, PID: 31857
    java.lang.IllegalStateException: Cannot perform this operation because there is no current transaction.
        at android.database.sqlite.SQLiteSession.throwIfNoTransaction(SQLiteSession.java:917)
        at android.database.sqlite.SQLiteSession.endTransaction(SQLiteSession.java:400)
        at android.database.sqlite.SQLiteDatabase.endTransaction(SQLiteDatabase.java:585)
        at androidx.sqlite.db.framework.FrameworkSQLiteDatabase.endTransaction(FrameworkSQLiteDatabase.java:90)
        at androidx.room.RoomDatabase.endTransaction(RoomDatabase.java:266)
        at com.stripe.stripeterminal.storage.TraceDao_Impl.insertAll(TraceDao_Impl.java:100)
        at com.stripe.stripeterminal.Terminal$Companion$cleanupTerminal$1.invokeSuspend(Terminal.kt:522)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by chander-stripe** [comment]
This is the same error as #109 , so going to close this one and figure out more details on that ticket instead.
