### ISSUE TITLE
Receiving CONNECTION_TOKEN_PROVIDER_ERROR when calling connectReader

### ISSUE THREAD

**Issue by rscherf** [stripe/stripe-terminal-android#113]
## Summary
After fetching and setting the `ConnectionToken`, we are trying to call `connectReader`, which always fails with the same error: `CONNECTION_TOKEN_PROVIDER_ERROR`, even though we've verified that the connection token is set. You can see the successful token request at: `req_CuBPDwzdnjjvnH1`

## Code to reproduce
```
Terminal.getInstance().discoverReaders(config, readers -> {
  try {
    Reader firstReader = readers.get(0);

    Log.d(TAG, "Reader serial is: " + firstReader.getSerialNumber());

    Terminal.getInstance().connectReader(firstReader, new ReaderCallback() {
      @Override
      public void onSuccess(Reader r) {
        // Does stuff
      }

      @Override
      public void onFailure(@Nonnull TerminalException e) {
        // Always errors here
      }
    });

  } catch (Exception e) {}
}
```

## Android version
```
compileSdkVersion 28
```

## Impacted devices (Android devices or readers)
Simulator

## SDK version
```
implementation 'com.stripe:stripe-android:14.4.1'
implementation 'com.stripe:stripeterminal:1.0.17'
```

## Logs
```
D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
D/StripeTokenProvider: ✅ Fetched connection_token pst_test_YWNjdF8yVFVmTk9GZmNLQURtRUxWbDhiTixLd0xMWDJnbFFWM25uMWN1ckRpS2pCSzh3RE5UaEZh_00QQBBvLID
D/StripeTerminal: class=Terminal message=discoverReaders
D/BaseAuthorizedActivity: Reader count: 1
    Reader serial is: CHB20SIMULATOR
D/StripeTerminal: class=Terminal message=connectReader serial_number=CHB20SIMULATOR
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTING)
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTED)
D/StripeTerminal: class=LogFlusher message="Reporting traces" num_traces=1
D/StripeTerminal: class=LogFlusher message="Sent 1 traces"
D/StripeTerminal: class=LogFlusher message="Reporting events" num_events=1
D/StripeTerminal: class=LogFlusher message="Sent 1 events"
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(NOT_CONNECTED)
E/StripeTerminal: NETWORK_ERROR.CONNECTION_TOKEN_PROVIDER_ERROR: Timed out waiting for connection token
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.ConnectionTokenManager.waitForToken(ConnectionTokenManager.kt:108)
        at com.stripe.stripeterminal.ConnectionTokenManager.getToken(ConnectionTokenManager.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.run$terminalsdk_release(TerminalSession.kt:481)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:191)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

## Other information
This previously worked before updating from `1.0.0-b7` to `1.0.15`. Tested both on Simulator `Pixel 3 Simulator` and `Google Pixel 2` device.

**Comment by corin-stripe** [comment]
@rscherf hey Ryan! Thanks for the detailed description and repro steps, and sorry about the slow response. Our resident Android expert hasn't been free to look at these issues recently, and unfortunately won't be for a couple more weeks, but he will be able to take a look and get back to you after July 4. In the meantime, please let us know if you found any workarounds or just wound up rolling back.

**Comment by rscherf** [comment]
@corin-stripe hey there! I ended up just rolling back, and dealing with #112 as that was the path of least resistance at the time. Thanks for the update!

**Comment by corin-stripe** [comment]
@rscherf gotcha, thanks for letting us know!

**Comment by rscherf** [comment]
@corin-stripe hey there! I updated to `v1.0.17` per the suggestion from Ruth Costigan (via email), but I'm still receiving the above error. You can see in the verbose log level, the reader is `CONNECTING`, `CONNECTED`, then `NOT_CONNECTED`. This was not an issue with `v1.0.0-rc7`

```
D/StripeTokenProvider: ✅ Fetched connection_token pst_test_YWNjdF8yVFVmTk9GZmNLQURtRUxWbDhiTiw4N09WZEpQbzVTWkRLSDN4OHc1SzVWQnFacWpnVzJ1_00jxvA0lOh
D/StripeTerminal: class=Terminal message=connectReader serial_number=CHB20SIMULATOR
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTING)
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(CONNECTED)
D/StripeTerminal: class=LogFlusher message="Reporting traces" num_traces=1
D/StripeTerminal: class=LogFlusher message="Sent 1 traces"
    class=LogFlusher message="Reporting events" num_events=1
D/StripeTerminal: class=LogFlusher message="Sent 1 events"
D/StripeTerminal: class=TerminalListenerProxy message=onConnectionStatusChange(NOT_CONNECTED)
E/StripeTerminal: NETWORK_ERROR.CONNECTION_TOKEN_PROVIDER_ERROR: Timed out waiting for connection token
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.ConnectionTokenManager.waitForToken(ConnectionTokenManager.kt:108)
        at com.stripe.stripeterminal.ConnectionTokenManager.getToken(ConnectionTokenManager.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.run$terminalsdk_release(TerminalSession.kt:481)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:191)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
I/System.out: onConnectionStatusChangeonConnectionStatusChangeonConnectionStatusChangeStopping spinner...
D/EGL_emulation: eglMakeCurrent: 0xdfae12a0: ver 3 0 (tinfo 0xdfb72740)
D/EGL_emulation: eglMakeCurrent: 0xdfae12a0: ver 3 0 (tinfo 0xdfb72740)
```

**Comment by rscherf** [comment]
Hey there! Just checking in to see if anyone had every looked into this issue?

**Comment by L-is-0** [comment]
Hey there, i am having the same issue on some of my devices, could anyone please advise on this?

**Comment by billfinn-stripe** [comment]
@L-is-0 -- if you are seeing this error, try setting a breakpoint or logging from your `ConnectionTokenProvider`. It typically means that the SDK is calling your `fetchConnectionToken` implementation, and it's throwing an exception or failing to provide a connection token (or maybe the device is offline and can't reach your backend).

**Comment by L-is-0** [comment]
hi @billfinn-stripe , thanks for the response. However, i can see from the log, the request to my backend for generating the connection token is success and i am still getting this error from the app until i restart it?

**Comment by billfinn-stripe** [comment]
Hi @L-is-0 -- can you please open a new issue, link to this issue, and provide the Android logcat logs you are seeing?
