### ISSUE TITLE
Java example will not build using Gradle 3.5.4, cannot generate view binders java.lang.StackOverflowError #81

### ISSUE THREAD

**Issue by sivasharma** [stripe/stripe-terminal-android#122]
I am getting this issue after gradle upgrade to 3.5.4 from 3.5.1

logs

: error: cannot generate view binders java.lang.StackOverflowError
  	at android.databinding.tool.expr.Expr.resolveListeners(Expr.java:209)
  	at android.databinding.tool.expr.Expr.resolveListeners(Expr.java:211)
  	at android.databinding.tool.expr.Expr.resolveListeners(Expr.java:211)
  	at android.databinding.tool.expr.Expr.resolveListeners(Expr.java:211)
  	at android.databinding.tool.expr.Expr.resolveListeners(Expr.java:211)

**Comment by billfinn-stripe** [comment]
Hi @sivasharma -- we've released 2.0.0 -- can you check if you are still seeing this error using version 2.0.0?

**Comment by dhenry-stripe** [comment]
Closing due to inactivity
