### ISSUE TITLE
Failed resolution of: Landroid/support/v4/content/ContextCompat at com.stripe.bbpos.bbdevice.BBDeviceController.aaa002

### ISSUE THREAD

**Issue by jerrydeng** [stripe/stripe-terminal-android#127]
## Summary
I was trying to re-implement the example app with minimum amount of code needed.  As soon as it gets to Terminal.initTerminal step, the app crashes with the following error.

## Code to reproduce
Essentially, I only include codes that needed to run this line from the example app.  Including verifyGPS, request permission, TokenProvider (w/ all the ConnectionProvider, ApiClient and BackendService, and TerminalEventListener
```
Terminal.initTerminal(applicationContext, LogLevel.VERBOSE, TokenProvider(),
                TerminalEventListener())
```

## Android version
This was on an emulator Pixel 2 API 25

## Impacted devices (Android devices or readers)
Emulator Android above with simulator

## SDK version
1.0.17

## Other information
It appears that BBDeviceController is still using support/v4/content/ContextCompat and caused unresolved class with the following error.
`2021-02-22 11:15:33.708 9215-9215/com.example.paymenttest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.paymenttest, PID: 9215
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa002(SourceFile:126)
        at com.stripe.bbpos.bbdevice.aaa008zz.<init>(SourceFile:101)
        at com.stripe.bbpos.bbdevice.BBDeviceController.<init>(SourceFile:395)
        at com.stripe.bbpos.bbdevice.BBDeviceController.getInstance(SourceFile:17)
        at com.stripe.stripeterminal.dagger.BbposModule.provideBBDeviceController(BbposModule.kt:24)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.provideBBDeviceController(BbposModule_ProvideBBDeviceControllerFactory.java:37)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:27)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBbposDeviceControllerFactory.get(BbposModule_ProvideBbposDeviceControllerFactory.java:32)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBbposDeviceControllerFactory.get(BbposModule_ProvideBbposDeviceControllerFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:14)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:42)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:13)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:46)
        at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.log.TraceFactory_Factory.get(TraceFactory_Factory.java:26)
        at com.stripe.stripeterminal.log.TraceFactory_Factory.get(TraceFactory_Factory.java:9)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.DaggerTerminalComponent.getTraceFactory(DaggerTerminalComponent.java:207)
        at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:448)
        at com.example.paymenttest.MainActivity.initialize(MainActivity.kt:95)
        at com.example.paymenttest.MainActivity.onResume(MainActivity.kt:42)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
        at android.app.Activity.performResume(Activity.java:6783)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3406)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3469)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6119)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

**Comment by billfinn-stripe** [comment]
Hi @jerrydeng -- are you able to build and run the [example Java or Kotlin app](https://github.com/stripe/stripe-terminal-android/tree/master/Example)? I just built the Kotlin example app on a Pixel 2 API 25 emulator, and it worked just fine.

I suspect that your project may be missing an implementation dependency (e.g., `androidx.appcompat:appcompat:1.1.0`).

**Comment by jerrydeng** [comment]
I was able to build and run the example Kotlin app.  To be sure dependency wasn't the issue, I copied the entire project and module gradle file to be safe.  This is what's in the gradle file
`
ext {
    maxSdkVersion = 29

    appcompat_version = '1.1.0'
    ...
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])

    api "com.google.android.material:material:$material_version"
    implementation "androidx.legacy:legacy-support-v4:$legacy_support_version"
    implementation "androidx.appcompat:appcompat:$appcompat_version"
    ...
}
`

**Comment by billfinn-stripe** [comment]
> I was able to build and run the example Kotlin app. To be sure dependency wasn't the issue, I copied the entire project and module gradle file to be safe.

Ah, ok, thanks for confirming. When I analyze the stacktrace that you pasted in the description in the sample app, I see the `BBDeviceController.class` is importing `androidx.core.content.ContextCompat`. Do you have both of these set in your `gradle.properties`?

```
android.enableJetifier=true
android.useAndroidX=true
```

**Comment by jerrydeng** [comment]
That was it.  Thanks Bill
