### ISSUE TITLE
Example throws terminal exception (unknown parameter)

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#13]
```
02-18 13:11:01.628 11190-11228/com.stripe.example E/Log: com.stripe.stripeterminal.TerminalException
       at com.stripe.stripeterminal.ApiClient.decodeResponse(ApiClient.java:76)
       at com.stripe.stripeterminal.ApiClient.confirmPaymentIntent(ApiClient.java:39)
       at com.stripe.stripeterminal.TerminalSession$ConfirmPaymentIntentOperation.run(TerminalSession.java:593)
       at com.stripe.stripeterminal.TerminalSession.lambda$enqueueOperation$0(TerminalSession.java:192)
       at com.stripe.stripeterminal.-$$Lambda$TerminalSession$jBo4Xx9Ldr_iXUis4CS0byxws7Y.run(lambda)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
02-18 13:11:01.632 11190-11228/com.stripe.example E/ConfirmPaymentIntentCallback: Received unknown parameter: source_data[card_present][ksn]
   com.stripe.stripeterminal.TerminalException
       at com.stripe.stripeterminal.ApiClient.decodeResponse(ApiClient.java:76)
       at com.stripe.stripeterminal.ApiClient.confirmPaymentIntent(ApiClient.java:39)
       at com.stripe.stripeterminal.TerminalSession$ConfirmPaymentIntentOperation.run(TerminalSession.java:593)
       at com.stripe.stripeterminal.TerminalSession.lambda$enqueueOperation$0(TerminalSession.java:192)
       at com.stripe.stripeterminal.-$$Lambda$TerminalSession$jBo4Xx9Ldr_iXUis4CS0byxws7Y.run(lambda)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Message Input
```

**Comment by danwaters-stripe** [comment]
This has been fixed in release 0.5.1
