### ISSUE TITLE
Methods marked with @UiThread must be executed on the main thread

### ISSUE THREAD

**Issue by matejkramny** [stripe/stripe-terminal-android#130]
## Summary
Once the SDK starts scanning for bluetooth we get the error below

## Code to reproduce
Example code
https://gist.github.com/matejkramny/3d7ed186139fe6b174692ded1fb15d9a

## Impacted devices (Android devices or readers)
Bluetooth readers

## SDK version
2.0.0-b2

## more info
Running as a flutter plugin, not sure that's relevant

```
I/TransactionManager(29121): endTransaction
I/ConnectionManager(29121): endOperation
I/UpdateManager(29121): endOperation
I/StripeTerminal(29121): class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
I/BBPOSBluetoothDiscoveryController(29121): stopDiscoverReaders
I/StripeTerminal(29121): class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
E/StripeTerminal(29121): java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-5-thread-1
E/StripeTerminal(29121): com.stripe.stripeterminal.model.external.TerminalException: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-5-thread-1
E/StripeTerminal(29121): 	at com.stripe.stripeterminal.ConnectionTokenManager.waitForToken(ConnectionTokenManager.kt:119)
E/StripeTerminal(29121): 	at com.stripe.stripeterminal.ConnectionTokenManager.getToken(ConnectionTokenManager.kt:71)
E/StripeTerminal(29121): 	at com.stripe.stripeterminal.adapter.BbposAdapter$DiscoverReadersOperation$onUpdateDiscoveredReaders$1.run(BbposAdapter.kt:1161)
E/StripeTerminal(29121): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
E/StripeTerminal(29121): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
E/StripeTerminal(29121): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/StripeTerminal(29121): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
E/StripeTerminal(29121): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
E/StripeTerminal(29121): 	at java.lang.Thread.run(Thread.java:761)
W/System.err(29121): com.stripe.stripeterminal.model.external.TerminalException: java.lang.RuntimeException: Methods marked with @UiThread must be executed on the main thread. Current thread: pool-5-thread-1
W/System.err(29121): 	at com.stripe.stripeterminal.ConnectionTokenManager.waitForToken(ConnectionTokenManager.kt:119)
W/System.err(29121): 	at com.stripe.stripeterminal.ConnectionTokenManager.getToken(ConnectionTokenManager.kt:71)
W/System.err(29121): 	at com.stripe.stripeterminal.adapter.BbposAdapter$DiscoverReadersOperation$onUpdateDiscoveredReaders$1.run(BbposAdapter.kt:1161)
W/System.err(29121): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
W/System.err(29121): 	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
W/System.err(29121): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err(29121): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
W/System.err(29121): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
W/System.err(29121): 	at java.lang.Thread.run(Thread.java:761)
V/LogFlusher(29121): Reporting 1 traces
```

**Comment by matejkramny** [comment]
Nevermind, not related to this package
