### ISSUE TITLE
Bbpos reader doesn't allow tapping with credit card to collect payment on Android

### ISSUE THREAD

**Issue by punktzrzutu** [stripe/stripe-terminal-android#133]
## Summary
Bbpos reader doesn't allow tapping with a credit card to collect payment on Android. After tapping the credit card, the only result is a message that reader waits for (INSERT or SWIPE), before tapping the message included also TAP, eventually collection results in the error "Timeout during card read".

Inserting card works as expected. Tapping works when you tap with iPhone with apple pay, but not with a credit card.
Tested with several credit cards none of them work with a tap, on several android devices with different android versions.
The location where the collection happens is in Poland (not sure if that can affect anything, considering Terminal is for the US, using US stripe account of course).

Also checked with sample android app, same problem, collection not possible with a tap using a credit card.

D/StripeTerminal: class=Terminal message=retrievePaymentIntent
D/StripeTerminal: class=ApiClient message=retrievePaymentIntent
I/StripeTerminal: class=ApiClient api_request_id=req_Ij7TYP4FyDB67F
D/StripeTerminal: class=Terminal message=collectPaymentMethod
D/StripeTerminal: class=TerminalListenerProxy message=onPaymentStatusChange(WAITING_FOR_INPUT)
D/StripeTerminal: class=BbposBluetoothAdapter message=collectPaymentMethod
D/StripeTerminal: class=BbposDeviceController message=startEmv
D/StripeTerminal: class=BbposDeviceControllerListener message=onRequestDisplayText(PRESENT_CARD)
D/StripeTerminal: class=BbposDeviceControllerListener message=onWaitingForCard(SWIPE_OR_INSERT_OR_TAP)

(now tapping credit card)

D/StripeTerminal: class=BbposDeviceControllerListener message=onRequestDisplayText(INSERT_OR_SWIPE_CARD)
D/StripeTerminal: class=BbposDeviceControllerListener message=onWaitingForCard(SWIPE_OR_INSERT)

D/StripeTerminal: class=LogFlusher message="Reporting traces" num_traces=1
D/StripeTerminal: class=LogFlusher message="Sent 1 traces"
D/StripeTerminal: class=LogFlusher message="Reporting events" num_events=1
D/StripeTerminal: class=LogFlusher message="Sent 1 events"
D/StripeTerminal: class=BbposDeviceControllerListener message=onReturnTransactionResult(TIMEOUT)
D/StripeTerminal: class=TerminalListenerProxy message=onPaymentStatusChange(READY)
E/StripeTerminal: USER_ERROR.CARD_READ_TIMED_OUT: Timeout during card read
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onReturnTransactionResult(BbposDeviceControllerListener.kt:158)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa058zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7397)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)

## Code to reproduce
Collect payment from sample android app.

## Android version
7, 10

## Impacted devices (Android devices or readers)
Possibly reader

## SDK version
SDK 'com.stripe:stripeterminal:1.0.18'
Reader's Software version 1.00.03.34-SZZZ_Generic_v45-30000

**Comment by billfinn-stripe** [comment]
Hi @punktzrzutu -- thanks for the detailed report. I have two questions:

1. Have you tried another Chipper reader, and does it exhibit the same failure?
2. Are you able to test with [a Stripe-issued test credit card](https://dashboard.stripe.com/test/terminal/shop/thsku_FmpZaTqwezTFvS)?

I am able to tap on my Chipper using the example app, so I'd like to rule out the hardware.

**Comment by punktzrzutu** [comment]
Hi @billfinn-stripe 
1. Don't have another reader
2. Don't have test card, testing with real cards in live mode

would it be possible to arrange the delivery of another reader and test cards to an address not in the US (Poland to be more specific)

**Comment by billfinn-stripe** [comment]
Hi @punktzrzutu -- unfortunately, for US accounts, we don't support shipping to non-US addresses.

**Comment by punktzrzutu** [comment]
@billfinn-stripe I have a personal stripe account registered in Poland as well, would it be possible to arrange shipping of reader and test cards to Poland in that case?

**Comment by billfinn-stripe** [comment]
Hi @punktzrzutu -- sorry, I should have been more clear. The only means of ordering a reader and test cards is through your stripe.com account via https://dashboard.stripe.com/test/terminal/shop. We may make exceptions for large users, and you can reach out to support via the dashboard for more information.

**Comment by billfinn-stripe** [comment]
@punktzrzutu -- are you still experiencing this issue? We have recently released 2.0.0. While I don't have a specific reason to believe the updated version will change fix this reported issue, we'd still encourage you to upgrade and see if you are still able to reproduce this issue.

**Comment by dhenry-stripe** [comment]
Closing due to inactivity. Feel free to re-open if this issue is still occurring.
