### ISSUE TITLE
Unable to connect device in release mode from android terminal sdk

### ISSUE THREAD

**Issue by Teja-Batchu** [stripe/stripe-terminal-android#153]
I am getting the below error when I am trying to connect to the device (Real device / Simulation) for payments, When I run the Android project in release mode. Debug mode is working fine with simulation, but working with a real device. 

Error:
com.stripe.stripeterminal.w.c.v0: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.affluence.deliverymodel.e.a()' on a null object reference

Total Log: 

21-08-18 16:31:43.484 9528-11840/com.affluence.deliverymodel E/StripeTerminal: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.affluence.deliverymodel.e.a()' on a null object reference
    com.stripe.stripeterminal.w.c.v0: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.affluence.deliverymodel.e.a()' on a null object reference
        at com.stripe.stripeterminal.d.f(Unknown Source:89)
        at com.stripe.stripeterminal.d.b(Unknown Source:23)
        at com.stripe.stripeterminal.d.c(Unknown Source:0)
        at com.stripe.stripeterminal.o$e.c(Unknown Source:48)
        at com.stripe.stripeterminal.o$i.b(Unknown Source:16)
        at com.stripe.stripeterminal.o.c(Unknown Source:40)
        at com.stripe.stripeterminal.o.d(Unknown Source:0)
        at com.stripe.stripeterminal.b.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by dhenry-stripe** [comment]
Hi @Teja-Batchu, it looks like you're minifying your code with Proguard/R8. Can you please disable it (`minifyEnabled false`) and post the resulting stack trace?

**Comment by Teja-Batchu** [comment]
Sorry for the late replay, please check below stack trace 

2021-08-25 14:39:45.821 23058-28941/com.affluence.deliverymodel E/StripeTerminal: Stripe API error
    com.stripe.stripeterminal.external.models.TerminalException: Stripe API error
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse(ApiClient.kt:191)
        at com.stripe.stripeterminal.api.ApiClient.activateReader(ApiClient.kt:50)
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.activateReader(DirectResourceRepository.kt:62)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:48)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:720)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:426)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:323)
        at com.stripe.stripeterminal.TerminalSession.lambda$onrTDPCIL0JzgfnO5iTaKnvzbds(Unknown Source:0)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$onrTDPCIL0JzgfnO5iTaKnvzbds.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)

**Comment by dhenry-stripe** [comment]
Thanks @Teja-Batchu. "Stripe API error" indicates that the Stripe backend has rejected the request. The SDK error handling had some improvements made in the latest version which may help to identify the cause. Can you please update to version 2.2.0 and try again?

Just to confirm - did you resolve the NullPointerException reported earlier? This is a different issue.

**Comment by dhenry-stripe** [comment]
Closing due to inactivity
