### ISSUE TITLE
onReportLowBatteryWarning not invoked when trying to connect to a card reader

### ISSUE THREAD

**Issue by malinajirka** [stripe/stripe-terminal-android#175]
## Summary

When I'm trying to connect to a card reader and reader's battery is low, the connection always fails with generic `StripeTerminal: Bluetooth unexpectedly disconnected during operation.` and `onReportLowBatteryWarning` is not getting invoked. Internally the SDK knows the reason of the failure was `Battery critically low during prefetch device info` as I can see that in the logs.

## Code to reproduce

I've tested both the example app and our app and the issue seem to be present in both.

## Android version

Android 11

## Impacted devices (Android devices or readers)

I'm seeing this problem on a M2, but I suspect the same issue is present on a Chipper 2X.

## SDK version

2.4.1

## Other information

```
D/StripeTerminal: class=Terminal message=connectBluetoothReader serial_number=STRM26122001017
I/StripeTerminal: class=TransactionManager message=endTransaction
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
D/StripeTerminal: class=BbposAdapter message=connectReader
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> CONNECT: Connect requested"
D/StripeTerminal: class=BBPOSDeviceControllerImpl message=connectBT
I/StripeTerminal: class=BBPOSControllerListener message=onBatteryLow
I/StripeTerminal: class=BBPOSControllerListener message="onError FAIL_TO_START_BT, Battery critically low during prefetch device info"
I/StripeTerminal: class=TransactionManager message=endTransaction
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CONNECT -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
D/StripeTerminal: class=ProxyTerminalListener message=onUnexpectedReaderDisconnect(STRM26122001017)
class=BbposAdapter message="skipping disconnectReader"
Bluetooth unexpectedly disconnected during operation.
    com.stripe.stripeterminal.external.models.TerminalException: Bluetooth unexpectedly disconnected during operation.
        at com.stripe.stripeterminal.adapter.BbposAdapter.register$lambda-17(BbposAdapter.kt:450)
        at com.stripe.stripeterminal.adapter.BbposAdapter.lambda$-pG0tX_wqZPkkrcRZHx8HWUdO44(Unknown Source:0)
        at com.stripe.stripeterminal.adapter.-$$Lambda$BbposAdapter$-pG0tX_wqZPkkrcRZHx8HWUdO44.accept(Unknown Source:4)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.stripe.core.hardware.reactive.status.ReactiveReaderStatusListener.handleReaderDisconnect(ReactiveReaderStatusListener.kt:71)
        at com.stripe.core.bbpos.BBPOSControllerListener.onError(BBPOSControllerListener.kt:85)
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa000(SourceFile:894)
        at com.stripe.bbpos.bbdevice.BBDeviceController.lambda$v4mGzwG6p-0ePoW6Y9cSxpCDv5Q(Unknown Source:0)
        at com.stripe.bbpos.bbdevice.-$$Lambda$BBDeviceController$v4mGzwG6p-0ePoW6Y9cSxpCDv5Q.run(Unknown Source:6)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:247)
        at android.app.ActivityThread.main(ActivityThread.java:8656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
class=CrpcClient message="GatorService.reportTrace request=null"
class=CrpcClient message="GatorService.reportTrace response={}"
class=CrpcClient message="GatorService.reportEvent request=null"
class=CrpcClient message="GatorService.reportEvent response={}"
W/StripeTerminal: class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=15 memoryProfile=TRIM_MEMORY_RUNNING_CRITICAL
W/StripeTerminal: class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=20 memoryProfile=TRIM_MEMORY_UI_HIDDEN
I/StripeTerminal: class=TerminalLifecycleObserver message=applicationDidEnterBackground
D/StripeTerminal: class=LocationHandler message=stopListening
W/StripeTerminal: class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=80 memoryProfile=TRIM_MEMORY_COMPLETE
W/StripeTerminal: class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=80 memoryProfile=TRIM_MEMORY_COMPLETE

```

**Comment by dhenry-stripe** [comment]
Thanks for reporting @malinajirka, we'll look into it!

**Comment by vatsal-gadhiya-searce** [comment]
Same issue as above. Android 11, Samsung S6 Tablet, Samsung S10 Phone

**Comment by dhenry-stripe** [comment]
This has been addressed and will be resolved in the next release.
