### ISSUE TITLE
No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;) right after connection was established

### ISSUE THREAD

**Issue by Turbozanik** [stripe/stripe-terminal-android#176]
Hi, we are trying to implement payments right now and right after we are connected to the emulated and real terminal, we are receiving the following error. 
STRIPE SDK version: '2.4.0' and '2.4.1'
Devices that we were using are running on android versions 7.1.2 and 10. Both rooted.

Maybe you will be able to help us.

**Error:**
`E/StripeTerminal: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.cryospa.app.debug-1/base.apk:classes4.dex)
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.cryospa.app.debug-1/base.apk:classes4.dex)
        at com.stripe.proto.api.rest.MainlandApi.activateConnectionToken(MainlandApi.kt:59)
        at com.stripe.core.transaction.AuthenticatedRestClient.activateTerminal(AuthenticatedRestClient.kt:104)
        at com.stripe.stripeterminal.api.ApiClient.activateReader(ApiClient.kt:61)
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.activateReader(DirectResourceRepository.kt:80)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:816)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:449)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:346)
        at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(TerminalSession.kt)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)`

**Adding full log to give you a higher resolution view:**        
```
E/BluetoothAdapter: Bluetooth binder is null
D/StripeTerminal: class=Terminal app_language=JAVA
D/StripeTerminal: class=LocationHandler message=startListening
D/StripeTerminal: class=Terminal device_rooted=TRUE
D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
E/BluetoothAdapter: Bluetooth binder is null
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: null -> EMPTY: null"
I/StripeTerminal: class=TransactionManager message="handleCardStatus NO_CARD"
D/StripeReaderRepositoryImpl: STRIPE TERMINAL INITIALIZED
D/StripeReaderRepositoryImpl: STRIPE TERMINAL DISCOVERY STARTED
D/StripeTerminal: class=Terminal message=discoverReaders
D/CreditCardInfoFragmentPresenter: STRIPE READER DISCOVERY STARTED
I/StripeTerminal: class=ProxyDiscoveryListener message="onUpdateDiscoveredReaders([CHB20SIMULATOR:47ed9d32-7f41-40f6-b771-63933c10788f, CHB30SIMULATOR:47ed9d32-7f41-40f6-b771-63933c10788f, WPC30SIMULATOR:47ed9d32-7f41-40f6-b771-63933c10788f])"
D/StripeReaderRepositoryImpl: STRIPE TERMINAL DISCOVERED null
D/StripeTerminal: class=Terminal message=connectBluetoothReader serial_number=CHB20SIMULATOR:47ed9d32-7f41-40f6-b771-63933c10788f
D/CreditCardInfoFragmentPresenter: STRIPE READER CONNECTION CONNECTING
D/CreditCardInfoFragmentPresenter: STRIPE READER DISCOVERY SUCCESS
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
D/CreditCardInfoFragmentPresenter: STRIPE READER CONNECTION CONNECTING
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTED)
D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
D/CreditCardInfoFragmentPresenter: STRIPE READER CONNECTION CONNECTED
D/StripeTerminal: class=DirectResourceRepository message=activateReader
D/StripeTerminal: class=ApiClient message=activateReader
D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
E/StripeTerminal: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.someapp.app.debug-1/base.apk:classes4.dex)
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.someapp.app.debug-1/base.apk:classes4.dex)
        at com.stripe.proto.api.rest.MainlandApi.activateConnectionToken(MainlandApi.kt:59)
        at com.stripe.core.transaction.AuthenticatedRestClient.activateTerminal(AuthenticatedRestClient.kt:104)
        at com.stripe.stripeterminal.api.ApiClient.activateReader(ApiClient.kt:61)
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.activateReader(DirectResourceRepository.kt:80)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:816)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:449)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:346)
        at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(TerminalSession.kt)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2021-11-12 00:51:08.495 8805-8920/com.someapp.app.debug D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
2021-11-12 00:51:08.495 8805-8920/com.someapp.app.debug E/StripeTerminal: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.someapp.app.debug-1/base.apk:classes4.dex)
    com.stripe.stripeterminal.external.models.TerminalException: No direct method <init>(Ljava/nio/charset/Charset;ILkotlin/jvm/internal/DefaultConstructorMarker;)V in class Lokhttp3/FormBody$Builder; or its super classes (declaration of 'okhttp3.FormBody$Builder' appears in /data/app/com.someapp.app.debug-1/base.apk:classes4.dex)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:349)
        at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(TerminalSession.kt)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
D/CreditCardInfoFragmentPresenter: STRIPE READER CONNECTION NOT_CONNECTED
D/CreditCardInfoFragmentPresenter: STRIPE READER CONNECTION NOT_CONNECTED
```

**Comment by dhenry-stripe** [comment]
Hi @Turbozanik, this looks like the okhttp version used in your app is incompatible with the version required by the Terminal SDK. Do you use okhttp in your app? If so, which version?

**Comment by Turbozanik** [comment]
Hi @dhenry-stripe 
We are using okHttp version '3.12.0' as we have to support android 4.1.2 devices. 
But as stripe is supporting only android 5+ we will do separate builds for them.
What is the lowest supported by the stripe okhttp version?

**Comment by dhenry-stripe** [comment]
Hi @Turbozanik,
Understood, yes you'll need a separate build for devices running < Android 5. Stripe Terminal depends on okhttp 4.7.2 (You can inspect this yourself by [viewing the gradle dependencies graph for your project](https://docs.gradle.org/current/userguide/viewing_debugging_dependencies.html#sec:listing_dependencies)).

Feel free to re-open the ticket if updating okhttp to 4.7.2 doesn't resolve the issue.
