### ISSUE TITLE
SDK 2.5.0 Pre-dipping still does not work.

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#179]
## Summary
This is regarding the closed issue #173. Thanks for remove the error code in the new release 2.5.0. However, we are actually expecting the pre-dipping can make payment intent start normally and BBPOS read card to process then complete the payment.

Through latest version 2.5.0 we found instead of process payment, BBPOS canceled our payment when card is pre-dipping. Error code are display as below. Please provide us a solution asap. 

Thank you.

## Code to reproduce

CollectPaymentMethod was canceled by the user
BBPOSReaderController: disableDevice CARD_IDLE
2021-11-16 09:49:05.202 12868-13977/io.ubt.alaeat.pos.t2.crepe.dev E/StripeTerminal: CollectPaymentMethod was canceled by the user
    com.stripe.stripeterminal.external.models.TerminalException: CollectPaymentMethod was canceled by the user
        at com.stripe.stripeterminal.adapter.BbposAdapter$CardReadOperation.completeCancel$core_publish(BbposAdapter.kt:704)
        at com.stripe.stripeterminal.adapter.BbposAdapter.register$lambda-10(BbposAdapter.kt:390)
        at com.stripe.stripeterminal.adapter.BbposAdapter.lambda$qCtWd9OoYiNXlI1DnGEqctntkjw(Unknown Source:0)
        at com.stripe.stripeterminal.adapter.-$$Lambda$BbposAdapter$qCtWd9OoYiNXlI1DnGEqctntkjw.accept(Unknown Source:4)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.stripe.core.hardware.reactive.emv.ReactiveEmvTransactionListener.handleTransactionResult(ReactiveEmvTransactionListener.kt:54)
        at com.stripe.core.hardware.emv.CanceledKernelInterface.handleResult(CanceledKernelInterface.kt:82)
        at com.stripe.core.hardware.emv.CombinedKernelInterface.handleResult(CombinedKernelInterface.kt:134)
        at com.stripe.core.bbpos.BBPOSTransactionListener.onReturnTransactionResult(BBPOSTransactionListener.kt:232)
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa000(SourceFile:402)
        at com.stripe.bbpos.bbdevice.BBDeviceController.lambda$T7eQTLnjeMlBtrLVbdKm0WHnyZ8(Unknown Source:0)
        at com.stripe.bbpos.bbdevice.-$$Lambda$BBDeviceController$T7eQTLnjeMlBtrLVbdKm0WHnyZ8.run(Unknown Source:2)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6746)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2021-11-16 09:49:05.204 12868-13977/io.ubt.alaeat.pos.t2.crepe.dev W/BBPOSLOG: collectPaymentMethod onFailure USER_ERROR.CANCELED
2021-11-16 09:49:05.220 12868-12868/io.ubt.alaeat.pos.t2.crepe.dev I/StripeTerminal: class=BBPOSTransactionListener message="onRequestDisplayText REMOVE_CARD"
2021-11-16 09:49:05.222 12868-12868/io.ubt.alaeat.pos.t2.crepe.dev I/BBPOSLOG: onRequestReaderDisplayMessage
2021-11-16 09:49:05.377 12868-12868/io.ubt.alaeat.pos.t2.crepe.dev I/StripeTerminal: class=BBPOSTransactionListener message="onReturnCheckCardResult INSERTED_CARD"
## Android version

7 and 9
## Impacted devices (Android devices or readers)

BBPOS
## SDK version

2.5.0

**Comment by dhenry-stripe** [comment]
Hi @ohmyleonia,

> we are actually expecting the pre-dipping can make payment intent start normally and BBPOS read card to process then complete the payment.

That was the intent of the previous fix. This issue appears to be related to manually cancelling a transaction and attempting to pre-dip in subsequent transactions. Can you please try the following and confirm that the output matches what I'm seeing?

Test 1:
1. Complete a transaction without pre-dipping.
2. Complete a transaction with pre-dipping.
Current output: transaction #2 completes successfully.
Expected output: transaction #2 completes successfully.

Test 2:
1. Start a transaction without pre-dipping and manually cancel it.
2. Start a transaction with pre-dipping.
Current output: transaction #2 is automatically cancelled.
Expected output: transaction #2 completes successfully.

I'm looking into a fix for Test 2. Can you please confirm that this is the issue you're seeing?

**Comment by dhenry-stripe** [comment]
Thanks for reporting @ohmyleonia! Resolved in 2.5.1
