### ISSUE TITLE
Unable to connect to both emulated reader or real one due to token activation error or discovery issue

### ISSUE THREAD

**Issue by Turbozanik** [stripe/stripe-terminal-android#184]
## Summary
I am unable to connect to the reader with the follwoing errors:
For emulated device:

```
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate request={"deviceSerialNumber":"CHB20SIMULATOR:20d01a1f-2b71-4866-9ae1-214dbf24c374","deviceType":"simulator","posDeviceId":"20d01a1f-2b71-4866-9ae1-214dbf24c374","posDeviceInfo":{"appModel":{"appId":"com.spmeapp.app.debug","appVersion":"8.0.1"},"deviceClass":"POS","deviceUuid":"20d01a1f-2b71-4866-9ae1-214dbf24c374","hardwareModel":{"posInfo":{"description":"\"Android SDK Built For X86\""}},"hostHwVersion":"\"Android SDK built for x86\"","hostOsVersion":"7.0"},"posVersionInfo":{"clientType":"ANDROID_SDK","clientVersion":"2.4.1"},"reader":{"appModel":{"appId":"firmware-config-key","appVersion":"1.00.03.32-SZZZ_Generic_v36-null"},"bbposBaseConfig":"SZZZ_Generic_v36","bbposFirmware":"1.00.03.32","deviceClass":"READER","deviceUuid":"CHB20SIMULATOR:20d01a1f-2b71-4866-9ae1-214dbf24c374","hardwareModel":{"simulatedHardware":{"bbposHardware":"CHIPPER2X"}}},"registerToLocation":"tml_EZTODgmL5ATznD"}"
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate status=HTTP_ERROR_UNKNOWN_STATE response={}"
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
E/StripeTerminal: Could not connect to Stripe. Please retry.
com.stripe.stripeterminal.external.models.TerminalException: Could not connect to Stripe. Please retry.
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse(ApiClient.kt:225)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:207)
        at com.stripe.stripeterminal.api.ApiClient.activateReader(ApiClient.kt:62)
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.activateReader(DirectResourceRepository.kt:80)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:816)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:449)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:346)
        at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(TerminalSession.kt)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(lambda)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```
For real device:
```

I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["CHB202902003002"]}"
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover status=UNAUTHORIZED response={"error":{"message":"Invalid API Key provided: getPosToken","type":"invalid_request_error"}}"
I/StripeTerminal: class=TransactionManager message=endTransaction
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
E/StripeTerminal: Invalid API Key provided: getPosToken
    com.stripe.stripeterminal.external.models.TerminalException: Invalid API Key provided: getPosToken
        at com.stripe.stripeterminal.api.ApiClient$Companion.convertErrorResponseTerminalException(ApiClient.kt:264)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse(ApiClient.kt:230)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:207)
        at com.stripe.stripeterminal.api.ApiClient.discoverLocations(ApiClient.kt:150)
        at com.stripe.stripeterminal.adapter.BbposAdapter$DiscoverReadersOperation.onUpdateDiscoveredReaders$lambda-8(BbposAdapter.kt:1004)
        at com.stripe.stripeterminal.adapter.BbposAdapter$DiscoverReadersOperation.lambda$B70mKtJblE55ZdvwuoEAIZbsneI(Unknown Source:0)
        at com.stripe.stripeterminal.adapter.-$$Lambda$BbposAdapter$DiscoverReadersOperation$B70mKtJblE55ZdvwuoEAIZbsneI.run(Unknown Source:6)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
        at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```
        
## Code to reproduce
Sharing what I can so far. This is the rxJava chain that we are using to connect to the reader.
1) We are creating connection token during terminal init and passing it to ConnectionTokenProvider, ConnectionTokenProvider basicaly holds a token string that we have created -> 
2) pst_test_YWNjdF8xSnBhN1NBa3dHamw2UHMyLFRIblBNclpveElDSGI5UWtsY3E4N2FzMlRHVWd3aGI_00jrKBjMh3
3) Get location id -> tml_EZT1DfmL5ATznD (its a fake location id, but it shows the format)
4) Starting discovery with the location id that we have. 
5) And it fails with the errors above depending on is it an emulated device or a real one.
```
addDisposable(inBackground(
		initTerminal()
			.flatMap(o -> mGetLocationIdUseCase
				.setParams(String.valueOf(mUnitHolder.getUnit().getCompanyId()))
				.execute())
			.flatMap(locationId -> mStripeDiscoveryUseCase.setParams(String.valueOf(locationId))
				.execute()))
			.subscribe(
				o -> {
					},
				e -> Timber.e("STRIPE INIT FAILED WITH ERROR %S", e.toString())));
```

## Android version
Android 7 and higher.

## Impacted devices (Android devices or readers)
On all devices that we have, starting from emulator ending with custom ELO android tablet and odroid SBC.

## SDK version
2.4.1

## Other information
Nothing that I can tell right away.

**Comment by dhenry-stripe** [comment]
Hi @Turbozanik, can you reproduce the error using the example apps? The first error code `HTTP_ERROR_UNKNOWN_STATE` indicates a connection problem, but the second suggests an invalid connection token. Can you please post your `ConnectionTokenProvider` implementation?

**Comment by Turbozanik** [comment]
I am not sure that it was exactly the same error with the sample app.  I can double check it tomorrow.
But I wasn't able to connect using example app as well.

ConnectionTokenProvider implementation is as simple as it could be. We are getting the connection token and just store it there. In case it will expire we will just restart the app right now. 

ConnectionTokenProvider implementation:
```

public class StripeReaderTokenProvider implements ConnectionTokenProvider {

	private final String mToken;

	public StripeReaderTokenProvider(String token) {
		mToken = token;
	}

	@Override
	public void fetchConnectionToken(@NonNull ConnectionTokenCallback connectionTokenCallback) {
		connectionTokenCallback.onSuccess(mToken);
	}
}

```

**Comment by dhenry-stripe** [comment]
@Turbozanik that code snippet looks fine. Can you please confirm whether or not you can reproduce with the Example apps? If so, can you please post the code you're using to generate the connection token on the backend?

**Comment by Turbozanik** [comment]
Yes, I was able to reproduce this with the example app.
But I have updated to SDK 2.5.2 and it seems like it is fixed now.
Now it work's.

**Comment by dhenry-stripe** [comment]
Okay, thanks for following up.
