### ISSUE TITLE
Reader gets disconnected right after it has established a connection

### ISSUE THREAD

**Issue by Turbozanik** [stripe/stripe-terminal-android#186]
## Summary
Right after I have connected to the reader I am receiving the following error:
No such location:  'tml_EZT1FgmK7ATznD#EhcKFWFjY3RfMUpwYTdTQWt3R2psNlBzMg' (this is fake location)

It seems like it gets correct location id(we are sure it exists), makes a call to `connection_tokens/activate` request and returns this strange string `'tml_EZT1FgmK7ATznD#EhcKFWFjY3RfMUpwYTdTQWt3R2psNlBzMg'` saying that our location does not exist.

Full log:
```
D/StartUpFragmentPresenter: STRIPE READER DISCOVERY STARTING
D/StartUpFragmentPresenter: STRIPE READER DISCOVERY IDLE
D/StartUpFragmentPresenter: STRIPE READER CONNECTION NOT_CONNECTED
D/StripeTerminal: class=Terminal app_language=KOTLIN
D/StripeTerminal: class=LocationHandler message=startListening
D/StripeTerminal: class=Terminal device_rooted=TRUE
D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: null -> EMPTY: null"
I/StripeTerminal: class=TransactionManager message="handleCardStatus NO_CARD"
D/StripeReaderRepositoryImpl: STRIPE TERMINAL INITIALIZED
D/StripeReaderRepositoryImpl: STRIPE TERMINAL DISCOVERY STARTED
D/StripeTerminal: class=Terminal message=discoverReaders
D/StartUpFragmentPresenter: STRIPE READER DISCOVERY STARTED
D/StripeTerminal: class=BbposAdapter message=discoverReaders
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
D/StripeTerminal: class=ApiClient message=discoverLocations
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["CHB202902003002"]}"
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=24, content-type=application/json, date=Mon, 29 Nov 2021 16:49:12 GMT, idempotency-key=1638204551933unknownhE3n9oGv, original-request=req_r5FJC4Yp6BnLPV, request-id=req_r5FJC4Yp6BnLPV, server=nginx, strict-transport-security=max-age=31556926; includeSubDomains; preload, stripe-account=acct_1Jpa7SAkwGjl6Ps2, stripe-should-retry=false, stripe-version=2019-11-05} response={}"
I/StripeTerminal: class=ProxyDiscoveryListener message=onUpdateDiscoveredReaders([CHB202902003002])
D/StripeReaderRepositoryImpl: STRIPE TERMINAL DISCOVERED 2F:24:4A:22:BF:11
D/StartUpFragmentPresenter: STRIPE READER CONNECTION CONNECTING
D/StripeTerminal: class=Terminal message=connectBluetoothReader serial_number=CHB202902003002
I/StripeTerminal: class=TransactionManager message=endTransaction
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
D/StartUpFragmentPresenter: STRIPE READER DISCOVERY SUCCESS
D/StripeTerminal: class=BbposAdapter message=connectReader
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTING)
D/StartUpFragmentPresenter: STRIPE READER CONNECTION CONNECTING
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> CONNECT: Connect requested"
D/StripeTerminal: class=BBPOSDeviceControllerImpl message=connectBT
I/StripeTerminal: class=BBPOSControllerListener message=onBTConnected
D/StripeTerminal: class=BluetoothBondStateReceiver message=stopListening
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CONNECT -> READER_INFO: null"
D/StripeTerminal: class=BBPOSDeviceControllerImpl message=getDeviceInfo
I/StripeTerminal: class=BBPOSControllerListener message="onReturnDeviceInfo {firmwareVersion=1.00.03.34.921a53dc, deviceSettingVersion=SZZZ_Generic_v46, uid=32005E00115048574B323920, trackKsn=3000020001000500003F, productID=4348423230, vendorID=535A5A5A, isSupportedTrack3=false, isSupportedTrack2=true, isSupportedTrack1=true, emvKsn=3000030001000500003C, batteryPercentage=99, pinKsn=30000100010005000004, terminalSettingVersion=SZZZ_Generic_v46, productId=4348423230, isCharging=false, isUsbConnected=true, bootloaderVersion=5.00.16.22, sdkVersion=3.21.2, 1.6.17, bID=CHB202902003002, batteryLevel=4.121, formatID=60, serialNumber=CHB202902003002, macKsn=30000400010005000001, isSupportedNfc=true, hardwareVersion=1.0.4}"
I/StripeTerminal: class=BbposAdapter reader_software_version=1.00.03.34.921a53dc-SZZZ_Generic_v46-300001 reader_battery_level=0.99
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(CONNECTED)
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: READER_INFO -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
D/StripeTerminal: class=ConnectionTokenManager message=refreshToken
D/StartUpFragmentPresenter: STRIPE READER CONNECTION CONNECTED
D/StripeTerminal: class=DirectResourceRepository message=activateReader
D/StripeTerminal: class=ApiClient message=activateReader
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate request={"deviceSerialNumber":"CHB202902003002","deviceType":"bbpos_chipper2x","posDeviceId":"ad8a889e-ac28-4a5a-93de-631aeee152f0","posDeviceInfo":{"appModel":{"appId":"com.someapp.app.debug","appVersion":"8.0.1"},"deviceClass":"POS","deviceUuid":"ad8a889e-ac28-4a5a-93de-631aeee152f0","hardwareModel":{"posInfo":{"description":"ODROID-N2"}},"hostHwVersion":"ODROID-N2","hostOsVersion":"9"},"posVersionInfo":{"clientType":"ANDROID_SDK","clientVersion":"2.5.2"},"reader":{"appModel":{"appId":"firmware-config-key","appVersion":"1.00.03.34.921a53dc-SZZZ_Generic_v46-300001"},"bbposBaseConfig":"SZZZ_Generic_v46","bbposFirmware":"1.00.03.34.921a53dc","bbposKeyProfile":"300001","deviceClass":"READER","deviceUuid":"CHB202902003002","hardwareModel":{"bbposHardware":"CHIPPER2X"},"hostHwVersion":"1.0.4"},"registerToLocation":"tml_EZT1FgmK7ATznD","reportedReaderConfig":{"keyId":"300001"}}"
D/StripeTerminal: class=ConnectionTokenManager message=fetchConnectionToken.onSuccess
I/StripeTerminal: class=RestClient message="url=https://api.stripe.com/v1/terminal/connection_tokens/activate status=NOT_FOUND response={"error":{"code":"resource_missing","docUrl":"https://stripe.com/docs/error-codes/resource-missing","message":"No such location: 'tml_EZT1FgmK7ATznD#EhcKFWFjY3RfMUpwYTdTQWt3R2psNlBzMg'","type":"invalid_request_error"}}"
D/StripeTerminal: class=BbposAdapter message=disconnectReader
I/StripeTerminal: class=TransactionManager message=endTransaction
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCONNECT: Disconnect requested"
D/StripeTerminal: class=BBPOSDeviceControllerImpl message=disconnectBT
I/StripeTerminal: class=BBPOSControllerListener message=onBTDisconnected
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
W/StripeTerminal: class=BbposAdapter message="skipping disconnectReader"
D/StartUpFragmentPresenter: STRIPE READER CONNECTION NOT_CONNECTED
E/StripeTerminal: No such location: 'tml_EZT1FgmK7ATznD#EhcKFWFjY3RfMUpwYTdTQWt3R2psNlBzMg'
    com.stripe.stripeterminal.external.models.TerminalException: No such location: 'tml_EZT1FgmK7ATznD#EhcKFWFjY3RfMUpwYTdTQWt3R2psNlBzMg'
        at com.stripe.stripeterminal.api.ApiClient$Companion.convertErrorResponseTerminalException(ApiClient.kt:264)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse(ApiClient.kt:230)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:207)
        at com.stripe.stripeterminal.api.ApiClient.activateReader(ApiClient.kt:62)
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.activateReader(DirectResourceRepository.kt:80)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:49)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:811)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:444)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:341)
        at com.stripe.stripeterminal.TerminalSession.lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(Unknown Source:0)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$JON2uE3bqI6fqJ9Sw06Ciz8JRZw.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
D/StartUpFragmentPresenter: STRIPE READER CONNECTION NOT_CONNECTED
I/StripeTerminal: class=CrpcClient message="GatorService.reportTrace request=null"
I/StripeTerminal: class=CrpcClient message="GatorService.reportTrace response={}"
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent request=null"
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent response={}"
```

## Code to reproduce

```
`.flatMap(data -> mGetConnectionStatusSubjectUseCase.execute().take(1)
	.flatMap(connectionData -> {
		if (connectionData == ConnectionStatus.NOT_CONNECTED) {
			return mGetStripeLocationIdUseCase
			      .setParams(String.valueOf(mUnitHolder.getUnit().getCompanyId())).execute()
					.flatMap(locationId -> mStripeDiscoveryUseCase.setParams(String.valueOf(locationId)).execute());
			} else {
				return Flowable.just(new Object());
			}
		}))`
```

## Android version
Android 7-11

## Impacted devices (Android devices or readers)
All devaices that we have so far. Samsung A52, elo custom table, odroid sbc etc.

## SDK version
2.5.2

## Other information
Nothing I can tell so far.

**Comment by dhenry-stripe** [comment]
@Turbozanik the location you're trying to access is owned by `acct_1DgDnJF2OEGRb1cS` but you're attempting to connect with `acct_1Jpa7SAkwGjl6Ps2`. Please take a look at the key that you're using and ensure that it's generated from the correct account. Feel free to re-open the ticket if the issue persists after verifying/updating your key.
