### ISSUE TITLE
Is it possible to install the cancelled update?

### ISSUE THREAD

**Issue by vivekvardhanadepu** [stripe/stripe-terminal-android#200]
After I cancel the update and try to install it again by calling `installUpdate`. It gives me error
```
E/StripeTerminal: null
    java.lang.NullPointerException
        at com.stripe.stripeterminal.TerminalSession$CancelableOperation.onCancelSuccess(TerminalSession.kt:521)
        at com.stripe.stripeterminal.TerminalSession$InstallUpdateOperation.onFailure$core_publish(TerminalSession.kt:978)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:429)
        at com.stripe.stripeterminal.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:781)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:427)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:324)
        at com.stripe.stripeterminal.TerminalSession.lambda$onrTDPCIL0JzgfnO5iTaKnvzbds(Unknown Source:0)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$onrTDPCIL0JzgfnO5iTaKnvzbds.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
E/StripeTerminal: Unexpected failure
    com.stripe.stripeterminal.external.models.TerminalException: Unexpected failure
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:327)
        at com.stripe.stripeterminal.TerminalSession.lambda$onrTDPCIL0JzgfnO5iTaKnvzbds(Unknown Source:0)
        at com.stripe.stripeterminal.-$$Lambda$TerminalSession$onrTDPCIL0JzgfnO5iTaKnvzbds.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```
I am using the cancellable returned from the `didStartInstallingUpdate` to cancel the update.
```
@ReactMethod
    public void installUpdate(Promise promise) {
        try {
            if (readerSoftwareUpdate != null) {
                Terminal.getInstance().installAvailableUpdate();
            }
            promise.resolve(serializeUpdate(readerSoftwareUpdate));
        } catch (Exception e) {
            promise.reject("Installing Update Error:", e);
        }
    }
@ReactMethod
    public void abortInstallUpdate() {
        if (pendingInstallUpdate != null && !pendingInstallUpdate.isCompleted()) {
            pendingInstallUpdate.cancel(new Callback() {
                @Override
                public void onSuccess() {
                    pendingInstallUpdate = null;
                    sendEventWithName(EVENT_ABORT_INSTALL_COMPLETION, Arguments.createMap());
                }

                @Override
                public void onFailure(@Nonnull TerminalException e) {
                    WritableMap errorMap = Arguments.createMap();
                    errorMap.putString(ERROR, e.getErrorMessage());
                    sendEventWithName(EVENT_ABORT_INSTALL_COMPLETION, errorMap);
                }
            });
        } else {
            sendEventWithName(EVENT_ABORT_INSTALL_COMPLETION, Arguments.createMap());
        }
    }
    @Override
    public void onReportReaderSoftwareUpdateProgress(float v) {
        sendEventWithName(EVENT_DID_REPORT_UPDATE_PROGRESS, new Float(v));
    }

    @Override
    public void onReportAvailableUpdate(ReaderSoftwareUpdate update) {
        readerSoftwareUpdate = update;
        sendEventWithName(EVENT_DID_REPORT_AVAILABLE_UPDATE, serializeUpdate(update));
    }

    @Override
    public void onStartInstallingUpdate(ReaderSoftwareUpdate update, Cancelable cancel) {
        readerSoftwareUpdate = update;
        pendingInstallUpdate = cancel;
        sendEventWithName(EVENT_DID_START_INSTALLING_UPDATE, serializeUpdate(update));
    }

    @Override
    public void onFinishInstallingUpdate(ReaderSoftwareUpdate update, TerminalException e) {
        if (e != null) {
            WritableMap errorMap = Arguments.createMap();
            errorMap.putString(ERROR, e.getErrorMessage());
            sendEventWithName(EVENT_DID_FINISH_INSTALLING_UPDATE, errorMap);
        } else {
            readerSoftwareUpdate = null;
            pendingInstallUpdate = null;
            sendEventWithName(EVENT_DID_FINISH_INSTALLING_UPDATE, serializeUpdate(update));
        }
    }
 ```

**Comment by chr-stripe** [comment]
@vivekvardhanadepu are you using the Android Terminal SDK or the React Native Terminal SDK? Some of the class and method references you have mentioned and present in your code snippet seem to indicate this might be an issue with the React Native SDK instead.

**Comment by vivekvardhanadepu** [comment]
It has been a long time. Let me check and get back to you

**Comment by vivekvardhanadepu** [comment]
I am using https://github.com/theopolisme/react-native-stripe-terminal. We might integrate the new `stripe-terminal-react-native` pkg. So, I am closing this for now
