### ISSUE TITLE
Google Crypto crash at WifiConfigurationStore.EncryptedPrefsDataStore.init

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#222]
## Summary
Hello, I've had 200+ crashes on Crashlytics because of a Google Crypto library   [issue](https://github.com/google/tink/issues/504) in combination with the Stripe Terminal SDK. 

Since it's internal there aren't any specific steps to re-create this.

## Exception
```
Fatal Exception: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException
While parsing a protocol message, the input ended unexpectedly in the middle of a field. This could mean either that the input has been truncated or that an embedded message misreported its own length.
```

## StackTrace
```
Fatal Exception: com.google.crypto.tink.shaded.protobuf.InvalidProtocolBufferException: While parsing a protocol message, the input ended unexpectedly in the middle of a field.  This could mean either that the input has been truncated or that an embedded message misreported its own length.
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parsePartialFrom(GeneratedMessageLite.java:1566)
       at com.google.crypto.tink.shaded.protobuf.GeneratedMessageLite.parseFrom(GeneratedMessageLite.java:1664)
       at com.google.crypto.tink.proto.Keyset.parseFrom(Keyset.java:957)
       at com.google.crypto.tink.integration.android.SharedPrefKeysetReader.read(SharedPrefKeysetReader.java:84)
       at com.google.crypto.tink.CleartextKeysetHandle.read(CleartextKeysetHandle.java:58)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.read(AndroidKeysetManager.java:328)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.readOrGenerateNewKeyset(AndroidKeysetManager.java:287)
       at com.google.crypto.tink.integration.android.AndroidKeysetManager$Builder.build(AndroidKeysetManager.java:238)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:155)
       at androidx.security.crypto.EncryptedSharedPreferences.create(EncryptedSharedPreferences.java:120)
       at com.stripe.core.connectivity.WifiConfigurationStore$EncryptedPrefsDataStore.<init>(WifiConfigurationStore.kt:152)
       at com.stripe.core.connectivity.WifiConfigurationStore.<init>(WifiConfigurationStore.kt:27)
       at com.stripe.core.connectivity.WifiConfigurationStore_Factory.newInstance(WifiConfigurationStore_Factory.java:31)
       at com.stripe.core.connectivity.WifiConfigurationStore_Factory.get(WifiConfigurationStore_Factory.java:23)
       at com.stripe.core.connectivity.WifiConfigurationStore_Factory.get(WifiConfigurationStore_Factory.java:9)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.core.connectivity.DefaultWifiConnectionRepository_Factory.get(DefaultWifiConnectionRepository_Factory.java:41)
       at com.stripe.core.connectivity.DefaultWifiConnectionRepository_Factory.get(DefaultWifiConnectionRepository_Factory.java:11)
       at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
       at com.stripe.core.connectivity.DefaultConnectivityRepository$WifiCallback.updateWifiConnectionFlow(ConnectivityRepository.kt:309)
       at com.stripe.core.connectivity.DefaultConnectivityRepository$WifiCallback.access$updateWifiConnectionFlow(ConnectivityRepository.kt:259)
       at com.stripe.core.connectivity.DefaultConnectivityRepository$WifiCallback$startWifiStrengthJob$job$1.invokeSuspend(ConnectivityRepository.kt:289)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

## Android version
Android 10, 11, 12

## Impacted devices
Galaxy Z Flip3 5G  |  Google Pixel 5 | Galaxy S9 | Moto G9

## SDK version
```com.stripe:stripeterminal:2.7.0```

**Comment by billfinn-stripe** [comment]
Hi @yogen-p! Thanks for reporting this issue. To clarify, is this issue causing your app to crash? Or is it just being reported as a crash (but it doesn't have any user-facing consequences)? In any case, we're going to look closer at fixing this, but I want to better understand its impact.

**Comment by yogen-p** [comment]
Hello @billfinn-stripe ,hope you had a nice weekend! Just wanted to ask if there's been any updates on the issue?
Our crashlytics numbers are rising day by day.

**Comment by billfinn-stripe** [comment]
Hi @yogen-p -- thanks for checking in. We have identified a fix, and we'll publish it in our upcoming 2.9.0 release, scheduled for the end of April.

In the meantime, you can downgrade to 2.6.0 if your app is not using any new features or bug fixes introduced in 2.7.0 or 2.8.0.

Thanks for your patience here, and thanks again for bringing this to our attention!

**Comment by yogen-p** [comment]
Hi @billfinn-stripe thanks for the update. Unfortunately, downgrading is not an option since we're using the tipping feature. We'll take it from here, waiting for your next release.
Also, I've got another serious issue incoming regarding tipping.

**Comment by billfinn-stripe** [comment]
Thanks, @yogen-p. I'm going to leave this ticket as open until we release 2.9.0 in case other users encounter the same crash that you reported.
