### ISSUE TITLE
Interac refund does not work with a simluated Interac cards

### ISSUE THREAD

**Issue by kidinov** [stripe/stripe-terminal-android#226]
## Summary
Interac refund does not work with a simulated Interac cards

*  Make an Interac payment using a built-in simulator
```
Terminal.getInstance().simulatorConfiguration = SimulatorConfiguration(
            simulatedCard = SimulatedCard(SimulatedCardType.INTERAC)
)
```
* Attempt to make a refund of the same payment
* Notice that processing state fails with:
```
2022-04-21 14:35:40.385 21768-22034/com.woocommerce.android.dev E/StripeTerminal: Failed to retrieve payment method data
    com.stripe.stripeterminal.external.models.TerminalException: Failed to retrieve payment method data
        at com.stripe.stripeterminal.resourcerepository.DirectResourceRepository.processRefund(DirectResourceRepository.kt:103)
        at com.stripe.stripeterminal.resourcerepository.ProxyResourceRepository.processRefund(ProxyResourceRepository.kt:83)
        at com.stripe.stripeterminal.TerminalSession$ProcessRefundOperation.executeIfNotCanceled(TerminalSession.kt:1251)
        at com.stripe.stripeterminal.TerminalSession$CancelableOperation.execute(TerminalSession.kt:485)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:452)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:349)
        at com.stripe.stripeterminal.TerminalSession.$r8$lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(Unknown Source:0)
        at com.stripe.stripeterminal.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
```

Apparently, simulator ejects the card too fast?

![image](https://user-images.githubusercontent.com/4923871/164440702-f261931b-36f0-4953-8148-0b47c45d90d9.png)

**Comment by chr-stripe** [comment]
Hey @kidinov, I believe this is now supported as of version `2.10.0` of the Android SDK. I just tested this with the latest version `2.12.0` and it seems to be working. Can you verifying that this is fixed for your use case as well?

**Comment by kidinov** [comment]
@chr-stripe We checked and it works fine in `2.10.0`! Thank you for the fix 🙏
