### ISSUE TITLE
Bluetooth unexpectedly disconnected during operation

### ISSUE THREAD

**Issue by kirankumbhar10** [stripe/stripe-terminal-android#233]
I am not able use M2 Reader on Android 5.0. Getting the error 'Bluetooth unexpectedly disconnected during operation'.

Stripe Terminal SDK- 2.5.2.
Android Version:- 5

E/StripeTerminal: Bluetooth unexpectedly disconnected during operation.
    com.stripe.stripeterminal.external.models.TerminalException: Bluetooth unexpectedly disconnected during operation.
        at com.stripe.stripeterminal.adapter.BbposAdapter.register$lambda-19(BbposAdapter.kt:483)
        at com.stripe.stripeterminal.adapter.BbposAdapter.$r8$lambda$MnvVTIbH5AJLSb6NQiPB5jmkREQ(BbposAdapter.kt)
        at com.stripe.stripeterminal.adapter.BbposAdapter$$ExternalSyntheticLambda15.accept(D8$$SyntheticClass)
        at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
        at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
        at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
        at com.stripe.core.hardware.reactive.status.ReactiveReaderStatusListener.handleReaderDisconnect(ReactiveReaderStatusListener.kt:83)
        at com.stripe.core.bbpos.BBPOSControllerListener.onError(BBPOSControllerListener.kt:85)
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa000(SourceFile:902)
        at com.stripe.bbpos.bbdevice.BBDeviceController.$r8$lambda$mB31SUx8g9bn3es3skUODvjjpwA(SourceFile)
        at com.stripe.bbpos.bbdevice.BBDeviceController$$ExternalSyntheticLambda111.run(D8$$SyntheticClass)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:145)
        at android.app.ActivityThread.main(ActivityThread.java:6930)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)

**Comment by chenmin-stripe** [comment]
Hi @kirankumbhar10 , are you able to upgrade your SDK version to 2.9.0 and let us know if you still encounter the issue?

**Comment by kirankumbhar10** [comment]
Yes. I have upgraded to latest SDK version.
But it doesn't work Android 5.0

**Comment by chr-stripe** [comment]
Hi @kirankumbhar10, I seem to be able to reproduce this on an Android 5.1 device. Not seeing the root cause for this just yet, but I'll continue to investigate further.

**Comment by chr-stripe** [comment]
This is likely due to an incompatibility with your device's hardware. The M2 reader requires Bluetooth Low Energy (BLE) Secure in order to establish a secure connection to your phone. BLE Secure was introduced in Bluetooth 4.2, which was finalized in December 2014. Since Android 5 and 5.1 were also released around this time, it's likely that many Android devices running on 5 or 5.1 inherently do not support connecting to the M2.

Unfortunately, as far as I can tell there's no easy way for us to determine programmatically whether the device specifically supports BLE Secure or not, though we'll look further into seeing if there's any improvements we can make around the messaging of this issue in the future.

There are two ways in which you can work around this, however:
1) Use a more modern device that has support for BLE Secure. Most phones produced in the last few years should have this.
2) Use the [BBPOS Chipper 2X BT](https://stripe.com/docs/terminal/readers/bbpos-chipper2xbt) instead of the M2. This hardware has no BLE Secure requirement and I can confirm that it should connect just fine to older devices running on Android 5 / 5.1 as well.
