### ISSUE TITLE
stripe terminal 2.12.0 NoSuchMethodException

### ISSUE THREAD

**Issue by dharmeshdevstree** [stripe/stripe-terminal-android#251]
//stripe terminal
    implementation "com.stripe:stripeterminal:2.12.0"

    //tap on phone
    implementation "com.stripe:stripeterminal-localmobile:2.11.0-b0"
    implementation "com.stripe:stripeterminal-core:2.12.0"

Error :
Caused by: java.lang.NoSuchMethodException: com.s.f.business.<init> [class android.content.Context]

 at com.stripe.stripeterminal.DaggerTerminalComponent$TerminalComponentImpl.getTerminal(DaggerTerminalComponent.java:1867)
        at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:932)
        at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:851)
        at com.givetap.view.ui.fragments.HomeFragment.initialize(Class.kt:650)

**Comment by chr-stripe** [comment]
Hi @dharmeshdevstree! Can you add some additional information about the issue you're currently facing using [our issue template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&template=terminal-android-sdk-issue.md&title=)?

**Comment by chr-stripe** [comment]
Closing due to inactivity. @dharmeshdevstree if you're able to provide additional context in the future I can reopen this ticket and investigate it further.
