### ISSUE TITLE
Android Terminal retrievePaymentIntent for NFC Tap to Pay Crash

### ISSUE THREAD

**Issue by raymond-hitpay** [stripe/stripe-terminal-android#256]
## Summary
App crashes when Terminal.getInstane().retrievePaymentIntent is called for Tap to Pay with NFC

Crash happens for Galaxy A21 device

## Code to reproduce
`Terminal.getInstance().retrievePaymentIntent(clientSrt, createPaymentIntentCallback);
`

## Android version
Android version 11

## Impacted devices (Android devices or readers)
Galaxy A21

## SDK version
stripe-android: 2.10.2-b0
Android Gradle Plugin: 7.0.0
Gradle: 7.0.2

##Stack Trace
```
Fatal Exception: java.lang.StringIndexOutOfBoundsException: length=6; index=7
       at java.lang.String.substring(String.java:2060)
       at com.s.f.burden.Dashboard(:1282)
       at com.s.f.Terminal.onCreateView(:1297)
       at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2995)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:523)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:261)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:113)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1374)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2841)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:2784)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:262)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:478)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:246)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1435)
       at android.app.Activity.performStart(Activity.java:8231)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3872)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2336)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8653)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by chr-stripe** [comment]
Hi @raymond-hitpay, what sort of reader (if any) are you connected to that is giving you this issue?

Also, I'm not seeing `retrievePaymentIntent()` anywhere in the stack trace you provided. Does this mean that there are some other actions between calling that method and when the crash happens? Additionally, those top few lines in the stack trace:

```
       at com.s.f.burden.Dashboard(:1282)
       at com.s.f.Terminal.onCreateView(:1297)
```

don't look like they match any classes that we ship in the Terminal SDK. This `com.s.f.Terminal` class looks like a Fragment (though it's hard to say since it looks like it's been obfuscated), and our Terminal SDK would not be showing a Fragment upon calling retrievePaymentIntent. Is that class something that is present in your own application?
