### ISSUE TITLE
Authorization exception when cancelling payment intent

### ISSUE THREAD

**Issue by alasdairhall** [stripe/stripe-terminal-android#257]
## Summary
Receiving the following exception when attempting to cancel a payment intent on an internet reader.
```
E/StripeTerminal: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
    com.stripe.stripeterminal.external.models.TerminalException: You did not provide an API key. You need to provide your API key in the Authorization header, using Bearer auth (e.g. 'Authorization: Bearer YOUR_SECRET_KEY'). See https://stripe.com/docs/api#authentication for details, or we can help at https://support.stripe.com/.
        at com.stripe.stripeterminal.internal.common.proto.ProtoConverter.toTerminalException(ProtoConverter.kt:229)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse(ApiClient.kt:232)
        at com.stripe.stripeterminal.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:209)
        at com.stripe.stripeterminal.api.ApiClient.cancelPaymentIntent(ApiClient.kt:66)
        at com.stripe.stripeterminal.TerminalSession$CancelPaymentIntentOperation.execute(TerminalSession.kt:759)
        at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:642)
        at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:504)
        at com.stripe.stripeterminal.TerminalSession.$r8$lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw(Unknown Source:0)
        at com.stripe.stripeterminal.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:459)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

The payment intent is captured in the `onSuccess` callback of a call to `retrievePaymentIntent`. It is being called after the `collectPaymentMethod` job has been cancelled.

## Android version
9

## Impacted devices (Android devices or readers)
WisePOS E

## SDK version
2.13.0

**Comment by bric-stripe** [comment]
Hi @alasdairhall this is a confusing error message that we'll be improving. When connected to an internet reader the SDK doesn't currently have a valid session to make the API request to cancel the payment intent. This is similar to how createPaymentIntent doesn't work with internet readers today. We'll be improving this by providing the same error, UNSUPPORTED_OPERATION, when attempting cancel with an internet reader.

For now the recommendation is to make the cancel API request from your merchant backend or from your application directly.

**Comment by bric-stripe** [comment]
Hi, in version 2.19.0 of the SDK client-side `cancelPaymentIntent` is now supported from the SDK when connected to a WisePOS E.
