### ISSUE TITLE
Getting 'No connected reader' error while collecting payment method

### ISSUE THREAD

**Issue by kirankumbhar10** [stripe/stripe-terminal-android#263]
I just upgraded stripe terminal sdk to 2.13.1 from 2.5.2.  First few payments worked fine. Now I am getting error 'No connected reader'
but card reader was already connected.  I have attached error log below.

`Non-fatal Exception: com.stripe.stripeterminal.external.models.TerminalException: No connected reader
       at com.stripe.stripeterminal.adapter.PaymentCollectionCoordinatorWrapper.collectPaymentMethodHelper(PaymentCollectionCoordinatorWrapper.kt:186)
       at com.stripe.stripeterminal.adapter.PaymentCollectionCoordinatorWrapper.collectPaymentMethod(PaymentCollectionCoordinatorWrapper.kt:118)
       at com.stripe.stripeterminal.adapter.BbposAdapter.collectPaymentMethod(BbposAdapter.kt:223)
       at com.stripe.stripeterminal.adapter.ProxyAdapter.collectPaymentMethod(ProxyAdapter.kt:127)
       at com.stripe.stripeterminal.TerminalSession$CollectPaymentMethodOperation.executeIfNotCanceled(TerminalSession.kt:841)
       at com.stripe.stripeterminal.TerminalSession$CancelableOperation.execute(TerminalSession.kt:675)
       at com.stripe.stripeterminal.TerminalSession$ExternalOperation.run$core_publish(TerminalSession.kt:642)
       at com.stripe.stripeterminal.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:504)
       at com.stripe.stripeterminal.TerminalSession.$r8$lambda$JON2uE3bqI6fqJ9Sw06Ciz8JRZw()
       at com.stripe.stripeterminal.TerminalSession$$ExternalSyntheticLambda0.run(:4)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)`

## Android version
Android 11

## Impacted devices (Android devices or readers)
Stripe Reader M2
## SDK version
2.13.1

## Other information
There was no error while creating payment intent. But error comes while collecting payment method

**Comment by kirankumbhar10** [comment]
Issue recreating

**Comment by justinadkins** [comment]
Following up here because we saw an incredible spike in this error over the past few days. We have reproduction steps:

1. Connect a reader
2. Force a disconnection by turning off the reader
3. Turn the reader back on and automatically reconnect
4. Attempt to collect payment method
5. Observe failure

If we "switch" connection type from usb <-> bluetooth, it will temporarily resolve until another disconnection. We can also restart our application which resolves the issue.

This was introduced in `2.13.0`.

**Comment by chenmin-stripe** [comment]
This is due to our internal feature flag dialing up. The feature has been turn off. You shouldn't see this issue any more.
Please reopen if you have further question.
