### ISSUE TITLE
Terminal.getInstance().connectBluetoothReader call failed.

### ISSUE THREAD

**Issue by darkengine** [stripe/stripe-terminal-android#278]
Failed to connect to a Reader using 'Terminal.getInstance().connectBluetoothReader'

## Summary
We integrate Stripe and Square card reader SDK. When calling connectBluetoothReader after discovering and getting the reader list, it shows error and the app crashed.

## Code to reproduce
`ConnectionConfiguration.BluetoothConnectionConfiguration connectionConfig =
                new ConnectionConfiguration.BluetoothConnectionConfiguration(
                        info.stripe_location_id
                );

        Terminal.getInstance().connectBluetoothReader(
                targetReader,
                connectionConfig,
                new BluetoothReaderListener() {
                },
                new ReaderCallback() {
                    @Override
                    public void onSuccess(@NotNull Reader reader) {
                        Log.d(TAG, "connectToReader done");
                        endDiscoverIfNeeded();
                    }

                    @Override
                    public void onFailure(@NotNull TerminalException e) {
                        Log.e(TAG, "connectToReader failed with: " + e.getLocalizedMessage());
                        e.printStackTrace();
                    }
                }
        );`

## Android version
Android 12

## Impacted devices (Android devices or readers)
Simulator readers

## SDK version
2.16.0

## Other information
Stripe card reader SDK - v 2.16.0
Square card reader SDK - v 1.7.4

Logcat message:
`E/StripeTerminal: null
    java.lang.NoSuchMethodError: No static method createRuntimeMessageAdapter(Ljava/lang/Class;)Lcom/squareup/wire/internal/RuntimeMessageAdapter; in class Lcom/squareup/wire/internal/ReflectionKt; or its super classes (declaration of 'com.squareup.wire.internal.ReflectionKt' appears in /data/app/~~UpidX6Y_FFGNotmrwoesPg==/com.groomore.scheduler-ZCBRyUXZNcGZUaNL7Z4row==/base.apk!classes24.dex)
        at com.squareup.wire.WireJsonAdapterFactory.create(WireJsonAdapterFactory.kt:78)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:146)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:106)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:80)
        at com.stripe.wirecrpc.moshi_utils.MoshiExt.toJsonWithSnakeCase(MoshiExt.kt:35)
        at com.stripe.wirecrpc.moshi_utils.MoshiExt.toJsonWithSnakeCaseFieldNames(MoshiExt.kt:26)
        at com.stripe.core.environment.EnvironmentKt.stripeUserAgentHeader(Environment.kt:95)
        at com.stripe.core.transaction.AuthenticatedRestClient.activateTerminal(AuthenticatedRestClient.kt:122)
        at com.stripe.stripeterminal.internal.common.api.ApiClient.activateReader(ApiClient.kt:59)
        at com.stripe.stripeterminal.internal.common.resourcerepository.OnlineDirectResourceRepository.activateReader(OnlineDirectResourceRepository.kt:117)
        at com.stripe.stripeterminal.internal.common.resourcerepository.DirectResourceRepositoryRouter.activateReader(DirectResourceRepositoryRouter.kt:50)
        at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:51)
        at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:50)
        at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.withCurrentRepository(ProxyResourceRepository.kt:133)
        at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:50)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1230)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:691)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda-2(TerminalSession.kt:553)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$1IVjgEQTaDgDebv5q6iisqavZt0(Unknown Source:0)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)`

**Comment by darkengine** [comment]
Thanks a lot, @chr-stripe, I realize this after searching what Square Wire is. I'll try the 'customize dependency resolution' to check if any luck that both readers can work.

**Comment by ssavic** [comment]
@darkengine any luck with customizing dependency?

**Comment by ssavic** [comment]
Any updates as to when we will get new SDK?

**Comment by chr-stripe** [comment]
We're planning to release the update next week. I'll drop a message in this thread once it's available.

**Comment by chr-stripe** [comment]
Version `2.17.0` of the SDK has been published!
