### ISSUE TITLE
Can't connect to terminals on Samsung devices running Android 13

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#280]
## Summary
We now have 40+ instances of where users updated their Samsung device to Android 13 and now they are unable to connect to the WisePad 3.

## Code to reproduce
After initiating a connection using `terminalInstance.connectBluetoothReader(...)`, after a while there are multiple consecutive InterruptedException and the whole process fails.
```
I/BluetoothAdapter: STATE_ON
I/BluetoothAdapter: STATE_ON
D/BluetoothLeScanner: Stop Scan with callback
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Object.wait(Native Method)
W/System.err:     at java.lang.Object.wait(Object.java:442)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb055zz.aaa000(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.aaa012zz.aaa002(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb065zz.run(SourceFile:91)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err:     at java.lang.Thread.run(Thread.java:1012)
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Object.wait(Native Method)
W/System.err:     at java.lang.Object.wait(Object.java:442)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb055zz.aaa000(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.aaa012zz.aaa002(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb065zz.run(SourceFile:91)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err:     at java.lang.Thread.run(Thread.java:1012)
W/System.err: java.lang.InterruptedException
W/System.err:     at java.lang.Object.wait(Native Method)
W/System.err:     at java.lang.Object.wait(Object.java:442)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb055zz.aaa000(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.aaa012zz.aaa002(SourceFile:40)
W/System.err:     at com.stripe.bbpos.bbdevice.bbb065zz.run(SourceFile:91)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
W/System.err:     at java.lang.Thread.run(Thread.java:1012)
V/QueueFileCollector: terminal_sdk_wire_metrics batch of size 1 generated.
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent request=null"
D/TrafficStats: tagSocket(237) with statsTag=0xffffffff, statsUid=-1
I/StripeTerminal: class=CrpcClient message="GatorService.reportEvent response={}"
V/BatchDispatcher: Flushed successfully.
V/QueueFileCollector: terminal_sdk_wire_metrics removed 1 entries.
D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=6 device=CC:D3:1E:67:95:A4
D/BluetoothGatt: cancelOpen() - device: CC:D3:1E:67:95:A4
D/BluetoothGatt: cancelOpen() - device: CC:D3:1E:67:95:A4
D/BluetoothGatt: close()
D/BluetoothGatt: unregisterApp() - mClientIf=6
I/BbposControllerListener: onReturnDebugLog
D/BbposControllerListener: {date: Mon Dec 12 12:45:36 GMT 2022,type: CALLBACK,message: errorState : FAIL_TO_START_BT, errorMessage : Bluetooth (error code - 3020)(BLE status : 0, newState : 0),callback: onError}
I/StripeTerminal: class=BbposControllerListener message="onError FAIL_TO_START_BT, Bluetooth (error code - 3020)(BLE status : 0, newState : 0)"
D/StripeTerminal: class=BluetoothBondStateReceiver message=stopListening
I/StripeTerminal: class=TransactionManager message=endTransaction
I/ConnectionManager: endOperation
I/UpdateManager: endOperation
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CONNECT -> CANCELLED: null"
D/StripeTerminal: class=BbposProxyDiscoveryController message=stopDiscover
I/BBBTDiscoveryController: stopDiscoverReaders
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
I/StripeTerminal: class=TerminalStatusManager message=TerminalStatusManager unexpectedDisconnect.
D/StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
D/StripeTerminal: class=ProxyTerminalListener message=onUnexpectedReaderDisconnect(WPC323105000811)
W/MixpanelAPI.SysInfo: Permission READ_PHONE_STATE not granted. Property $radio will not be available.
D/StripeTerminal: class=Terminal message=discoverReaders
D/StripeTerminal: class=BbposBluetoothAdapterLegacy message=disconnectReader
I/StripeTerminal: class=TransactionManager message=endTransaction
I/UpdateManager: endOperation
I/ConnectionManager: startDisconnect
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCONNECT: Disconnect requested"
I/StripeTerminal: class=BbposReaderConnectionController message=disconnectBluetooth
D/StripeTerminal: class=BbposDeviceControllerImpl message=disconnectBT
I/BbposControllerListener: onReturnDebugLog
D/BbposControllerListener: {function: disconnectBT,date: Mon Dec 12 12:45:36 GMT 2022,type: FUNCTION,message: }
I/BbposControllerListener: onReturnDebugLog
D/BbposControllerListener: {date: Mon Dec 12 12:45:36 GMT 2022,type: CALLBACK,message: errorState : COMM_LINK_UNINITIALIZED, errorMessage : Cannot disconnect bluetooth because bluetooth is not connected.,callback: onError}
I/StripeTerminal: class=BbposControllerListener message="onError COMM_LINK_UNINITIALIZED, Cannot disconnect bluetooth because bluetooth is not connected."
I/ConnectionManager: endOperation
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
D/StripeTerminal: class=BbposProxyDiscoveryController message=stopDiscover
I/BBBTDiscoveryController: stopDiscoverReaders
I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
I/StripeTerminal: class=TerminalStatusManager message=TerminalStatusManager notConnected.
W/StripeTerminal: class=BbposBluetoothAdapterLegacy message="skipping disconnectReader"
E/StripeTerminal: null
    com.stripe.stripeterminal.external.models.TerminalException: Bluetooth unexpectedly disconnected during operation.
        at com.stripe.stripeterminal.internal.common.adapter.BbposBluetoothAdapterLegacy.onDisconnect(BbposBluetoothAdapterLegacy.kt:177)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.registerReaderDisconnectHandler$lambda-12(BbposAdapterLegacy.kt:469)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.$r8$lambda$IwO5tMnEnfsPMnLhmI9FsHrksH4(Unknown Source:0)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$$ExternalSyntheticLambda30.accept(Unknown Source:4)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
```

## Android version
Android 13

## Impacted devices (Android devices or readers)
Samsung devies that updated to Android 13
- Most common: Samsung Galaxy Z Flip 3
- Samsung Galaxy Z Fold 3
- Samsung Galaxy S21
- Samsung Galaxy S20 FE
- Samsung Galaxy A71
- Samsung A52, etc

## SDK version
2.15.0, 2.16.0, 2.16.0-b0

## Other information
During the whole process it looks like the terminal has somehow restarted which then results in
 `TerminalException: Bluetooth unexpectedly disconnected during operation`

**Comment by billfinn-stripe** [comment]
Following up via email as well, but our current suspicion is this is a Samsung and Android 13 Bluetooth compatibility issue. See also: https://www.sammyfans.com/2022/11/02/breaking-samsung-releases-android-13-bluetooth-connection-issue-fix-update-for-galaxy-s22/

**Comment by jolen10** [comment]
Any update on this issue?

**Comment by billfinn-stripe** [comment]
Hi @jolen10 -- we have determined that this issue is only impacting Samsung Z Flip and Samsung Z Fold devices running Android 13. We are have not yet identified a fix.

Are you encountering the same problem? Can you share how many mobile devices you have in the field that are experiencing this problem?

**Comment by jolen10** [comment]
Hi @billfinn-stripe, yes we are encountering the same issue. Good thing that there are no live customers that got impacted on it on our end at the moment and only internal dev team got affected that are using Z-Flip.

**Comment by jolen10** [comment]
Any update?

We just got a report that it's also happening on an older device, Samsung Galaxy Tab A @ Android 7.1.1 where it gets unexpectedly disconnected while trying to connect.

I'm not sure if it's the same InterruptedException as I don't have access to an old device where I can debug.

**Comment by billfinn-stripe** [comment]
Update from @yogen-p here -- @yogen-p's team was able to update their Samsung devices to the December 2022 security patch [0], and it seems to have resolved their issues.

I'm going to leave this Github issue open until we can internally confirm, but please let us know if the December 2022 update fixes or does not fix the issue for you.

[0] https://www.sammyfans.com/2022/12/25/these-samsung-galaxy-devices-start-getting-december-2022-security-update/

**Comment by jolen10** [comment]
I have confirmed that the December 2022 Samsung update on Android 13 devices did fix the issue.
