### ISSUE TITLE
Payment was declined by reader

### ISSUE THREAD

**Issue by legomanaustralia** [stripe/stripe-terminal-android#29]
Hey folks, 

We've been seeing "payment was declined by reader" when attempting to start the payment process, this is before we even try to swipe the card. 

`2019-05-13 22:03:02.022 11099-11512/? E/Log: com.stripe.stripeterminal.TerminalException
        at com.stripe.stripeterminal.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.java:842)
        at com.stripe.stripeterminal.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.java:719)
        at com.bbposstripe.bbdevice.BBDeviceController$19.run(SourceFile:4601)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6548)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)`

**Comment by danwaters-stripe** [comment]
Hi,

Thanks for the report. We found a bug in the SDK that is causing the behavior you're seeing. We'll include a fix in the next release.

**Comment by danwaters-stripe** [comment]
Version 1.0.0-b4 has been released with a fix for this issue.
