### ISSUE TITLE
SCAN_FAILED_INTERNAL_ERROR on discovering

### ISSUE THREAD

**Issue by KucherenkoIhor** [stripe/stripe-terminal-android#291]
2023-02-22 12:15:18.464 2888-2945/com.wix.post.payment D/Stripe2TerminalHolder$offlineListener: OfflineListener onNetworkStatusChange ONLINE
2023-02-22 12:15:18.465 2888-2963/com.wix.post.payment D/StripeTerminal: class=BbposBluetoothAdapterLegacy message=discoverReaders
2023-02-22 12:15:18.465 2888-2981/com.wix.post.payment I/StripeTerminal: class=TransactionManager message="handleCardStatus NO_CARD"
2023-02-22 12:15:18.468 2888-2963/com.wix.post.payment I/ConnectionManager: startDiscovery
2023-02-22 12:15:18.476 2888-2981/com.wix.post.payment I/StripeTerminal: class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
2023-02-22 12:15:18.477 2888-2981/com.wix.post.payment D/StripeTerminal: class=BbposProxyDiscoveryController message=discover
2023-02-22 12:15:18.477 2888-2981/com.wix.post.payment I/BBBTDiscoveryController: discoverDevices
2023-02-22 12:15:18.478 2888-2981/com.wix.post.payment D/BluetoothAdapter: isLeEnabled(): ON
2023-02-22 12:15:18.478 2888-2888/com.wix.post.payment D/BbposBluetoothScanner: scanFailed, errorCode: 3
2023-02-22 12:15:18.479 2888-2981/com.wix.post.payment E/StripeTerminal: null
    com.stripe.core.hardware.status.ScanFailedFatalError: Bluetooth scan failed - SCAN_FAILED_INTERNAL_ERROR
        at com.stripe.core.bbpos.hardware.discovery.BbposBluetoothScanner.onScanFailed(BbposBluetoothScanner.kt:134)
        at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:562)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)

## Summary
I get this error on Android 11. Everything is ok on Android 8

## Code to reproduce
val config = DiscoveryConfiguration(
                    timeout = DISCOVERY_TIMEOUT,
                    discoveryMethod = DiscoveryMethod.BLUETOOTH_SCAN,
                    isSimulated = isTerminalSimulated
                )
                val discoveryCallback = object : Callback {
                    override fun onSuccess() {
                        Timber.d("DiscoverDevices succeed")
                        discoveryTask = null
                        callback?.invoke()
                    }

                    override fun onFailure(e: TerminalException) {
                        discoveryTask = null
                       
                    }
                }
                discoveryTask = terminalHolder.terminal.discoverReaders(
                    config = config,
                    discoveryListener = discoveryListener,
                    callback = discoveryCallback
                )

## Android version
Android 11

## SDK version
2.17.1

**Comment by chr-stripe** [comment]
Thanks for the report. I'm wondering if we can get a few more details to help diagnose this issue:

- What are the hardware devices being used to test on? I see you're switching between Android 8 and 11 – are those devices the same hardware type running on two different versions?

- Can you post the full device logs that _aren't_ filtered by application? The logs above are only those emitted by your POS application, but since this seems to be failing in the Bluetooth level, having the full system logs between starting to scan and receiving the error may prove to be more useful

- Is this reproducible on any previous versions of the SDK? ie: does downgrading to `2.16.0` solve this for you?

**Comment by KucherenkoIhor** [comment]
Hey @chr-stripe 
Thanks 

 * the tablet with Android 11 is hp engage one essential all-in-one system 1.00.04-2053 rd2a.211001.002
    the tablet with Android 8 has been also provided by HP but it is not available any more. Hardware are not the same.

 * the full logcat from app launching https://gist.github.com/KucherenkoIhor/c3ad269f809b92c829fe25e02b1b17a9
 
 * downgrading to 2.16.0 doesn't help

**Comment by chr-stripe** [comment]
Hey @KucherenkoIhor, it sound from other contacts your team has had to Stripe that the issue was with the hardware not supporting scanning through Bluetooth Low Energy (despite the [product sheet](https://h20195.www2.hp.com/v2/getpdf.aspx/c07928667.pdf) claiming to support it). I'd recommend you reach out to HP and let them know of the issue.

Additionally, I'd recommend you take a look at our beta feature for [connecting to readers via USB](https://stripe.com/docs/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=usb). This might be a preferable alternative for you to connect with the new HP hardware.
