### ISSUE TITLE
Receive onUnexpectedReaderDisconnect event at the time of reader update 

### ISSUE THREAD

**Issue by arbaz8dots** [stripe/stripe-terminal-android#293]
## Code to reproduce
 Terminal.getInstance().connectBluetoothReader(reader, connectionConfig, this, new ReaderCallback() {
                @Override
                public void onSuccess(Reader r) {
                    getActivity().runOnUiThread(() -> {
                        stripeReader = r;
                        cardReader.s_terminal_id = r.getId();
                        createPaymentIntent();

                    });

                }

                @Override
                public void onFailure(TerminalException e) {
                    e.printStackTrace();
                    sendMessage("Terminal Exception\nCode:" + e.getErrorCode().toString() + "\n" + e.getErrorMessage() + "\n", 2);

                }
            });. 

## Android version
 above Oreo 

## SDK version
2.17.1

## Other information
 Before upgrading to terminal version 2.17.1 it was working fine, getting this issue after upgrading 2.17.1 
![image](https://user-images.githubusercontent.com/114399091/222336411-45a1e485-a314-4f73-b3a7-ec09d00ae297.png)

**Comment by billfinn-stripe** [comment]
@arbaz8dots -- are you still filling out details here, or was this issue submitted by mistake?

**Comment by arbaz8dots** [comment]
> @arbaz8dots -- are you still filling out details here, or was this issue submitted by mistake?

@billfinn-stripe no issue was not submitted by mistake, please check I've updated details of the issue.

**Comment by billfinn-stripe** [comment]
> Before upgrading to terminal version 2.17.1 it was working fine, getting this issue after upgrading 2.17.1

What version did you upgrade from?

Can you share a reader serial number, so we can check our logs for your devices?

If you can reproduce the issue, can you share a stacktrace?

**Comment by jronnen7** [comment]
We have a customer reporting a similar issue after a reader update a few weeks ago, I cannot share much besides this is the error they receive when they are trying to connect to the reader now, they are using a Galaxy S10e

```
com.stripe.stripeterminal.external.models.TerminalException: Bluetooth unexpectedly disconnected during operation.
       at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.onDisconnect(BbposBluetoothAdapter.kt:128)
       at com.stripe.stripeterminal.adapter.BbposAdapter.registerReaderDisconnectHandler$lambda-12(BbposAdapter.kt:403)
       at com.stripe.stripeterminal.adapter.BbposAdapter.lambda$JYXeDBofYmEiuWGtvUMLqu4c4YY()
       at com.stripe.stripeterminal.adapter.-$$Lambda$BbposAdapter$JYXeDBofYmEiuWGtvUMLqu4c4YY.accept(:4)
       at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onNext(ObservableSubscribeOn.java:58)
       at io.reactivex.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:308)
       at io.reactivex.subjects.PublishSubject.onNext(PublishSubject.java:228)
       at io.reactivex.subjects.SerializedSubject.onNext(SerializedSubject.java:104)
       at com.stripe.core.hardware.reactive.status.ReactiveReaderStatusListener.handleReaderDisconnect(ReactiveReaderStatusListener.kt:96)
       at com.stripe.core.hardware.status.ReaderStatusListener$DefaultImpls.handleReaderDisconnect$default(ReaderStatusListener.kt:34)
       at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$ConnectBluetoothReaderOperation$startConnectWithManualBonding$2.invoke(BbposBluetoothAdapter.kt:232)
       at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$ConnectBluetoothReaderOperation$startConnectWithManualBonding$2.invoke(BbposBluetoothAdapter.kt:228)
       at com.stripe.stripeterminal.BluetoothBondStateReceiverManager$BluetoothBondStateReceiver.onReceive(BluetoothBondStateReceiverManager.kt:55)
       at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1613)
       at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(:2)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:223)
       at android.app.ActivityThread.main(ActivityThread.java:7986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:603)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by TatsuUkraine** [comment]
Recently noticed the same error. stripe_m2 with Galaxy Tab A (7.1.1)
