### ISSUE TITLE
Unknown error listing locations from API

### ISSUE THREAD

**Issue by matthieutirelli-pro** [stripe/stripe-terminal-android#296]
Hi there,
I notice something weird, I'm trying to implement Stripe reader, but first I wanted to see how the stripe-terminal-android Example was working.
I want to test my reader in TEST mode with a test card.
My reader ( serial WPC323145029918 )  is detected, calls the Stripe api : 
```
class=RestClient message="url=https://api.stripe.com//v1/terminal/readers/discover request={"readers":["WPC323145029918"]}"
```

And then tries to list locations : 
```
class=RestClient message="url=https://api.stripe.com/v1/terminal/locations?limit=100 status=OK headers={access-control-allow-credentials=true, access-control-allow-methods=GET, POST, HEAD, OPTIONS, DELETE, access-control-allow-origin=*, access-control-expose-headers=Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required, access-control-max-age=300, cache-control=no-cache, no-store, content-length=92, content-type=application/json, date=Thu, 09 Mar 2023 11:58:53 GMT, idempotency-key=1678363132984unknownHkqToRK4, request-id=req_oBvxQUdK3Kc8XH, server=nginx, strict-transport-security=max-age=63072000; includeSubDomains; preload, stripe-version=2022-11-15} response={"hasMore":false}"
```

And an exception occurs : 
```
class=TerminalSession message="Unknown error listing locations from API"
                                                                                                    com.squareup.moshi.JsonDataException: Required value 'locations' (JSON name 'data') missing at $
                                                                                                    	at com.squareup.moshi.internal.Util.missingProperty(Util.java:660)
                                                                                                    	at com.stripe.stripeterminal.internal.common.api.ListLocationsResponseJsonAdapter.fromJson(ListLocationsResponseJsonAdapter.kt:58)
                                                                                                    	at com.stripe.stripeterminal.internal.common.api.ListLocationsResponseJsonAdapter.fromJson(ListLocationsResponseJsonAdapter.kt:24)
                                                                                                    	at com.squareup.moshi.internal.NullSafeJsonAdapter.fromJson(NullSafeJsonAdapter.java:41)
                                                                                                    	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
                                                                                                    	at com.stripe.stripeterminal.internal.common.proto.ProtoConverter.toSdkListLocationsResponse(ProtoConverter.kt:314)
                                                                                                    	at com.stripe.stripeterminal.internal.common.api.ApiClient.listLocations(ApiClient.kt:192)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$listLocations$1.invokeSuspend(TerminalSession.kt:480)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

It seems to be related to stripe test only and seems very close to https://github.com/stripe/stripe-terminal-android/issues/203

Any idea on what to change to avoid this error ?
I'm using example app, so app is com.stripe.example

**Comment by billfinn-stripe** [comment]
Hi @matthieutirelli-pro -- thanks for reporting. Can you try creating a location via the [Stripe API](https://stripe.com/docs/api/terminal/locations/create) and then try registering/connecting to the reader?

**Comment by matthieutirelli-pro** [comment]
Hello @billfinn-stripe, sorry for the delay, I tested to create one with API : 
When I check one with the test token it works : 
`< request-id: req_KkHvPgWh3bEk4V
`

```
curl -G https://api.stripe.com/v1/terminal/locations \ 
  -u sk_test_4eC***************: \
  -d limit=3
{
  "object": "list",
  "data": [
    {
      "id": "tml_FBWOnQYSxQyNE8",
      "object": "terminal.location",
      "address": {
        "city": "****",
        "country": "FR",
        "line1": "1 *****",
        "line2": "",
        "postal_code": "*****",
        "state": ""
      },
      "display_name": "Test",
      "livemode": false,
      "metadata": {}
    },
    {
      "id": "tml_FBT8QZzA3ncG8Z",
      "object": "terminal.location",
      "address": {
        "city": "San Francisco",
        "country": "US",
        "line1": "272 Valencia Street",
        "line2": "",
        "postal_code": "94110",
        "state": "CA"
      },
      "display_name": "TestingLocationForReza",
      "livemode": false,
      "metadata": {}
    },
    {
      "id": "tml_FBF8dATDL5nAad",
      "object": "terminal.location",
      "address": {
        "city": "San Francisco",
        "country": "US",
        "line1": "272 Valencia Street",
        "line2": "",
        "postal_code": "94110",
        "state": "CA"
      },
      "display_name": "TestingLocationForReza",
      "livemode": false,
      "metadata": {}
    }
  ],
  "has_more": true,
  "url": "/v1/terminal/locations"
}%```


But if I use a token obtained by the connection_token endpoint, the list is null : 
```
< request-id: req_ERE05pdBoPFI4k
```

```
curl -G https://api.stripe.com/v1/terminal/locations \ 
  -u pst_test_YWNjdF********: \
  -d limit=3
{
  "object": "list",
  "data": [],
  "has_more": false,
  "url": "/v1/terminal/locations"
}%
```

**Comment by matthieutirelli-pro** [comment]
Hey, forget my latest response, I mixed up different API keys, so my requests were hitting another account, I'll close my request, thanks for your help @billfinn-stripe
