### ISSUE TITLE
About the problem of not being able to find the Terminal class in the SDK

### ISSUE THREAD

**Issue by LuckyPhz** [stripe/stripe-terminal-android#309]
My stripeTerminalVersion is already the latest 2.19.0, why can't I find the Terminal class in the SDK, and I can't find this class even after downloading your Example and importing it into AndroidStudio
<img width="763" alt="WeChat1afb768402f0c16333d0b9670dd25391" src="https://user-images.githubusercontent.com/30281040/230267025-ae6fdfb6-7687-49a1-bb4a-3133f8b5cbf9.png">
<img width="675" alt="WeChat56730aa04ce33d86974f7c5cd530581a" src="https://user-images.githubusercontent.com/30281040/230267087-86960d3d-febf-41c2-b811-fffc9894c4cd.png">

**Comment by chr-stripe** [comment]
@LuckyPhz this seems to be working just fine for me, when using the current sources:

<img width="1608" alt="image" src="https://user-images.githubusercontent.com/108023228/231024500-2e53a22d-7728-43d6-8a6c-9f6c5feaaf1a.png">

A few questions for troubleshooting:

1. Which version of Android Studio are you using? Are you sure that your IDE and plugins are all up-to-date?
2. Did your IDE complete a Gradle Sync successfully? You can manually trigger that by clicking on this button in the toolbar:
    <img width="262" alt="image" src="https://user-images.githubusercontent.com/108023228/231024754-604690aa-d676-4c36-8152-27a7869e5e41.png">
3. Are you able to compile the sample project, either by clicking the ▶️ Run button in the IDE, or by running `./gradlew :javaapp:assembleDebug` from the command line?

**Comment by LuckyPhz** [comment]
I reported an error when connecting the reader, the error message is as follows

`2023-05-08 15:17:17.969 Strip...minal com...rder_helper  D  class=ConnectionTokenRepository message=fetchConnectionToken.onSuccess
2023-05-08 15:17:18.232 Strip...minal com...rder_helper  I  class=BbposControllerListener message=onBTDisconnected
2023-05-08 15:17:18.236 Strip...minal com...rder_helper  I  class=TransactionStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
2023-05-08 15:17:18.236 Strip...minal com...rder_helper  D  class=BbposProxyDiscoveryController message=stopDiscover
2023-05-08 15:17:18.238 Strip...minal com...rder_helper  I  class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2023-05-08 15:17:18.239 Strip...minal com...rder_helper  I  class=TerminalStatusManager message=notConnected.
2023-05-08 15:17:18.240 Strip...minal com...rder_helper  D  class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
2023-05-08 15:17:18.240 Strip...minal com...rder_helper  W  class=BbposBluetoothAdapterLegacy message="skipping disconnectReader"
2023-05-08 15:17:18.244 Strip...minal com...rder_helper  E  class=TerminalSession
                                                            com.stripe.stripeterminal.external.models.TerminalException: Could not connect to Stripe. Please retry.
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient$Companion.decodeResponse(ApiClient.kt:237)
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:219)
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient.activateReader(ApiClient.kt:61)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.OnlineDirectResourceRepository.activateReader(OnlineDirectResourceRepository.kt:122)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.DirectResourceRepositoryRouter.activateReader(DirectResourceRepositoryRouter.kt:54)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:52)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:51)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.withCurrentRepository(ProxyResourceRepository.kt:147)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:51)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1417)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$2(TerminalSession.kt:715)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$rYGQPNcZu27M8Fdv0ehwoLn0Un8(Unknown Source:0)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                            	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                            	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                            	at java.lang.Thread.run(Thread.java:923)
`

**Comment by billfinn-stripe** [comment]
Hi @LuckyPhz -- this appears to be a separate issue. In the future, please open a new Github issue.

To answer your question, the SDK needs to be able to communicate with stripe.com.

Separately, for a list of supported countries, please see:
https://stripe.com/docs/terminal#learn-about-terminal
