### ISSUE TITLE
Crash during firmware update

### ISSUE THREAD

**Issue by asdico** [stripe/stripe-terminal-android#314]
## Summary

When I connect a (new) terminal to my Android app, the terminal disconnects after a few seconds. Looking at the Logcat what I understand that it's the firmware update the problem. 

I get this exception:

> E/StripeTerminal: class=TerminalSession
    com.stripe.stripeterminal.external.models.TerminalException: Unexpected SDK error
        at com.stripe.stripeterminal.internal.common.makers.TerminalExceptionMaker$Companion.fromReaderUpdateException(TerminalExceptionMaker.kt:35)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$41.accept(BbposAdapterLegacy.kt:680)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$41.accept(BbposAdapterLegacy.kt:678)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
     Caused by: com.stripe.core.hardware.updates.ReaderUpdateException$UnexpectedError: Failed resolution of: [Ljava/nio/file/LinkOption;
        at com.stripe.core.readerupdate.UpdateInstaller.fail(UpdateInstaller.kt:138)
        at com.stripe.core.readerupdate.UpdateInstaller.install(UpdateInstaller.kt:57)
        at com.stripe.stripeterminal.internal.common.transaction.InstallUpdatesHandler.onEnter(TransactionStates.kt:318)
        at com.stripe.stripeterminal.internal.common.transaction.InstallUpdatesHandler.onEnter(TransactionStates.kt:312)
        at com.stripe.core.statemachine.StateMachine.transitionTo(StateMachine.kt:87)
        at com.stripe.core.statemachine.StateMachine$StateHandler.transitionTo(StateMachine.kt:140)
        at com.stripe.stripeterminal.internal.common.transaction.EmptyHandler.onApplicationDataUpdate(TransactionStates.kt:122)
        at com.stripe.stripeterminal.internal.common.transaction.TransactionStateHandler.onUpdate(TransactionStates.kt:667)
        at com.stripe.stripeterminal.internal.common.transaction.TransactionStateHandler.onUpdate(TransactionStates.kt:654)
        at com.stripe.core.statemachine.StateMachine.updateData(StateMachine.kt:53)
        at com.stripe.stripeterminal.internal.common.transaction.TransactionStateMachine.update(TransactionStateMachine.kt:134)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.update(BbposAdapterLegacy.kt:771)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.update$default(BbposAdapterLegacy.kt:770)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$InstallUpdateOperation.execute(BbposAdapterLegacy.kt:1132)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$InstallUpdateOperation.execute(BbposAdapterLegacy.kt:1115)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.installUpdate(BbposAdapterLegacy.kt:302)
        at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.installUpdate(ProxyAdapter.kt:282)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$InstallUpdateOperation.executeIfNotCanceled(TerminalSession.kt:1718)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:895)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.handleMposDevice(TerminalSession.kt:1514)
E/StripeTerminal:     at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1449)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$2(TerminalSession.kt:715)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$rYGQPNcZu27M8Fdv0ehwoLn0Un8(TerminalSession.kt)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        	... 3 more

And this:

> E/StripeTerminal: class=TerminalSession
>     com.stripe.stripeterminal.external.models.TerminalException: Unexpected SDK error
>         at com.stripe.stripeterminal.internal.common.makers.TerminalExceptionMaker$Companion.fromReaderUpdateException(TerminalExceptionMaker.kt:35)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$41.accept(BbposAdapterLegacy.kt:680)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$41.accept(BbposAdapterLegacy.kt:678)
>         at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
>         at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
>         at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
>         at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
>         at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
>         at java.lang.Thread.run(Thread.java:761)
>      Caused by: com.stripe.core.hardware.updates.ReaderUpdateException$UnexpectedError: Failed resolution of: [Ljava/nio/file/LinkOption;
>         at com.stripe.core.readerupdate.UpdateInstaller.fail(UpdateInstaller.kt:138)
>         at com.stripe.core.readerupdate.UpdateInstaller.install(UpdateInstaller.kt:57)
>         at com.stripe.stripeterminal.internal.common.transaction.InstallUpdatesHandler.onEnter(TransactionStates.kt:318)
>         at com.stripe.stripeterminal.internal.common.transaction.InstallUpdatesHandler.onEnter(TransactionStates.kt:312)
>         at com.stripe.core.statemachine.StateMachine.transitionTo(StateMachine.kt:87)
>         at com.stripe.core.statemachine.StateMachine$StateHandler.transitionTo(StateMachine.kt:140)
>         at com.stripe.stripeterminal.internal.common.transaction.EmptyHandler.onApplicationDataUpdate(TransactionStates.kt:122)
>         at com.stripe.stripeterminal.internal.common.transaction.TransactionStateHandler.onUpdate(TransactionStates.kt:667)
>         at com.stripe.stripeterminal.internal.common.transaction.TransactionStateHandler.onUpdate(TransactionStates.kt:654)
>         at com.stripe.core.statemachine.StateMachine.updateData(StateMachine.kt:53)
>         at com.stripe.stripeterminal.internal.common.transaction.TransactionStateMachine.update(TransactionStateMachine.kt:134)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.update(BbposAdapterLegacy.kt:771)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.update$default(BbposAdapterLegacy.kt:770)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$InstallUpdateOperation.execute(BbposAdapterLegacy.kt:1132)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$InstallUpdateOperation.execute(BbposAdapterLegacy.kt:1115)
>         at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy.installUpdate(BbposAdapterLegacy.kt:302)
>         at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.installUpdate(ProxyAdapter.kt:282)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$InstallUpdateOperation.executeIfNotCanceled(TerminalSession.kt:1718)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:895)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.handleMposDevice(TerminalSession.kt:1514)
> E/StripeTerminal:     at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1449)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$2(TerminalSession.kt:715)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$rYGQPNcZu27M8Fdv0ehwoLn0Un8(TerminalSession.kt)
>         at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(R8$$SyntheticClass)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:237)
>         	... 3 more

While trying to update the firmware. 
The documentation says the BBPos Wisepad 3 is compatible with Android 4.1 (API level 16) but, if I'm not wrong (according to this topic https://stackoverflow.com/questions/18981757/how-to-use-java-nio-file-package-in-android) java.nio.file was added to Android in API level 26. 

I can do the first connection to the terminal using a more recent Android device, but it won't solve the problem for next updates. 

## Android version

Android O, API level 25

## Impacted devices (Android devices or readers)

I'm using the BBPos WisePad 3

## SDK version

I'm using the Android SDK 2.19.0

**Comment by rv-stripe** [comment]
Hey, can you provide the serial number for the device you saw this on?

**Comment by asdico** [comment]
I got 21 from Stripe, I tested a few and none of them worked.

The latest I used is:

WPC323211074324

Thank you

**Comment by rv-stripe** [comment]
Thanks. Looking into this and will update you here.

**Comment by rv-stripe** [comment]
@asdico 
After looking into this, we've determined this is related to an ongoing issue that should be fully addressed in an upcoming release. In the meantime, we've added a workaround to your account that should allow you to update and connect successfully using your Android O device.
Please continue to keep your SDK up to date to receive the full fix when it is released, and let us know if you run into any similar issues.

**Comment by asdico** [comment]
Indeed now it works! Thank you very much!

**Comment by asdico** [comment]
@rv-stripe Actually, it worked only for the terminal with the serial number that I shared. All the others still don't work - for a different reason now though.

Serial Number: WPC323211074341

> E/StripeTerminal: class=TerminalSession
    com.stripe.stripeterminal.external.models.TerminalException: Bluetooth unexpectedly disconnected during operation.
        at com.stripe.stripeterminal.internal.common.adapter.BbposBluetoothAdapterLegacy.onDisconnect(BbposBluetoothAdapterLegacy.kt:178)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$registerReaderDisconnectHandler$1.accept(BbposAdapterLegacy.kt:474)
        at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$registerReaderDisconnectHandler$1.accept(BbposAdapterLegacy.kt:469)
        at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
        at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
        at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by takeawayfinder** [comment]
Same issue, any updates on this?

**Comment by asdico** [comment]
@rv-stripe plus, now I'm working with Stripe connect, and it doesn't work. 
Can I send to the CS the connected account ids and get the same workaround for this? 
Thank you

**Comment by rv-stripe** [comment]
👋 Hello! A fix for this update issue was added into the 2.20.0version that we just released.
Please update your SDK as soon as you can and let me know that this fixed the issue for you.
