### ISSUE TITLE
 After initializing the Terminal after obtaining the location permission, the error message is still as follows

### ISSUE THREAD

**Issue by LuckyPhz** [stripe/stripe-terminal-android#318]
`05-09 19:05:22.797 21034 21034 I lloorder_helpe: Late-enabling -Xcheck:jni
05-09 19:05:22.849 21034 21034 I lloorder_helpe: Unquickening 12 vdex files!
05-09 19:05:24.964 21034 21034 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
05-09 19:05:24.969 21034 21034 D NetworkSecurityConfig: Using Network Security Config from resource network_security_config debugBuild: true
05-09 19:05:25.446 21034 21034 W lloorder_helpe: Accessing hidden method Landroid/view/View;->computeFitSystemWindows(Landroid/graphics/Rect;Landroid/graphics/Rect;)Z (greylist, reflection, allowed)
05-09 19:05:25.448 21034 21034 W lloorder_helpe: Accessing hidden method Landroid/view/ViewGroup;->makeOptionalFitsSystemWindows()V (greylist, reflection, allowed)
05-09 19:05:26.469 21034 21272 V QueueFileCollector: terminal_sdk_wire_metrics ready to use with 0 entries and 32 bytes.
05-09 19:05:26.494 21034 21275 V QueueFileCollector: terminal_sdk_wire_traces_2 ready to use with 0 entries and 32 bytes.
05-09 19:05:26.546 21034 21277 V QueueFileCollector: observabilitydata_wire ready to use with 0 entries and 32 bytes.
05-09 19:05:26.686 21034 21034 E StripeTerminal: class=Terminal
05-09 19:05:26.686 21034 21034 E StripeTerminal: com.stripe.stripeterminal.external.models.TerminalException: Location services must be enabled to use Terminal
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.stripe.stripeterminal.dagger.LocationServicesModule$provideLocationServicesValidator$1.validateLocationServices(LocationServicesModule.kt:30)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:954)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:888)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.stripe.stripeterminal.Terminal.initTerminal(Unknown Source:2)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.example.helloorder_helper.PosSettingActivity.init(PosSettingActivity.java:184)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.example.helloorder_helper.PosSettingActivity.handleUrlScheme(PosSettingActivity.java:98)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.example.helloorder_helper.PosSettingActivity.onCreate(PosSettingActivity.java:84)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.Activity.performCreate(Activity.java:8028)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.Activity.performCreate(Activity.java:8012)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.os.Looper.loop(Looper.java:223)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-09 19:05:26.686 21034 21034 E StripeTerminal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-09 19:05:26.767 21034 21034 W System.err: com.stripe.stripeterminal.external.models.TerminalException: Location services must be enabled to use Terminal
05-09 19:05:26.767 21034 21034 W System.err: 	at com.stripe.stripeterminal.dagger.LocationServicesModule$provideLocationServicesValidator$1.validateLocationServices(LocationServicesModule.kt:30)
05-09 19:05:26.767 21034 21034 W System.err: 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:954)
05-09 19:05:26.767 21034 21034 W System.err: 	at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:888)
05-09 19:05:26.768 21034 21034 W System.err: 	at com.stripe.stripeterminal.Terminal.initTerminal(Unknown Source:2)
05-09 19:05:26.768 21034 21034 W System.err: 	at com.example.helloorder_helper.PosSettingActivity.init(PosSettingActivity.java:184)
05-09 19:05:26.768 21034 21034 W System.err: 	at com.example.helloorder_helper.PosSettingActivity.handleUrlScheme(PosSettingActivity.java:98)
05-09 19:05:26.768 21034 21034 W System.err: 	at com.example.helloorder_helper.PosSettingActivity.onCreate(PosSettingActivity.java:84)
05-09 19:05:26.768 21034 21034 W System.err: 	at android.app.Activity.performCreate(Activity.java:8028)
05-09 19:05:26.768 21034 21034 W System.err: 	at android.app.Activity.performCreate(Activity.java:8012)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1309)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3404)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
05-09 19:05:26.769 21034 21034 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:106)
05-09 19:05:26.770 21034 21034 W System.err: 	at android.os.Looper.loop(Looper.java:223)
05-09 19:05:26.770 21034 21034 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:7660)
05-09 19:05:26.770 21034 21034 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
05-09 19:05:26.770 21034 21034 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
05-09 19:05:26.770 21034 21034 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
05-09 19:05:26.770 21034 21034 I System.out: 初始化异常
05-09 19:05:26.809 21034 21034 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10172; state: ENABLED
05-09 19:05:26.936 21034 21185 I mali_so : [File] : hardware/rockchip/mali_so/driver/product/base/src/mali_base_kbase.c; [Line] : 1311; [Func] : base_context_deal_with_version_affairs_rk_ext;
05-09 19:05:26.936 21034 21185 I mali_so : arm_release_ver of this mali_so is 'g2p0-01eac0', rk_so_ver is '8@0 '.
05-09 19:05:26.936 21034 21185 I mali_so : [File] : hardware/rockchip/mali_so/driver/product/base/src/mali_base_kbase.c; [Line] : 1327; [Func] : base_context_deal_with_version_affairs_rk_ext;
05-09 19:05:26.936 21034 21185 I mali_so : arm_release_vers are match. to set the full mali_ver 'g2p0-01eac0-x-8@0' as value of 'sys.gmali.version'.
05-09 19:05:26.933 21034 21034 I RenderThread: type=1400 audit(0.0:7126): avc: denied { write } for name="property_service" dev="tmpfs" ino=18684 scontext=u:r:untrusted_app:s0:c172,c256,c512,c768 tcontext=u:object_r:property_socket:s0 tclass=sock_file permissive=1 app=com.example.helloorder_helper
05-09 19:05:27.175 21034 21185 W libEGL  : EGLNativeWindowType 0xb4000071d682ee90 disconnect failed
05-09 19:05:27.285 21034 21034 W lloorder_helpe: Accessing hidden field Landroid/view/inputmethod/InputMethodManager;->mCurRootView:Landroid/view/ViewRootImpl; (blacklist, reflection, denied)
05-09 19:05:27.301 21034 21034 W StripeTerminal: class=TerminalLifecycleObserver message=applicationDidReceiveMemoryWarning memoryLevel=20 memoryProfile=TRIM_MEMORY_UI_HIDDEN appId=com.example.helloorder_helper
05-09 19:05:28.821 21034 21185 W libEGL  : EGLNativeWindowType 0xb4000071d682ee90 disconnect failed
05-09 19:06:26.417 21034 21267 D LogFlusher: Reporting 1 traces
05-09 19:06:27.173 21034 21267 D LogFlusher: Sent 1 traces
05-09 19:06:27.174 21034 21267 D LogFlusher: Reporting 2 events
05-09 19:06:27.235 21034 21267 D LogFlusher: Sent 2 events

`

**Comment by LuckyPhz** [comment]
problem solved
