### ISSUE TITLE
USB connection failing to update firmware

### ISSUE THREAD

**Issue by jbuda** [stripe/stripe-terminal-android#324]
## Summary

Using the USB connection method the terminal is recognised and connects. Whilst the terminal is doing the firmware update, it just  stops and indicates an exception. Updated to the most recent 2.20.0 of the SDK as was getting same results with previous version 2.18.

The firmware update seems to install ok but when making the update for the config, is where the error occurs. Always at the `0.7091837` mark.

Partial output of the log :

```class=BbposControllerListener message=onUsbConnected
class=BbposAssetInstallProcessor message="Connected to reader"
class=BbposApplicatorImpl message="Finished installing Firmware(remoteUpdate=Local(version=4.01.00.32, hex=DF87280501...))"
class=BbposApplicatorImpl message="Installing Config(remoteUpdate=Local(version=szzz_prod_eu_w1_off_v14, hex=DF87280501...)) [2 of 3]..."
class=BbposAssetInstallProcessor message="Waiting for installation to complete"
Setting up flushing for Thread[BB001-Thread,5,main]
class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.6663265."
class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.6663265)
Install progress 0.6663265 <--
class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.6785714."
class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.6785714)
Install progress 0.6785714 <--
class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.6846939."
class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.6846939)
Install progress 0.6846939 <--
class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.6877551."
class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.6877551)
Install progress 0.6877551 <--
class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.7091837."
class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.7091837)
Install progress 0.7091837 <--
close
class=BbposControllerListener message=onUsbDisconnected
class=TransactionManager message=endTransaction
class=TransactionStateMachine message="onStateChanged: INSTALL_UPDATES -> CANCELLED: null"
class=UpdateInstaller message=cancel
class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
class=BbposAssetInstallProcessor message="Cancelling installation"
class=TerminalSession
    com.stripe.stripeterminal.external.models.TerminalException: Not connected to reader
    	at com.stripe.stripeterminal.internal.common.makers.TerminalExceptionMaker$Companion.fromReaderUpdateException(TerminalExceptionMaker.kt:45)
    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$UpdateOperation.onUpdateException(BbposAdapterLegacy.kt:912)
    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$39.accept(BbposAdapterLegacy.kt:666)
    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapterLegacy$register$39.accept(BbposAdapterLegacy.kt:658)
    	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    	at java.lang.Thread.run(Thread.java:919)
    Caused by: com.stripe.core.hardware.updates.ReaderUpdateException$NotConnectedToReader: USB disconnected
    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError(BbposOtaListener.kt:161)
    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError$default(BbposOtaListener.kt:142)
    	at com.stripe.core.bbpos.BbposOtaListener.onReturnRemoteConfigUpdateResult(BbposOtaListener.kt:119)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.c(SourceFile:1)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.$r8$lambda$nDQkhMP9x0WkOR4N1sATootLlvE(Unknown Source:0)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController$$ExternalSyntheticLambda5.run(Unknown Source:4)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
class=BbposAssetInstallProcessor message="Installation cancelled with exception"
    com.stripe.core.hardware.updates.ReaderUpdateException$NotConnectedToReader: USB disconnected
    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError(BbposOtaListener.kt:161)
    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError$default(BbposOtaListener.kt:142)
    	at com.stripe.core.bbpos.BbposOtaListener.onReturnRemoteConfigUpdateResult(BbposOtaListener.kt:119)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.c(SourceFile:1)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.$r8$lambda$nDQkhMP9x0WkOR4N1sATootLlvE(Unknown Source:0)
    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController$$ExternalSyntheticLambda5.run(Unknown Source:4)
    	at android.os.Handler.handleCallback(Handler.java:883)
    	at android.os.Handler.dispatchMessage(Handler.java:100)
    	at android.os.Looper.loop(Looper.java:214)
    	at android.app.ActivityThread.main(ActivityThread.java:7356)
    	at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
class=BbposApplicatorImpl message="Cancelled while installing Config(remoteUpdate=Local(version=szzz_prod_eu_w1_off_v14, hex=DF87280501...))"
                                                                                                    kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@f526150
class=TerminalStatusManager message=finishInstallingUpdate.
class=ProxyReaderListener message=onFinishInstallingUpdate version=4.01.00.32-szzz_prod_eu_w1_off_v14-510001 exception?=true
Install finished
class=UpdateInstaller message=completeCancel
class=UpdateInstaller message=reset
class=BbposUsbAdapterLegacy message=disconnectReader
class=TransactionManager message=endTransaction
class=TransactionStateMachine message="onStateChanged: EMPTY -> DISCONNECT: Disconnect requested"
class=BbposReaderConnectionController message=disconnectUsb
class=BbposDeviceControllerImpl message=stopUsb
class=BbposControllerListener message="onError COMM_LINK_UNINITIALIZED, Cannot stop USB because USB is not connected."
class=TransactionStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
class=BbposProxyDiscoveryController message=stopDiscover
class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"

**Comment by chr-stripe** [comment]
Hi @jbuda, thanks for the report! This is indeed a known issue and affects reader updates taking place when connected via USB. While we do encounter the unexpected disconnect after the firmware phase finishes, reconnecting again – even via USB – _should_ complete the update successfully. Connecting to the reader via Bluetooth instead seems to be entirely unaffected by this bug.

Thankfully, this will be fixed in the upcoming `2.21.0` SDK release. I can leave this issue open until that version has been released and ping you here once it's available for use.

**Comment by jbuda** [comment]
Great, thanks for responding @chr-stripe. 

Unfortunately we are trying to integrate with USB due to the unreliability with Bluetooth and random disconnections. 

When do you think the `2.21.0` will be released?

**Comment by chr-stripe** [comment]
We're targeting some time next week for the next SDK release to be available.

**Comment by jbuda** [comment]
Great, ill keep an eye out for that release. Thanks @chr-stripe

**Comment by chr-stripe** [comment]
Terminal SDK `2.21.0` has been released, which should resolve these update issues when connected via USB. I'll close this issue out but feel free to reopen if you're still seeing this issue!

**Comment by scottfits** [comment]
In version 3.6.0 this error still happens for me, stopping at 13% or so.

**Comment by chr-stripe** [comment]
Hi @scottfits, can you please file a new GitHub issue using the [bug report template](https://github.com/stripe/stripe-terminal-android/issues/new?assignees=&labels=&projects=&template=terminal-android-sdk-issue.md&title=) so we can investigate?
