### ISSUE TITLE
Getting gradle error while trying to add stripeterminal-localmobile for Tap To Pay

### ISSUE THREAD

**Issue by arbaz8dots** [stripe/stripe-terminal-android#325]
Getting below error while trying to add stripeterminal-localmobile dependencies with stripe-android and stripe-java dependencies 

2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties'.

## Summary
**Getting below error while trying to add stripeterminal-localmobile dependencies with stripe-android and stripe-java dependencies 
2 files found with path 'org/bouncycastle/x509/CertPathReviewerMessages_de.properties'.**

**And if I trying to solve error using packagingOptions getting below run time error when discover local reader** 
Process: com.stripe.cots.aidlservice, PID: 32111
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.s.b.Dashboard.Dashboard(Unknown Source:0)
                                                                                                    	at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26)
                                                                                                    	at android.app.Service.attach(Service.java:915)
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                                    Caused by: java.lang.RuntimeException: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
                                                                                                    	at com.s.b.Dashboard.<clinit>(:275)
                                                                                                    	at com.s.b.Dashboard.Dashboard(Unknown Source:0) 
                                                                                                    	at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26) 
                                                                                                    	at android.app.Service.attach(Service.java:915) 
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
                                                                                                    Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
                                                                                                    	at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
                                                                                                    	at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
                                                                                                    	at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
                                                                                                    	at java.util.jar.JarVerifier.update(JarVerifier.java:229)
                                                                                                    	at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
                                                                                                    	at java.util.jar.JarFile.getInputStream(JarFile.java:460)
                                                                                                    	at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
                                                                                                    	at java.net.URL.openStream(URL.java:1072)
                                                                                                    	at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
                                                                                                    	at java.lang.Class.getResourceAsStream(Class.java:2246)
                                                                                                    	at com.s.b.Dashboard.<clinit>(:2410)
                                                                                                    	at com.s.b.Dashboard.Dashboard(Unknown Source:0) 
                                                                                                    	at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26) 
                                                                                                    	at android.app.Service.attach(Service.java:915) 
                                                                                                    	at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226) 
                                                                                                    	at android.os.Looper.loop(Looper.java:313) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8757) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 

## Code to reproduce
   implementation 'com.stripe:stripe-android:19.3.0'
    implementation 'com.stripe:stripe-java:20.107.0'
    implementation "com.stripe:stripeterminal-localmobile:2.19.0"
    implementation "com.stripe:stripeterminal-core:2.19.0"

## Android version
Android 12 

## Impacted devices (Android devices or readers)
Local reader for tap to pay 

## SDK version
2.19.0

**Comment by htcardone** [comment]
You can fix that by adding the following on your app's `build.gradle`:
```
android {
    ...
    packagingOptions {
        pickFirst  '**'
    }
}
```

**Comment by arbaz8dots** [comment]
@htcardone as already mentioned in issue I tried adding below 

android {
    ...
    packagingOptions {
        pickFirst  '**'
    }
}

But getting below exception when trying to discover local reader 

Process: com.stripe.cots.aidlservice, PID: 32111
java.lang.ExceptionInInitializerError
at com.s.b.Dashboard.Dashboard(Unknown Source:0)
at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26)
at android.app.Service.attach(Service.java:915)
at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071)
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:226)
at android.os.Looper.loop(Looper.java:313)
at android.app.ActivityThread.main(ActivityThread.java:8757)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
Caused by: java.lang.RuntimeException: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
at com.s.b.Dashboard.(:275)
at com.s.b.Dashboard.Dashboard(Unknown Source:0) 
at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26) 
at android.app.Service.attach(Service.java:915) 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071) 
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:226) 
at android.os.Looper.loop(Looper.java:313) 
at android.app.ActivityThread.main(ActivityThread.java:8757) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067) 
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
at sun.security.util.SignatureFileVerifier.processImpl(SignatureFileVerifier.java:314)
at sun.security.util.SignatureFileVerifier.process(SignatureFileVerifier.java:268)
at java.util.jar.JarVerifier.processEntry(JarVerifier.java:317)
at java.util.jar.JarVerifier.update(JarVerifier.java:229)
at java.util.jar.JarFile.initializeVerifier(JarFile.java:393)
at java.util.jar.JarFile.getInputStream(JarFile.java:460)
at libcore.io.ClassPathURLStreamHandler$ClassPathURLConnection.getInputStream(ClassPathURLStreamHandler.java:162)
at java.net.URL.openStream(URL.java:1072)
at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:989)
at java.lang.Class.getResourceAsStream(Class.java:2246)
at com.s.b.Dashboard.(:2410)
at com.s.b.Dashboard.Dashboard(Unknown Source:0) 
at com.stripe.cots.aidlservice.CotsService.attachBaseContext(Unknown Source:26) 
at android.app.Service.attach(Service.java:915) 
at android.app.ActivityThread.handleCreateService(ActivityThread.java:5071) 
at android.app.ActivityThread.-$$Nest$mhandleCreateService(Unknown Source:0) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2428) 
at android.os.Handler.dispatchMessage(Handler.java:106) 
at android.os.Looper.loopOnce(Looper.java:226) 
at android.os.Looper.loop(Looper.java:313) 
at android.app.ActivityThread.main(ActivityThread.java:8757) 
at java.lang.reflect.Method.invoke(Native Method) 
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)

**Comment by maggiewhite-stripe** [comment]
Hi @arbaz8dots,

Using the stripe-java and stripe-android libraries at the same time is not supported. They have the same functionality so you should only need to use one.

I was able to get our test application to build with these dependencies:
```gradle
implementation 'com.stripe:stripe-android:19.3.0'
implementation "com.stripe:stripeterminal-localmobile:2.19.0"
implementation "com.stripe:stripeterminal-core:2.19.0"
```
by adding the following packaging option:
```gradle
android {
    ...
    packagingOptions {
        resources {
            excludes += 'org/bouncycastle/x509/CertPathReviewerMessages*'
        }
    }
```

**Comment by arbaz8dots** [comment]
@maggiewhite-stripe Thank you for your guide, Able to solve issue.
