### ISSUE TITLE
[BUG] com.stripe.stripeterminal.external.models.TerminalException: Not connected to reader. through reader update 

### ISSUE THREAD

**Issue by msoliman22** [stripe/stripe-terminal-android#350]
## Summary
I am running my app on android 9 so since I am not using the reader from 2 months there are some updates have to run when I tried to connect with the reader , so everytime the update progress will be reach to like 22% then it will thrown this error 
```

com.stripe.stripeterminal.external.models.TerminalException: Not connected to reader
    at com.stripe.stripeterminal.internal.common.makers.TerminalExceptionMaker$Companion.fromReaderUpdateException(TerminalExceptionMaker.kt:45)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$UpdateOperation.onUpdateException(BbposAdapter.kt:554)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$15.accept(BbposAdapter.kt:440)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$15.accept(BbposAdapter.kt:432)
                                                                                                    	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
                                                                                                    	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
                                                                                                    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
                                                                                                    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
                                                                                                    	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    Caused by: com.stripe.core.hardware.updates.ReaderUpdateException$NotConnectedToReader: USB disconnected
                                                                                                    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError(BbposOtaListener.kt:161)
                                                                                                    	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError$default(BbposOtaListener.kt:142)
                                                                                                    	at com.stripe.core.bbpos.BbposOtaListener.onReturnRemoteFirmwareUpdateResult(BbposOtaListener.kt:106)
                                                                                                    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.d(SourceFile:1)
                                                                                                    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.$r8$lambda$yLV7c84D_jiHUVI2q4oubquBza8(Unknown Source:0)
                                                                                                    	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController$$ExternalSyntheticLambda8.run(Unknown Source:4)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:193)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:6718)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

```
But if I run my on android 7 so everything is fine and update will be done successfully , then I can make success payment on android 9 after that for long time since there is no updates required after I installed it on android 7 device 

## Code to reproduce
```
override fun onStartInstallingUpdate(update: ReaderSoftwareUpdate, cancelable: Cancelable?) {
        runOnUiThread {
           
            pay1.isGone = true
            pay5.isGone = true
            pay10.isGone = true
            retry.isGone = true
            reset.isGone = true
            payment_success.isGone = true
            connected_text.isVisible = true
            connected_text.text = "Your Reader Updating"
        }

    }

    override fun onReportReaderSoftwareUpdateProgress(progress: Float) {
        runOnUiThread {
            connected_text.text = "Your Reader Updating ${(progress * 100).toInt()}%"
        }
    }

    override fun onFinishInstallingUpdate(update: ReaderSoftwareUpdate?, e: TerminalException?) {
        runOnUiThread {
            connected_text.text = "Updating is done"
        }
    }

    override fun onReportAvailableUpdate(update: ReaderSoftwareUpdate){
        runOnUiThread {
            Terminal.getInstance().installAvailableUpdate()

        }
    }
```

## Android version
android 9

## Impacted devices
rockship ZC339v
## Installation method
gradle

## Dependency Versions
    implementation "com.stripe:stripeterminal:2.22.0"

Updates are : 
 2.01.00.16-SZZZ_Prod_US_v1-480001
Tue Jul 04 14:49:34 CDT 2023

 2.01.00.17-SZZZ_Prod_US_v5-480001
 Mon Aug 21 19:00:00 CDT 2023

**Comment by chr-stripe** [comment]
Thank you for the report @msoliman22. Can you share the serial number of the reader you had experienced these update failures on? Also, what kind of device was the one running on Android 7?

**Comment by msoliman22** [comment]
SN : STRM261420

Device on android 7 :  Sunmi. K2-mini

**Comment by chr-stripe** [comment]
Can you recheck if that's the correct serial number? Usually there are a few more digits than just that.

**Comment by msoliman22** [comment]
STRM26142024475.   It’s this one sorry for that

**Comment by msoliman22** [comment]
another SN that I tested it today : STRM26138006281.   I can confirm with 100% certainity that the update is always failed on android 9. , we tried on two devices that using android 9 so both of them have same issue

**Comment by msoliman22** [comment]
these also my permissions : 
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE" />
    <uses-permission android:name="android.permission.BLUETOOTH" />
    <uses-permission android:name="android.permission.BLUETOOTH_CONNECT" />
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE" />
    <uses-permission android:name="android.permission.CHANGE_WIFI_STATE" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.WAKE_LOCK" />
    <uses-permission android:name="android.permission.SYSTEM_ALERT_WINDOW"/>
    <uses-permission android:name="android.permission.DISABLE_KEYGUARD" />
    <uses-permission android:name="android.permission.ACTION_MANAGE_OVERLAY_PERMISSION" />
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED" />
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION" />
    <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION" />

**Comment by chr-stripe** [comment]
Thank you for the additional info. We are tracking this issue internally now and I will provide you with any updates as we try to investigate this further

**Comment by justinadkins** [comment]
Hey @chr-stripe, I had tested `2.21.0` previously for this issue and had a reader update successfully but maybe I just got lucky or the latest firmware is to blame. We're seeing this issue as well, it surfaced in our internally testing again today. Here's a log trace:

```
07-14 17:51:26.274 10425 10702 D StripeTerminal: class=BbposUsbAdapter message=installUpdate
07-14 17:51:26.276 10425 10702 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: EMPTY -> INSTALL_UPDATES: Installing updates"
07-14 17:51:26.276 10425 10702 D StripeTerminal: class=UpdateInstaller message=install
07-14 17:51:26.277 10425 10702 D StripeTerminal: class=UpdateInstaller message=reset
07-14 17:51:26.277 10425 10702 D StripeTerminal: class=UpdateInstaller message="Downloading updates..."
07-14 17:51:26.279 10425 10702 D StripeTerminal: class=ArmadaIngesterImpl message=downloadUpdates
07-14 17:51:26.282 10425 10702 D StripeTerminal: class=ArmadaIngesterImpl message=downloadSettings
07-14 17:51:26.285 10425 10702 D StripeTerminal: class=UpdateInstaller message="Starting installation job..."
07-14 17:51:26.294 10425 10749 D StripeTerminal: class=BbposApplicatorImpl message="Installing Firmware(remoteUpdate=Ota(version=2.01.00.18)) [1 of 3]..."
07-14 17:51:27.389 10425 10749 D StripeTerminal: class=BbposAssetInstallProcessor message="Waiting for installation to complete"
07-14 17:51:27.942 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.0066326526."
07-14 17:51:27.944 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.0066326526)
07-14 17:51:28.825 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.033163264."
07-14 17:51:28.825 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.033163264)
07-14 17:51:28.852 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.04642857."
07-14 17:51:28.853 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.04642857)
07-14 17:51:28.949 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.05306122."
07-14 17:51:28.950 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.05306122)
07-14 17:51:32.242 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.0994898."
07-14 17:51:32.243 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.0994898)
07-14 17:51:32.366 10425 10749 I StripeTerminal: class=TerminalStatusManager message="reportReaderSoftwareUpdateProgress 0.13265306."
07-14 17:51:32.367 10425 10749 I StripeTerminal: class=ProxyReaderListener message=onReportReaderSoftwareUpdateProgress(0.13265306)
07-14 17:51:33.101 10425 10425 I StripeTerminal: class=BbposControllerListener message=onUsbDisconnected
07-14 17:51:33.242 10425 10749 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: INSTALL_UPDATES -> CANCELLED: null"
07-14 17:51:33.243 10425 10749 D StripeTerminal: class=UpdateInstaller message=cancel
07-14 17:51:33.248 10425 10749 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
07-14 17:51:33.254 10425 10749 D StripeTerminal: class=BbposAssetInstallProcessor message="Cancelling installation"
07-14 17:51:33.266 10425 10702 E StripeTerminal: class=TerminalSession
07-14 17:51:33.266 10425 10702 E StripeTerminal: com.stripe.stripeterminal.external.models.TerminalException: Not connected to reader
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.makers.TerminalExceptionMaker$Companion.fromReaderUpdateException(TerminalExceptionMaker.kt:45)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$UpdateOperation.onUpdateException(BbposAdapter.kt:555)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$15.accept(BbposAdapter.kt:441)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$15.accept(BbposAdapter.kt:433)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at java.lang.Thread.run(Thread.java:764)
07-14 17:51:33.266 10425 10702 E StripeTerminal: Caused by: com.stripe.core.hardware.updates.ReaderUpdateException$NotConnectedToReader: USB disconnected
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError(BbposOtaListener.kt:161)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError$default(BbposOtaListener.kt:142)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.onReturnRemoteFirmwareUpdateResult(BbposOtaListener.kt:106)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.d(SourceFile:1)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.$r8$lambda$yLV7c84D_jiHUVI2q4oubquBza8(Unknown Source:0)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController$$ExternalSyntheticLambda8.run(Unknown Source:4)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at android.os.Handler.handleCallback(Handler.java:873)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at android.os.Looper.loop(Looper.java:193)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-14 17:51:33.266 10425 10702 E StripeTerminal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-14 17:51:33.278 10425 10749 W StripeTerminal: class=BbposAssetInstallProcessor message="Installation cancelled with exception"
07-14 17:51:33.278 10425 10749 W StripeTerminal: com.stripe.core.hardware.updates.ReaderUpdateException$NotConnectedToReader: USB disconnected
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError(BbposOtaListener.kt:161)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.handleOTAResultError$default(BbposOtaListener.kt:142)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.core.bbpos.BbposOtaListener.onReturnRemoteFirmwareUpdateResult(BbposOtaListener.kt:106)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.d(SourceFile:1)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController.$r8$lambda$yLV7c84D_jiHUVI2q4oubquBza8(Unknown Source:0)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.stripe.bbpos.bbdevice.ota.BBDeviceOTAController$$ExternalSyntheticLambda8.run(Unknown Source:4)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at android.os.Handler.handleCallback(Handler.java:873)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at android.os.Looper.loop(Looper.java:193)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at java.lang.reflect.Method.invoke(Native Method)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-14 17:51:33.278 10425 10749 W StripeTerminal: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-14 17:51:33.298 10425 10749 W StripeTerminal: class=BbposApplicatorImpl message="Cancelled while installing Firmware(remoteUpdate=Ota(version=2.01.00.18))"
07-14 17:51:33.298 10425 10749 W StripeTerminal: kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled; job=StandaloneCoroutine{Cancelling}@af1f8e1
07-14 17:51:33.312 10425 10702 I StripeTerminal: class=TerminalStatusManager message=finishInstallingUpdate.
07-14 17:51:33.313 10425 10749 D StripeTerminal: class=UpdateInstaller message=completeCancel
07-14 17:51:33.315 10425 10702 I StripeTerminal: class=ProxyReaderListener message=onFinishInstallingUpdate version=2.01.00.18-SZZZ_Prod_US_v9-480001 exception?=true
07-14 17:51:33.317 10425 10749 D StripeTerminal: class=UpdateInstaller message=reset
07-14 17:51:33.582 10425 10514 D StripeTerminal: class=Terminal message=disconnectReader
07-14 17:51:33.586 10425 10702 D StripeTerminal: class=BbposUsbAdapter message=disconnectReader
07-14 17:51:33.587 10425 10702 I StripeTerminal: class=ReaderBatteryInfoPoller message="ReaderBatteryInfoPoller endPolling"
07-14 17:51:33.591 10425 10702 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: EMPTY -> DISCONNECT: Disconnect requested"
07-14 17:51:33.591 10425 10702 I StripeTerminal: class=BbposReaderConnectionController message=disconnectUsb
07-14 17:51:33.592 10425 10702 D StripeTerminal: class=BbposDeviceControllerImpl message=stopUsb
07-14 17:51:33.636 10425 10425 I StripeTerminal: class=BbposControllerListener message="onError COMM_LINK_UNINITIALIZED, Cannot stop USB because USB is not connected."
07-14 17:51:33.638 10425 10749 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
07-14 17:51:33.638 10425 10749 D StripeTerminal: class=BbposProxyDiscoveryController message=stopDiscover
07-14 17:51:33.639 10425 10749 I StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
07-14 17:51:33.639 10425 10702 W StripeTerminal: class=BbposUsbAdapter message="skipping disconnectReader"
07-14 17:51:33.640 10425 10702 I StripeTerminal: class=TerminalStatusManager message=notConnected.
07-14 17:51:33.640 10425 10702 D StripeTerminal: class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
07-14 17:51:33.640 10425 10702 D StripeTerminal: class=ProxyTerminalListener message=onPaymentStatusChange(NOT_READY)
```

Reader Serial: `STRM26138002894`
Current firmware `2.01.00.17`
Firmware available: `2.01.00.18-SZZZ_Prod_US_v9-480001`
Android: `9`
Chipset: `rk30board`

**Comment by justinadkins** [comment]
Another important call out is since this is an optional update, when it fails, the reader remains "connected". However, when we go to checkout the reader will not work. PI creation works and we are prompted to insert, tap, swipe but the reader doesn't function.

**Comment by msoliman22** [comment]
any updates?  thx!!

**Comment by msoliman22** [comment]
another question when the update is fail like that so I can not reconnect or discover readers again in this case what I need to do in this case so I can recover and let the user try other options ?

**Comment by chr-stripe** [comment]
Thank you all for your patience. We have identified a fix for the issue of Stripe M2 readers being disconnected during a reader update when connected to certain kinds of hardware devices over USB. We are currently rolling out a new firmware version `2.01.00.20` that should no longer cause this to happen. This update is currently optional and can be installed via [`Terminal.getInstance().installAvailableUpdate()`](https://stripe.dev/stripe-terminal-android/core/com.stripe.stripeterminal/-terminal/install-available-update.html). It is currently slated to be a required update by November 30th, at which point the Terminal SDK will require that this update be installed in order to connect to your Stripe M2 reader.

Unfortunately, in order to install this new firmware, you will need to apply the update using a method that avoids the failure described in this ticket. This means either using the original Android host device but connected to the reader over Bluetooth, using a _different_ Android host device connected to the reader by USB or Bluetooth, or using an iOS host device connected to the reader over Bluetooth.

Once your Stripe M2 reader is on the `2.01.00.20` firmware, future reader updates should work just fine on any device using any connectivity method.
