### ISSUE TITLE
3.3.3-b6 SDK Failed to Get Card Last 4 Digits in Offline

### ISSUE THREAD

**Issue by ohmyleonia** [stripe/stripe-terminal-android#354]
## Summary

While we operate offline sdk (com.stripe:stripeterminal:3.0.0-b6), there were error caused. The logs can be found below. After error reported, we change the _updatePaymentIntent_ to false when using _collectPaymentMethod_. The issues was fixed then. However, we can no longer get the card last 4 digits, which in previous version (com.stripe:stripeterminal:3.0.0-b1) works good.

So why can't we get the last 4 digits of the card anymore? We would like to know if it will be retrieved in future versions. It is influencing our processing flow to open a tab at the restaurant currently.

## Code to reproduce

**Error Logs at first place:**
class=TerminalSession
com.stripe.stripeterminal.external.models.TerminalException: Updating PaymentIntents is not supported while offline mode is enabled.
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CollectPaymentMethodOperation.executeIfNotCanceled(TerminalSession.kt:1189)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:1043)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1001)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:860)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(TerminalSession.kt)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Code for not receiving card last 4 digits:**
CollectConfiguration collectConfig = new CollectConfiguration.Builder()
        .updatePaymentIntent(false)
        .build();
Terminal.getInstance().collectPaymentMethod(currentPaymentIntent,callback,collectConfig);

## Android version

9
## Impacted devices (Android devices or readers)

Stripe Reader M2 (STRM26138020431)
Firmware :   2.01.00.17
## SDK version

com.stripe:stripeterminal:3.0.0-b6

**Comment by billfinn-stripe** [comment]
Hi @ohmyleonia -- sorry for the slow response here -- can you upgrade to the latest public version (3.2.0), enable operating offline mode via the config API [0], and try again? The last4 for offline mode was added in 3.0.0-b7.

[0] https://stripe.com/docs/terminal/features/operate-offline/collect-payments?terminal-sdk-platform=android&reader-type=bluetooth#enable-offline-mode
