### ISSUE TITLE
Discovering doesn't work after device restarting

### ISSUE THREAD

**Issue by KucherenkoIhor** [stripe/stripe-terminal-android#358]
my steps
discover readers with stripe sdk
connect a reader with stripe sdk (reader is paired in bluetooth system settings)
reboot device
after rebooting the reader is not connected (reader is not paired in bluetooth system settings)
and all my readers don't appear in discovery list

BUT discovery works if I unpair the reader with sdk before rebooting

Discovering doesn't work after device rebooting. At the same time I readers can be found with the following code

```kotlin
 val bluetoothAdapter = BluetoothAdapter.getDefaultAdapter()

        val bluetoothLeScanner = bluetoothAdapter.bluetoothLeScanner
        var scanning = false
        val handler = Handler()

// Stops scanning after 10 seconds.
        val SCAN_PERIOD: Long = 10000

// Device scan callback.
        val leScanCallback: ScanCallback = object : ScanCallback() {
            override fun onScanResult(callbackType: Int, result: ScanResult) {
                super.onScanResult(callbackType, result)
                if (result.device.name == "STRM26122000078") {
                    Log.d("TAAAG", "result" + result.device + " " + result.device.name)
                }
            }

            override fun onScanFailed(errorCode: Int) {
                super.onScanFailed(errorCode)
                Log.d("TAAAG", "errorCode:" + errorCode)
            }
        }

        if (!scanning) { // Stops scanning after a pre-defined scan period.
            handler.postDelayed({
                scanning = false
                bluetoothLeScanner.stopScan(leScanCallback)
            }, SCAN_PERIOD)
            scanning = true
            bluetoothLeScanner.startScan(leScanCallback)
        } else {
            scanning = false
            bluetoothLeScanner.stopScan(leScanCallback)
        }
```
Discovering starts work only if turn off and on bluetooth in settings.
We don't have this bug with our another device with Android 8. 

## logs
```
BluetoothAdapter: isLeEnabled(): ON
StripeTerminal: class=Terminal message=discoverReaders
StripeTerminal: class=BbposBluetoothAdapter message=discoverReaders
StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
StripeTerminal: class=BbposProxyDiscoveryController message=discover
BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=6 mScannerId=0
StripeTerminal: class=ProxyOfflineListener message=onNetworkStatusChange
StripeTerminal: class=DefaultOfflineTraceManager message="Start forwarding" isAlreadyForwarding=true
TAAAG: resultC8:F5:D6:31:0C:5C STRM26122000078
StripeTerminal: class=BluetoothBondStateReceiver message=stopListening
StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: DISCOVER -> CANCELLED: null"
StripeTerminal: class=BbposProxyDiscoveryController message=stopDiscover
StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
StripeTerminal: class=TerminalSession
    com.stripe.stripeterminal.external.models.TerminalException: Bluetooth scan timed out
        at com.stripe.stripeterminal.internal.common.adapter.BbposBluetoothAdapter$DiscoverBluetoothReadersOperation$execute$$inlined$schedule$1.run(Timer.kt:151)
        at java.util.TimerThread.mainLoop(Timer.java:562)
        at java.util.TimerThread.run(Timer.java:512)

```

I don't see any system errors in logcat. and my code is able to discover the reader

our discovery function
```kotlin
 override fun discoverDevices(callback: (() -> Unit)?) {
        Timber.d("Trying to start readers discovery")
        launch { stripeStateStore.dispatch(StripeReaderManagerStateChangeAction.ClearDiscoverStripeReaders) }
        if (terminalHolder.isTerminalInitialized && discoveryTask == null && bluetoothManager.isBluetoothEnabled() && connectedReader == null) {
            val config = DiscoveryConfiguration(
                timeout = DISCOVERY_TIMEOUT,
                discoveryMethod = DiscoveryMethod.BLUETOOTH_SCAN,
                isSimulated = isTerminalSimulated
            )
            val discoveryCallback = object : Callback {
                override fun onSuccess() {
                    Timber.d("DiscoverDevices succeed")
                    discoveryTask = null
                    callback?.invoke()
                }

                override fun onFailure(e: TerminalException) {
                    discoveryTask = null
                    when (e.errorCode) {
                        TerminalException.TerminalErrorCode.BLUETOOTH_SCAN_TIMED_OUT -> discoverDevices(callback)
                        else -> Timber.e(Exception("DiscoverDevices: ${e.errorMessage} with code ${e.errorCode}"))
                    }
                }
            }
            discoveryTask = terminalHolder.terminal.discoverReaders(
                config = config,
                discoveryListener = discoveryListener,
                callback = discoveryCallback
            )
        }
    }
```    

## Android version
11

## Impacted devices (Android devices or readers)
any reader. HP Engage One Essential All in one System

## SDK version
2.22.0

**Comment by chr-stripe** [comment]
Hi @KucherenkoIhor, thank you for the report. Are you able to reproduce this issue with [one of the example apps](https://github.com/stripe/stripe-terminal-android/tree/master/Example) in this repo as well?

**Comment by KucherenkoIhor** [comment]
Hey @chr-stripe 
it looks working with example
Could you please tell me any reason why it may help with our project?

**Comment by KucherenkoIhor** [comment]
by some reasong I can see in logs this error from time to time
```
2023-07-27 13:48:49.972 2601-2670/com.wix.post.payment D/StripeTerminal: class=ProxyAdapter message="Switching from null to BbposBluetoothAdapter"
2023-07-27 13:48:49.983 2601-2670/com.wix.post.payment D/StripeTerminal: class=BbposBluetoothAdapter message=discoverReaders
2023-07-27 13:48:49.986 2601-2670/com.wix.post.payment I/StripeTerminal: class=ConnectAndUpdateStateMachine message="onStateChanged: EMPTY -> DISCOVER: Discovery requested"
2023-07-27 13:48:49.986 2601-2670/com.wix.post.payment D/StripeTerminal: class=BbposProxyDiscoveryController message=discover
2023-07-27 13:48:49.987 2601-2670/com.wix.post.payment D/BluetoothAdapter: isLeEnabled(): ON
2023-07-27 13:48:49.989 743-1169/? I/bt_stack: [INFO:gatt_api.cc(947)] GATT_Register 6112b5cd-4571-a5e7-0e3f-48b7c591f728
2023-07-27 13:48:49.989 743-1169/? I/bt_stack: [INFO:gatt_api.cc(967)] allocated gatt_if=5
2023-07-27 13:48:49.989 2601-2618/com.wix.post.payment D/BluetoothLeScanner: onScannerRegistered() - status=0 scannerId=5 mScannerId=0
2023-07-27 13:48:49.991 743-758/? E/BluetoothUtils: Permission denial: Need ACCESS_FINE_LOCATION permission to get scan results
```

But the app has this permission

**Comment by KucherenkoIhor** [comment]
@chr-stripe 
resolved
we init terminal while our app in the background
ACCESS_BACKGROUND_LOCATION permission is needed for this
it works with this permission ACCESS_BACKGROUND_LOCATION
