### ISSUE TITLE
Possible Firebase related crash

### ISSUE THREAD

**Issue by atrauzzi** [stripe/stripe-terminal-android#367]
I recently configured Firebase Crashlytics, Analytics and Performance Monitoring for my app which makes use of Stripe Tap to Pay on Android.

Unfortunately it looks like when I try to enable the production mode NFC reader in my production version of the app (no debug!), I get this error:

```
FATAL EXCEPTION: main
Process: com.mycompany.myapp, PID: 29650
com.stripe.stripeterminal.external.models.TerminalException: com.google.firebase.perf.config.RemoteConfigManager
at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(CotsAdapter.kt:319)
at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(CotsAdapter.kt:248)
at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(ProxyAdapter.kt:97)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.activateReader$terminalsession_release(TerminalSession.kt:511)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1569)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:979)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:838)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(Unknown Source:0)
at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:463)
at java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@8550e64, androidx.compose.runtime.BroadcastFrameClock@bf1c8cd, StandaloneCoroutine{Cancelling}@caf2582, AndroidUiDispatcher@88cc493]
```

Compile SDK is 34, Min SDK is 31 and target SDK is 33.

**Comment by Ekalips** [comment]
@atrauzzi We've also faced the same issue, it indeed happens because Stripe SDK spins up a separate process that also goes through the Application.onCreate and cause crashes if you have anything Firebase related there. 

What you can do instead of initialising Firebase in child processes is to flip the logic around. If "current process" != "main/first process" - don't do anything in your Application.onCreate. The crash only happens when you try to do things with Firebase in that process and as Stripe's process by itself doesn't touch Firebase - it's only your Application.onCreate that could trigger it.

**Comment by chr-stripe** [comment]
I'm happy to report that in version 4.4.0 of the Tap to Pay on Android SDK, we now have a `TapToPay.isInTapToPayProcess()` method that you can call from your integration to determine if you need to skip Application initialization. See our [public documentation](https://docs.stripe.com/terminal/payments/connect-reader?terminal-sdk-platform=android&reader-type=tap-to-pay#initialize) for more details on this.
