### ISSUE TITLE
SDK fails on Android 14 with `targetSdkVersion` to 34

### ISSUE THREAD

**Issue by yogen-p** [stripe/stripe-terminal-android#387]
## Summary
BT Reader discovery and Tap To Pay fail on devices running Android 14 with `targetSdkVersion` and `compileSdk` to 34.

## Code to reproduce
Set `targetSdkVersion` to 34 and run on an Android 14 device in `release` mode.

The Example Kotlin can be used to reproduce Tap To Pay payment crash by:
- Setting `latestSdkVersion = 34` in the project `build.gradle`
- Creating a `release` buildType with `debuggable` set to false.
- Creating and providing a `signingConfig` for the release build.
- Update `DiscoveryViewModel` to provide a `LocalMobileDiscoveryConfiguration()` object
- Update `ReaderClickListener` to call `Terminal.getInstance().connectLocalMobileReader(...)`
- Discover and connect to Tap To Pay
- Try taking a payment using "Collect card payment" CTA

## Android version
14

## Impacted devices (Android devices or readers)
Devices that upgraded to Android 14

## SDK version
I tested using 3.1.0, 2.23.2, and 2.22.0

## Other information
Everything works fine in debug mode. The issues arise in release mode for me with `minifyEnabled` and `shrinkResources` set to true.
Discovering readers doesn't discover anything, and Tap To Pay crashes while trying to take a payment with the following exception:
```
FATAL EXCEPTION: DefaultDispatcher-worker-2
Process: com.stripe.cots.aidlservice, PID: 25264
java.lang.RuntimeException: java.lang.SecurityException: Writable dex file '/data/user/0/com.checkfer.lopaymerchant/cache/.    ' is not allowed.
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
	at com.mastercard.terminalsdk.internal.n.<clinit>(Unknown Source:4285)
	at com.mastercard.terminalsdk.TerminalSdk.<init>(SourceFile:10)
	at com.mastercard.terminalsdk.TerminalSdk.getInstance(Unknown Source:9)
	at com.s.aa.Stripe$11661.<init>(:47)
	at com.s.ac.Connect$670.SDKs(:142)
	at com.s.ac.Connect$670.As(:36)
	at com.s.ac.Connect$670$3$8218.invokeSuspend(:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
	at kotlinx.coroutines.DispatchedTask.run(SourceFile:124)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@e516463, Dispatchers.IO]
Caused by: java.lang.SecurityException: Writable dex file '/data/user/0/com.checkfer.lopaymerchant/cache/.    ' is not allowed.
	at dalvik.system.DexFile.openDexFileNative(Native Method)
	at dalvik.system.DexFile.openDexFile(DexFile.java:406)
	at dalvik.system.DexFile.<init>(DexFile.java:171)
	at dalvik.system.DexFile.loadDex(DexFile.java:231)
	at dalvik.system.DexFile.loadDex(DexFile.java:198)
	at com.mastercard.terminalsdk.internal.n.<clinit>(Unknown Source:2489)
	... 14 more



class=AidlRpcClient message="Failed to send request to AIDL service"
android.os.DeadObjectException
	at android.os.BinderProxy.transactNative(Native Method)
	at android.os.BinderProxy.transact(BinderProxy.java:584)
	at com.stripe.core.aidlrpc.AidlRpc$Stub$Proxy.makeRequest(AidlRpc.java:142)
	at com.stripe.core.aidlrpcclient.AidlRpcClient$makeRequest$1.invoke(AidlRpcClient.kt:84)
	at com.stripe.core.aidlrpcclient.AidlRpcClient$makeRequest$1.invoke(AidlRpcClient.kt:73)
	at com.stripe.core.aidlrpcclient.AidlRpcClient.withAidlService(AidlRpcClient.kt:106)
	at com.stripe.core.aidlrpcclient.AidlRpcClient.makeRequest(AidlRpcClient.kt:73)
	at com.stripe.stripeterminal.internal.common.adapter.CotsClient.makeRequest(CotsClient.kt:181)
	at com.stripe.stripeterminal.internal.common.adapter.CotsClient.collectPayment(CotsClient.kt:150)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$collectPaymentMethodHandler$result$1.invokeSuspend(CotsAdapter.kt:147)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$collectPaymentMethodHandler$result$1.invoke(Unknown Source:8)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$collectPaymentMethodHandler$result$1.invoke(Unknown Source:4)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$callAidlWithExceptionConverted$1$1.invokeSuspend(CotsAdapter.kt:360)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:280)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:85)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:59)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source:1)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:38)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source:1)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.callAidlWithExceptionConverted(CotsAdapter.kt:360)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.collectPaymentMethodHandler(CotsAdapter.kt:146)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.collectPaymentMethod(CotsAdapter.kt:139)
	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.collectPaymentMethod(ProxyAdapter.kt:148)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CollectPaymentMethodOperation.executeIfNotCanceled(TerminalSession.kt:1271)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:1046)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1004)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:863)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(Unknown Source:0)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)


class=TerminalSession
com.stripe.stripeterminal.external.models.TerminalException: Contactless transaction failed com.stripe.core.aidlrpc.AidlRpcException: Failed to send request to AIDL server.
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.callAidlWithExceptionConverted(CotsAdapter.kt:371)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.collectPaymentMethodHandler(CotsAdapter.kt:146)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.collectPaymentMethod(CotsAdapter.kt:139)
	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.collectPaymentMethod(ProxyAdapter.kt:148)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CollectPaymentMethodOperation.executeIfNotCanceled(TerminalSession.kt:1271)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:1046)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1004)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:863)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(Unknown Source:0)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by ugochukwu-stripe** [comment]
Hi @yogen-p, thanks for bringing this up, we're currently working on a fix for this, and will update here once the fix is out.

**Comment by bperez-stripe** [comment]
Hi @yogen-p, you can target sdk version 33 while we work on this fix. We are working diligently to get this resolved but the updates are not trivial and are not expected to be ready in the next few days. We will provide an update once we have a clear timeline for an SDK update that addresses this issue.

**Comment by yogen-p** [comment]
@bperez-stripe @ugochukwu-stripe Thanks for your response. For the being, that is exactly what I did and reverted back to version 33 and will keep using it until this is fixed. I understand this is going to be a major change, and will require some time. All is good now, since I reverted back to 33. Thanks

**Comment by chr-stripe** [comment]
We have released version `3.1.1` which contains a fix for discovering Bluetooth readers on Android 14 with `targetSdkVersion 34`. Fixes for USB and Tap To Pay readers will come in a subsequent release. I'll update this ticket as those are available in the coming releases.

**Comment by chr-stripe** [comment]
We have released version `3.2.0` which contains a fix for discovering USB readers on Android 14 with `targetSdkVersion 34`. A fix for Tap To Pay readers will come in a subsequent release. I'll update this ticket again when that becomes available.

**Comment by chr-stripe** [comment]
We have released version `3.2.1` which contains a fix for taking payments using Tap To Pay readers on Android 14 with `targetSdkVersion 34`. This version should now be fully compatible with using any kind of reader while targetting the latest API version.

**Comment by parthasarathi95** [comment]
after installing the library i am getting this error on android

3 issues were found when checking AAR metadata:

  1.  Dependency 'androidx.activity:activity-ktx:1.8.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.3.1 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdkVerion of at least 34.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

  2.  Dependency 'androidx.activity:activity-compose:1.8.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.3.1 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdkVerion of at least 34.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).

  3.  Dependency 'androidx.activity:activity:1.8.0' requires libraries and applications that
      depend on it to compile against version 34 or later of the
      Android APIs.

      :app is currently compiled against android-33.

      Also, the maximum recommended compile SDK version for Android Gradle
      plugin 7.3.1 is 33.

      Recommended action: Update this project's version of the Android Gradle
      plugin to one that supports 34, then update this project to use
      compileSdkVerion of at least 34.

      Note that updating a library or application's compileSdkVersion (which
      allows newer APIs to be used) can be done separately from updating
      targetSdkVersion (which opts the app in to new runtime behavior) and
      minSdkVersion (which determines which devices the app can be installed
      on).
      
      
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.google.gms:google-services:4.3.15'
        classpath("com.android.tools.build:gradle:7.3.1")
        classpath("com.facebook.react:react-native-gradle-plugin")
    }
}

 "@notifee/react-native": "^7.8.0",
    "@react-native-async-storage/async-storage": "^1.18.1",
    "@react-native-firebase/app": "^18.3.1",
    "@react-native-firebase/messaging": "^18.3.1",
    "@react-navigation/drawer": "^6.6.2",
    "@react-navigation/material-top-tabs": "^6.6.2",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/native-stack": "^6.9.12",
    "@reduxjs/toolkit": "^1.9.5",
    "@stripe/stripe-react-native": "^0.35.0",
    "@stripe/stripe-terminal-react-native": "^0.0.1-beta.13",
    "axios": "^1.4.0",
    "email-validator": "^2.0.4",
    "lottie-react-native": "^5.1.5",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-date-picker": "^4.2.13",
    "react-native-dotenv": "^3.4.9",
    "react-native-gesture-handler": "^2.10.1",
    "react-native-google-places-autocomplete": "^2.5.1",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-modal": "^13.0.1",
    "react-native-pager-view": "^6.2.0",
    "react-native-reanimated": "^3.1.0",
    "react-native-safe-area-context": "^4.5.3",
    "react-native-screens": "^3.20.0",
    "react-native-shadow-2": "^7.0.8",
    "react-native-svg": "^13.9.0",
    "react-native-tab-view": "^3.5.1",
    "react-native-vector-icons": "^9.2.0",
    "react-redux": "^8.0.5",
    "redux": "^4.2.1"

need help.

**Comment by parthasarathi95** [comment]
now I am able to build the project.

**Comment by abhijitCN** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:checkDebugDuplicateClasses'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Failed to transform jackson-core-2.16.1.jar (com.fasterxml.jackson.core:jackson-core:2.16.1) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.

I am using =>
       {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 26
        compileSdkVersion = 34
        targetSdkVersion = 34
        ndkVersion = "25.1.8937393"
        kotlinVersion = "1.8.0"
        }
and
   "dependencies": {
    "@stripe/stripe-terminal-react-native": "^0.0.1-beta.16",
    "react": "18.2.0",
    "react-native": "0.73.6"
      }
 and gradle-8.3-all.zip for Android which version is wrong for me

**Comment by Zaynmiraj** [comment]
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
>   Execution failed for task ':app:checkDebugDuplicateClasses'.
> 
> > Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
> > Failed to transform jackson-core-2.16.1.jar (com.fasterxml.jackson.core:jackson-core:2.16.1) to match attributes {artifactType=enumerated-runtime-classes, org.gradle.category=library, org.gradle.dependency.bundling=external, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
> 
> I am using => { buildToolsVersion = "34.0.0" minSdkVersion = 26 compileSdkVersion = 34 targetSdkVersion = 34 ndkVersion = "25.1.8937393" kotlinVersion = "1.8.0" } and "dependencies": { "@stripe/stripe-terminal-react-native": "^0.0.1-beta.16", "react": "18.2.0", "react-native": "0.73.6" } and gradle-8.3-all.zip for Android which version is wrong for me

Also I had same problem

**Comment by chr-stripe** [comment]
Hi folks, this looks unrelated to the original issue reported here; I would recommend you file a separate issue so we can take a proper look. It also looks like you are using the React Native Terminal SDK so I'd recommend you file an issue in that repo instead: https://github.com/stripe/stripe-terminal-react-native

**Comment by davidvgalbraith** [comment]
Hi, in light of this issue's closure, is this line from the README out of date?
```
Note that attempting to override minSdkVersion to decrease the minimum supported API level will not work due to internal runtime API level validation. Furthermore, Stripe is updating the Terminal Android SDK to support Google’s recently released Android 14 (SDK 34). Please continue to target SDK 33 in the meantime as there are known issues with mPOS devices and TTP when targeting SDK 34. Please track the following https://github.com/stripe/stripe-terminal-android/issues/387 for updates on progress.
```

**Comment by nazli-stripe** [comment]
@davidvgalbraith yep the RN README is out of date, let me update
