### ISSUE TITLE
Tap to pay ATTESTATION_FAILURE (req_jEaC3nGwX1MDcH)

### ISSUE THREAD

**Issue by chance-yang** [stripe/stripe-terminal-android#394]
We encountered the following error while using Tap to pay to connect.(Attached are all the log information.
[log.txt](https://github.com/stripe/stripe-terminal-android/files/13233166/log.txt)
) Can you tell me what caused it?
com.stripe.stripeterminal.external.models.TerminalException: ATTESTATION_FAILURE (req_jEaC3nGwX1MDcH): 
Unexpected error encountered. Please try clearing the application data in the settings application and contact Stripe support if
the issue persists.

## Android version

Android 12
## SDK version

implementation "com.stripe:stripeterminal:2.20.1"
implementation "com.stripe:stripeterminal-localmobile:2.20.1"
implementation "com.stripe:stripeterminal-core:2.20.1"

**Comment by martinmroz-stripe** [comment]
Hey folks! Reviewing the log, it looks like there may be a clock-related issue with your device. Is it possible that the system time is out of sync? System time has to be accurate in order for attestation to pass. Would you mind verifying and letting us know if that resolves your issue?

**Comment by chance-yang** [comment]
Hi, thank you for your reply. I have checked the time on the device, and it is accurate. The logs previously provided were using the GMT+8 timezone, which works normally on another one of my devices. I've just switched the timezone to GMT-4 on this device, but it's still showing the same error. Could there be another reason?

**Comment by billfinn-stripe** [comment]
Hi @chance-yang -- can you confirm that you both:

1. Cleared the application data on the device; and
2. Have the device configured to set its current time using the network

Are you seeing this issue on any other device or just the one?

**Comment by chance-yang** [comment]
1. I have tried clearing the data, but the problem still persists.
2. yes, device's time is automatically obtained from the network.
My other Wiseasy Nano6 device also does not work, but it works on the Sunmi L2s.

**Comment by billfinn-stripe** [comment]
Got it. From our logs, we are unable to confirm the authenticity and security of the device. Considering that this issue is consistent across various devices of the same make and model and not present in devices from a different manufacturer, it could potentially be attributed to the Android OS implementation specific to that OEM.

We'll leave this issue open and file it in our backlog, but for now, you can limit your tap-to-pay use to devices that are not Wiseasy Nano6.

**Comment by yongzhi2701** [comment]
Hi Billfinn, 

Could you help to check this error?  what's mean for checkAndThrowCotsError? 

-----------------------------------------------------------------------------------

com.stripe.stripeterminal.external.models.TerminalException: ATTESTATION_FAILURE (req_GnVuoXgzruNPYQ): Unexpected error encountered. Please try clearing the application data in the settings application and contact Stripe support if the issue persists.
        at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(CotsAdapter.kt:307)
        at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(CotsAdapter.kt:236)
        at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(ProxyAdapter.kt:95)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1499)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:905)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$3(TerminalSession.kt:765)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$l3D1f-Vk5Q8NcJKxkmByt8wMjwc(Unknown Source:0)
        at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by billfinn-stripe** [comment]
For posterity, we followed up internally with the hardware manufacturer, and they are shipping a fix to certificate expiration dates.

**Comment by chance-yang** [comment]
@billfinn-stripe Thank you. The issue has been resolved after the certificate date update.
