### ISSUE TITLE
NoSuchMethodError com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity

### ISSUE THREAD

**Issue by cnhuz** [stripe/stripe-terminal-android#414]
## Summary

After implementation "com.stripe:stripeterminal:2.23.2" in my app. When the terminal is connected to an Android device via USB, a popup appears on the screen saying "Open <my app name> when this USB device is connected?" When I select "OK", the app crashes. In logcat, I see error messages:
```shell
java.lang.NoSuchMethodError: No static method getParcelableExtra(Landroid/content/Intent;Ljava/lang/String;Ljava/lang/Class;)Ljava/lang/Object; in class Landroidx/core/content/IntentCompat; or its super classes (declaration of 'androidx.core.content.IntentCompat' appears in /data/app/com.flygo.advertisingmachine-2/base.apk)
        at com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity.onResume(UsbEventReceiverActivity.kt:27)
        at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1257)
        at android.app.Activity.performResume(Activity.java:6323)
        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2997)
        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3039)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2412)
        at android.app.ActivityThread.access$800(ActivityThread.java:151)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1319)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5280)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
```

## Code to reproduce

NO, I integrated the reference example into my app.

## Android version

Android 5.1.1

Android 13

## Impacted devices (Android devices or readers)

NO

## SDK version

2.23.2

## Other information

I saw this code in the AndroidManifest.xml of com.stripe:stripeterminal-core:2.23.2
```xml
        <application>
		<activity android:excludeFromRecents="true" android:exported="false" android:label="@string/app_name" android:name="com.stripe.stripeterminal.internal.common.usb.UsbEventReceiverActivity" android:noHistory="true" android:taskAffinity="com.stripe.stripeterminal.taskAffinityUsbEventReceiver" android:theme="@style/Theme.Transparent">
			<intent-filter>
				<action android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED"/>
			</intent-filter>
			<meta-data android:name="android.hardware.usb.action.USB_DEVICE_ATTACHED" android:resource="@xml/usb_device_filter"/>
		</activity>
	</application>
```

**Comment by cnhuz** [comment]
I changed the version of `androidx.core:core-ktx`, and it worked fine.
`implementation "androidx.core:core-ktx:1.10.1"`

**Comment by chr-stripe** [comment]
Hi @cnhuz, thank you for reporting this as well as your mitigation.

For clarification, the `com.stripe:stripeterminal-core:2.23.2` dependency should already have a (transitive) compile-time dependency on `androidx.core:core-ktx:1.10.1`, so this should not have required any special handling. Were you perhaps doing some additional dependency resolution customizations in your application that would have caused an earlier version to be selected instead?

**Comment by cnhuz** [comment]
> Hi @cnhuz, thank you for reporting this as well as your mitigation.
> 
> For clarification, the `com.stripe:stripeterminal-core:2.23.2` dependency should already have a (transitive) compile-time dependency on `androidx.core:core-ktx:1.10.1`, so this should not have required any special handling. Were you perhaps doing some additional dependency resolution customizations in your application that would have caused an earlier version to be selected instead?

I previously specified the androidx.core:core-ktx version in resolutionStrategy.
```
configurations.all {
    resolutionStrategy {
        force 'androidx.core:core-ktx:1.6.0'
    }
}
```
