### ISSUE TITLE
Connecting after app restart don't work

### ISSUE THREAD

**Issue by anton8900** [stripe/stripe-terminal-android#43]
Please check this scenario:
1) Start app connect reader first time and maybe make some transaction, all works
2) Restart app
3) 
discoverReaders works, connectReader don't answer

getConnectedReader() in this case returns previous time connected reader
getConnectionStatus() returns CONNECTED

createPaymentIntent don't answer

**Comment by anton8900** [comment]
You can test this case for youself

**Comment by danwaters-stripe** [comment]
Are you able to reproduce this issue using the example app? I don't seem to be able to reproduce this behavior when I try.

**Comment by anton8900** [comment]
I using Land Rover X8 Android 5.1
So it worked only one first time and them i can't to connect at all
I have tried with example app and it don't work too
In logcat no errors or warnings

Only error that i have found in example that when you try to restart app it crashes with error 

06-04 07:44:10.979 10371-10371/com.stripe.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.stripe.example, PID: 10371
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.stripe.example/com.stripe.example.MainActivity}: java.lang.IllegalStateException: You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2534)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608)
        at android.app.ActivityThread.access$800(ActivityThread.java:178)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5637)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
     Caused by: java.lang.IllegalStateException: You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method.
        at com.stripe.stripeterminal.Terminal.initTerminal(Terminal.java:54)
        at com.stripe.example.MainActivity.initialize(MainActivity.kt:365)
        at com.stripe.example.MainActivity.onCreate(MainActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:6092)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2481)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2608) 
        at android.app.ActivityThread.access$800(ActivityThread.java:178) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
        at android.os.Handler.dispatchMessage(Handler.java:111) 
        at android.os.Looper.loop(Looper.java:194) 
        at android.app.ActivityThread.main(ActivityThread.java:5637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) 
06-04 07:44:16.704 10371-10399/com.stripe.example D/OpenGLRenderer: Flushing caches (mode 0)
06-04 07:44:16.707 10371-10384/com.stripe.example I/System.out: [CDS]close[0]

**Comment by anton8900** [comment]
That is logs from example when app stuck in connectiong
https://drive.google.com/file/d/1yPNzUGmd3JwRzLZkbW1jgKug814YkeXc/view?usp=sharing

I have found in messages that reader actually connected but no any callback received

**Comment by anton8900** [comment]
if you want i can change something in code to add more logs and send you again

**Comment by chander-stripe** [comment]
@anton8900 - are you still having this problem? Would you mind upgrading to the latest release candidate version and try again? We've done a significant amount of polish and additional logging, so it should be easier to debug. Let me know if this issue still persists, closing for now!
