### ISSUE TITLE
OOM crash after connecting NFC reader

### ISSUE THREAD

**Issue by jasells** [stripe/stripe-terminal-android#434]
## Summary
After connecting to NFC reader (30 sec or more sometimes). We get the following crash:

```
java.lang.OutOfMemoryError: Failed to allocate a 1129272416 byte allocation with 29686584 free bytes and 246MB until OOM, target footprint 39582112, growth limit 268435456
  at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:549)
  at com.squareup.tape2.QueueFile$ElementIterator.next(QueueFile.java:514)
  at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:388)
  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
  at java.lang.Thread.run(Thread.java:1012)
```

## Android version
13, 14

## Impacted devices (Android devices or readers)
Internal NFC reader/device

Pixel 4/4a
Samsung Galaxy S21FE
Lenovo Tab M8 (4th gen)

## SDK version
2.20.0 / 2.23.3  (much more prevalent)

## Other information
This seems to be the same issue posted on the tape2 [repo](https://github.com/square/tape/issues/173).

We only recently started seeing this in our branch where we were updating from 2.20.0 -> 2.23.3, however we just saw one report from our production app still on 2.20.0

Is there a reason stripe is using what appears to be a dead library?

**Comment by ugochukwu-stripe** [comment]
Hi @jasells, we rolled out a fix for a similar issue in `3.3.1`, could you try reproducing with the [latest release](https://github.com/stripe/stripe-terminal-android/releases) and let us know if you're still experiencing the same problem.

**Comment by ugochukwu-stripe** [comment]
Closing due to inactivity, feel free to open a new issue if you're still experiencing the same error
