### ISSUE TITLE
Corrupt proto payload in the queue: terminal_sdk_wire_traces_2

### ISSUE THREAD

**Issue by whyteH** [stripe/stripe-terminal-android#464]
## Summary
Corrupt proto payload in the queue: terminal_sdk_wire_metrics
`java.net.ProtocolException: Unexpected tag 0
at com.squareup.wire.ProtoReader.nextTag(ProtoReader.kt:172)
at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:387)
at com.stripe.proto.api.gator.EventResultPb$Companion$ADAPTER$1.decode(EventResultPb.kt:252)
at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:206)
at com.stripe.proto.api.gator.ProxyEventPb$Companion$ADAPTER$1.decode(ProxyEventPb.kt:160)
at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:457)
at com.squareup.wire.ProtoAdapter.decode(ProtoAdapter.kt:455)
at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:27)
at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileProtoSerializer.fromBytes(QueueFileProtoSerializer.kt:11)
at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.populateBatch(QueueFileCollector.kt:229)
at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector.access$populateBatch(QueueFileCollector.kt:26)
at com.stripe.jvmcore.batchdispatcher.collectors.QueueFileCollector$peek$2.invokeSuspend(QueueFileCollector.kt:176)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)`

![image](https://github.com/stripe/stripe-terminal-android/assets/12572016/01cbddc3-3a05-481a-9db4-4058860d0c1a)

## Android version
Android 11

## Impacted devices (Android devices or readers)
WisePad 3
## SDK version
3.6.0

## Other information

This bug seems to have always existed, and there are still problems when using 3.6.0.

**Comment by maxa-stripe** [comment]
@whyteH Thank you for the issue. Could you provide some instructions to reproduce this? Could you also describe what impact this exception has on your application: does it cause a crash? Does it occur during payment collection or discovery? Thanks!

**Comment by whyteH** [comment]
> @whyteH Thank you for the issue. Could you provide some instructions to reproduce this? Could you also describe what impact this exception has on your application: does it cause a crash? Does it occur during payment collection or discovery? Thanks!

After this exception occurs, OutOfMemoryError will occur, causing the app to crash. This exception occurs when creatingPaymentIntent. After Terminal.initTerminal to createPaymentIntent is repeated many times, it will easily appear. Once it appears, you must uninstall and reinstall the app. Reopening the app will still appear. In fact, my memory is sufficient. It appeared again when I was testing it just now.
![image](https://github.com/stripe/stripe-terminal-android/assets/12572016/5c376c6b-128b-4ec2-b460-0bcb85479a72)

![image](https://github.com/stripe/stripe-terminal-android/assets/12572016/085f3303-d882-454d-95ce-f43045051747)

**Comment by cwoods-stripe** [comment]
Fixed in Terminal Android SDK 3.7.0
https://github.com/stripe/stripe-terminal-android/blob/master/CHANGELOG.md

**Comment by cwoods-stripe** [comment]
Hi @whyteH - please confirm if issue is now resolved on your end as well, thanks!

**Comment by whyteH** [comment]
After testing 3.7.0, the following exception occurred, causing the application to crash.
![image](https://github.com/stripe/stripe-terminal-android/assets/12572016/18140890-f164-42a7-9d89-8cb1c2c648a5)

**Comment by whyteH** [comment]
> Hi @whyteH - please confirm if issue is now resolved on your end as well, thanks!

After testing 3.7.0, the following exception occurred, causing the application to crash.
![image](https://github.com/stripe/stripe-terminal-android/assets/12572016/d221e8cd-fe18-4b45-a9ee-11fabc738e95)
