### ISSUE TITLE
Can't connect wisepad 3 after upgrading 3.9.1

### ISSUE THREAD

**Issue by dev-innopix** [stripe/stripe-terminal-android#493]
We are using stripe_terminal_sdk. After upgrading the dependancies from 3.8.1 to 3.9.1, we are facing issue while we are trying to connect device to wisepad 3 using usb as well as bluetooth. It will works above android 11 but we are facing issue in android 9 devices. It 's give error as below.

Error code : `UNEXPECTED_ERROR.UNEXPECTED_SDK_ERROR`

`com.stripe.stripeterminal.external.models.TerminalException: Unexpected failure
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:1086)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$9_FdDGpM1BaifeFRjKBBfCCLP6o(Unknown Source:0)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:764)
                                                                                                    `

**Comment by dver-stripe** [comment]
Hey @dev-innopix -- as a heads up, this is the issue described in https://github.com/stripe/stripe-terminal-android/issues/495. We're currently working on a fix and will post more details there as they become available.

**Comment by usaimbhayat-stripe** [comment]
Issue fixed in `3.9.2`.

**Comment by dev-innopix** [comment]
@usaimbhayat-stripe  Thanks fro the update
