### ISSUE TITLE
com.stripe.stripeterminal.external.models.TerminalException - ATTESTATION_FAILURE

### ISSUE THREAD

**Issue by raymond-hitpay** [stripe/stripe-terminal-android#508]
## Summary
Hi we are facing issues with Stripe Tap to Pay on Android, our merchants are facing this error with their Oppo devices. 

## Code to reproduce
Here's the error log that was logged on our Firebase Crashanalytics Dashboard  :
CotsAdapter.checkAndThrowCotsError
com.stripe.stripeterminal.external.models.TerminalException - ATTESTATION_FAILURE (req_OvpDhoOC76ooy9): Unexpected error encountered. Please try clearing the application data in the settings application and contact Stripe support if the issue persists.

## Android version
Android 13

## Impacted devices (Android devices or readers)
Oppo (Majorly affects this)
- Reno 5 
- Reno 11 

## SDK version
3.9.1

## Other information
Also affecting Samsung : 
- Galaxy Note20 Ultra 5G
- Galaxy A52
- Galaxy S24+

**Comment by chr-stripe** [comment]
Hi @raymond-hitpay, is this issue still occurring for your devices?

**Comment by TatsuUkraine** [comment]
@chr-stripe it seems we have the same error during TTP connection attempt 

```
com.stripe.stripeterminal.external.models.TerminalException: Failed to generate attestation.
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(CotsAdapter.kt:674)
	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(CotsAdapter.kt:503)
	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(ProxyAdapter.kt:54)
	at com.stripe.stripeterminal.internal.common.terminalsession.activate.DefaultTerminalSessionReaderActivator.activateReader(DefaultTerminalSessionReaderActivator.kt:66)
	at com.stripe.stripeterminal.internal.common.terminalsession.connect.ConnectReaderOperation.execute(ConnectReaderOperation.kt:96)
	at com.stripe.stripeterminal.internal.common.terminalsession.ExternalOperation.run(ExternalOperation.kt:43)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:1345)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$Ir4aO0EWqkguS4CTgTdMxCOWU-4(Unknown Source:0)
	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
```

SDK version 4.3

**Comment by TatsuUkraine** [comment]
Device
Brand:Samsung
Model:Galaxy A14 5G

Operating System
Version:Android 14

**Comment by chr-stripe** [comment]
@TatsuUkraine I'll follow up with your issue in #580.

Otherwise, closing this one due to inactivity. @raymond-hitpay if you are able to confirm this is still happening, we'd be happy to reopen an investigate!
