### ISSUE TITLE
Bluetooth discovery fails with exception - SCAN_FAILED_INTERNAL_ERROR

### ISSUE THREAD

**Issue by TatsuUkraine** [stripe/stripe-terminal-android#519]
## Summary
SDK discovery fails with the exception:
```
com.stripe.stripeterminal.external.models.TerminalException: Unexpected failure
	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter.onUnexpectedFailure(BbposAdapter.kt:635)
	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$13.accept(BbposAdapter.kt:518)
	at com.stripe.stripeterminal.internal.common.adapter.BbposAdapter$register$13.accept(BbposAdapter.kt:518)
	at io.reactivex.rxjava3.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:202)
	at io.reactivex.rxjava3.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:256)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker$BooleanRunnable.run(ExecutorScheduler.java:324)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.runEager(ExecutorScheduler.java:289)
	at io.reactivex.rxjava3.internal.schedulers.ExecutorScheduler$ExecutorWorker.run(ExecutorScheduler.java:250)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
Caused by: com.stripe.core.hardware.status.ScanFailedFatalError: Bluetooth scan failed - SCAN_FAILED_INTERNAL_ERROR
	at com.stripe.stripeterminal.internal.common.discovery.BbposBluetoothScanner.onScanFailed(BbposBluetoothScanner.kt:135)
	at android.bluetooth.le.BluetoothLeScanner$1.run(BluetoothLeScanner.java:648)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:214)
	at android.app.ActivityThread.main(ActivityThread.java:7156)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
	at c<truncated: 101 chars>
```

## Android version
Android 9

## Impacted devices (Android devices or readers)
Brand:Samsung
Model:SM-J337A

## SDK version
3.9.5

**Comment by dmatthews-stripe** [comment]
@TatsuUkraine apologies for the delay, is this issue still occurring?

**Comment by TatsuUkraine** [comment]
It's been awhile, need to search through the logs 😅
