### ISSUE TITLE
"LOCAL_MOBILE_UNSUPPORTED_DEVICE | Localmobile reader not operating in secure process" error when discovering Tap to Pay (localmobile) readers

### ISSUE THREAD

**Issue by ivantespass** [stripe/stripe-terminal-android#520]
We are facing crashes targeting API Level 34 (on multiple devices, all of them are listed here https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#supported-devices) after update to v3.8 (it seems that reader is discovered and connected, then app crashes)

With v3.9 and v3.10 (with non-simulated readers) we are facing an error instead:

```
> 2024-10-29 10:42:16.487 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - Trace >> [STRIPE TERMINAL] Local Discovery timeout
> 2024-10-29 10:42:16.489 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - Trace >> [STRIPE TERMINAL] Discovery ErrorCode: LOCAL_MOBILE_UNSUPPORTED_DEVICE
> 2024-10-29 10:42:16.489 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - Trace >> [STRIPE TERMINAL] Discovery ErrorMessage: Localmobile reader not operating in secure process
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - Error >> reader_discover_error
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - Exception >> 
>                                                                                                       --- End of managed Com.Stripe.Stripeterminal.External.Models.TerminalException stack trace ---
>                                                                                                     com.stripe.stripeterminal.external.models.TerminalException: Localmobile reader not operating in secure process
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.checkAndThrowCotsError(CotsAdapter.kt:627)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.access$checkAndThrowCotsError(CotsAdapter.kt:83)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$DiscoverReadersOperation.execute(CotsAdapter.kt:709)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter$DiscoverReadersOperation.execute(CotsAdapter.kt:701)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.discoverReaders(CotsAdapter.kt:514)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.discoverReaders(ProxyAdapter.kt:259)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$DiscoverReadersOperation.executeIfNotCanceled(TerminalSession.kt:2439)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$CancelableOperation.execute(TerminalSession.kt:1319)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1274)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:1089)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$6lM7341_XI6PEqXfOM-yc2U5tkQ(Unknown Source:0)
>                                                                                                     	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
>                                                                                                     	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
>                                                                                                     	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  	at java.lang.Thread.run(Thread.java:1012)
> 2024-10-29 10:42:16.490 19220-19823 DOTNET                  net.mycompany.myapp             I  LOG - >> Errore discovering readers: Localmobile reader not operating in secure process
```

I clarify that we are using MAUI and Java Binding Project to wrap Stripe Terminal Android SDK: with v3.7.1 we don't get any error or exception and all works as excepted both in develop and release mode, both with simulated and non-simulated readers.

If it can be useful, error seems also related to a workaround used in MAUI to correctly define and declare :stripelocalmobile inner SDK process, in our autogenerated manifest:

`[Service(Process = ":stripelocalmobile")]
public class DummyService : Service {
}`

Above code snippet is inserted in our code to resolve this open issue (with v3.7.1 all works as excepted):
https://github.com/dotnet/android/issues/8675

Is it possible that something changed related to that process management, between v3.7.1 and latest ones?
Any ideas?

_Originally posted by @ivantespass in https://github.com/stripe/stripe-terminal-android/issues/479#issuecomment-2443824246_

**Comment by chr-stripe** [comment]
Hi @ivantespass, thanks for reaching out. The Tap to Pay on Android SDK runs mostly in a separate process for increased security when processing payment data. For that reason, we enforce that there are no other Android components also running in that process that are declared by the integrating application.

I suspect this is the issue your workaround is running into. Can you explain a bit more why this is needed? I reviewed the issue you mentioned (which is helpful, thanks!) but not entirely understanding what it's doing or why it's necessary.

**Comment by maggiewhite-stripe** [comment]
@ivantespass Are you seeing this issue with other targetSdk versions as well? E.g. targetSdk 33 or 35?

The most helpful thing for us to be able to help debug this would be a simple sample application that reproduces the issue, or at a minimum a list of your dependencies and other relevant build files. We have not observed this issue in our own test applications and so it's difficult for us to tell why this is happening in your particular build.

**Comment by PrabhaNPOS** [comment]
I am using ""@stripe/stripe-terminal-react-native": "^0.0.1-beta.22"". We are facing same issue after publish to google play store, then install the app from play store we are getting this same error. 

But while using as apk and install the apk in device , it is not throwing error

**Comment by chr-stripe** [comment]
@PrabhaNPOS the issue you are describing sounds more like the use case in stripe/stripe-terminal-react-native#866, please check there for updates to your issue.

@ivantespass without any further information about this use case for adding a `DummyService` in the Tap to Pay process to work around a .NET issue, I'll be closing this out given the guidance I've shared above. Please feel free to add more information in the future if needed and we can take a look!
