### ISSUE TITLE
Crash on Release Build v4.0.0 && v.4.1.0 `java.lang.NoSuchMethodError: No static method startTimedMetric`

### ISSUE THREAD

**Issue by jayjah** [stripe/stripe-terminal-android#527]
## Summary
A crash is happening during a payment process only in release builds. This happens when TapToPay with v.4.0.0 is chosen.
Following stacktrace is visible:

```
                                                                                                    com.stripe.stripeterminal.external.models.TerminalException: Contactless transaction failed java.lang.IllegalStateException: App Error: SERVER_ERROR 'An unknown error has occurred: java.lang.NoSuchMethodError: No static method startTimedMetric$default(Lcom/stripe/loggingmodels/MetricLogger;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/util/List;ILjava/lang/Object;)Lcom/stripe/loggingmodels/Metric; in class Lcom/stripe/loggingmodels/MetricLogger; or its super classes (declaration of 'com.stripe.loggingmodels.MetricLogger' appears in /data/app/~~NKqak6cvB6gmZPkFmW_D1Q==/com.talex.mytaxidriver-q0DWEjoMpm8lAqPi0eu6Zw==/base.apk)'.
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.callAidlWithExceptionConverted(CotsAdapter.kt:715)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.CotsAdapter.onReaderActivated(CotsAdapter.kt:467)
                                                                                                    	at com.stripe.stripeterminal.internal.common.adapter.ProxyAdapter.onReaderActivated(ProxyAdapter.kt:102)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.activateReader$terminalsession_release(TerminalSession.kt:611)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:2182)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:1243)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$6(TerminalSession.kt:1050)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$9_FdDGpM1BaifeFRjKBBfCCLP6o(Unknown Source:0)
                                                                                                    	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
```

## Android version
Android 14

## Impacted devices
Google Pixel 7a

## Dependency Versions
```
    // stripe
    implementation "com.stripe:stripe-java:26.4.0"
    implementation "com.stripe:stripeterminal:4.0.0"
    implementation "com.stripe:stripeterminal-taptopay:4.0.0"
    implementation "com.stripe:stripeterminal-core:4.0.0"
```

**Comment by sidhant-stripe** [comment]
Hi @jayjah 

According to [our documentation](https://docs.stripe.com/terminal/payments/setup-reader/tap-to-pay?platform=android#getting-started), you should replace `implementation "com.stripe:stripeterminal:4.0.0"` with 
```
    implementation "com.stripe:stripeterminal-taptopay:4.0.0"
    implementation "com.stripe:stripeterminal-core:4.0.0"
```

Can you try removing the line `implementation "com.stripe:stripeterminal:4.0.0"`  and let us know if this issue is still occurring?

**Comment by jayjah** [comment]
Unfortunately it's not possible for us to remove `implementation "com.stripe:stripeterminal:4.0.0"`, because we use tap to pay and a bluetooth scanner from stripe within the same application. 

Furthermore our proguard config already includes those lines.

Just for clarification:
This error does NOT happened with version 3.8.0 which was our last version where everything went fine.

**Comment by sidhant-stripe** [comment]
hi @jayjah, I've checked internally and confirmed that you do not need to include the `stripeterminal` dependency if you're including `stripeterminal-core`. Will continue to investigate, but in the meantime can you remove that line and see if you're still getting the same error?

A serial number for the device, account ID and approximate date/time when you encountered this issue would also be helpful if you can provide them.

**Comment by jayjah** [comment]
@sidhant-stripe Unfortunately the same error happened with version 4.1.0 and `com.stripe:stripe-java:28.1.0`.

Current stripe dependencies looks like the following:
```
    // stripe
    implementation "com.stripe:stripe-java:28.1.0"
    //implementation "com.stripe:stripeterminal:4.0.0"
    implementation "com.stripe:stripeterminal-taptopay:4.1.0"
    implementation "com.stripe:stripeterminal-core:4.1.0"
```

**Comment by jayjah** [comment]
Hi @chr-stripe 

 versions before 4.0.0 were fine to compile with Android API level below 26. We made runtime checks to make sure that the SDK will at first initialize only on valid API levels and run only on that specific valid API levels. Why was this behaviour changed with Version 4.0.0? This makes it currently absolute not usable at all for us.

**Comment by chr-stripe** [comment]
Hi @jayjah, the requirements are clear that downgrading the minSdk of the Terminal Android SDK has never been a supported use case. Even if it is only being used on versions higher than that at runtime, this behaviour is undefined and untested in our SDK, and thus is susceptible to break at any time as it seems is the case in v4.0.0 here.

If you see this `NoSuchMethodError` error on applications where the minSdk is 26 or higher, we will be happy to investigate and reopen this issue.
