### ISSUE TITLE
Accessing hidden method causes crash

### ISSUE THREAD

**Issue by rscherf** [stripe/stripe-terminal-android#53]
This happens directly at the `Terminal.initTerminal(...)` call.

Using: 
`com.stripe:stripeterminal:1.0.0-b9`
`compileSdkVersion 28`
`minSdkVersion 26`
`targetSdkVersion 26`

and building with Java, not Kotlin.

```
2019-08-01 09:53:34.008 16143-16143 Accessing hidden method Ljava/lang/invoke/LambdaMetafactory;->metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; (blacklist, linking, denied)
```

Here is the stack trace:

```
2019-08-01 09:53:34.009 16143-16143/com.nudge.payment E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nudge.payment, PID: 16143
    java.lang.NoSuchMethodError: No static method metafactory(Ljava/lang/invoke/MethodHandles$Lookup;Ljava/lang/String;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodType;Ljava/lang/invoke/MethodHandle;Ljava/lang/invoke/MethodType;)Ljava/lang/invoke/CallSite; in class Ljava/lang/invoke/LambdaMetafactory; or its super classes (declaration of 'java.lang.invoke.LambdaMetafactory' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at com.stripe.stripeterminal.ApplicationInfoModule.provideClock(ApplicationInfoModule.java:62)
        at com.stripe.stripeterminal.ApplicationInfoModule_ProvideClockFactory.proxyProvideClock(ApplicationInfoModule_ProvideClockFactory.java:29)
        at com.stripe.stripeterminal.ApplicationInfoModule_ProvideClockFactory.provideInstance(ApplicationInfoModule_ProvideClockFactory.java:20)
        at com.stripe.stripeterminal.ApplicationInfoModule_ProvideClockFactory.get(ApplicationInfoModule_ProvideClockFactory.java:16)
        at com.stripe.stripeterminal.ApplicationInfoModule_ProvideClockFactory.get(ApplicationInfoModule_ProvideClockFactory.java:7)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.EventFactory_Factory.provideInstance(EventFactory_Factory.java:20)
        at com.stripe.stripeterminal.EventFactory_Factory.get(EventFactory_Factory.java:16)
        at com.stripe.stripeterminal.EventFactory_Factory.get(EventFactory_Factory.java:7)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.DaggerTerminalComponent.getEventFactory(DaggerTerminalComponent.java:198)
        at com.stripe.stripeterminal.Terminal.initTerminal(Terminal.java:89)
        at nudge.payment.activities.MainActivity.onCreate(MainActivity.java:91)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3243)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3407)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
```

**Comment by danwaters-stripe** [comment]
Thanks for letting us know. Can you check if this error is happening with the example app as well?

**Comment by rscherf** [comment]
Interestingly, I'm getting a separate crash on the Example app (can't get anything to run). Cloned the latest this morning.

```
2019-08-01 12:44:50.984 18339-18339/com.stripe.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.stripe.example, PID: 18339
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.bbposstripe.bbdevice.BBDeviceController.aaa044(SourceFile:7845)
        at com.bbposstripe.bbdevice.aaa006zz.<init>(SourceFile:207)
        at com.bbposstripe.bbdevice.BBDeviceController.<init>(SourceFile:886)
        at com.bbposstripe.bbdevice.BBDeviceController.getInstance(SourceFile:3454)
        at com.stripe.stripeterminal.BbposModule.provideBBDeviceController(BbposModule.java:29)
        at com.stripe.stripeterminal.BbposModule_ProvideBBDeviceControllerFactory.proxyProvideBBDeviceController(BbposModule_ProvideBBDeviceControllerFactory.java:39)
        at com.stripe.stripeterminal.BbposModule_ProvideBBDeviceControllerFactory.provideInstance(BbposModule_ProvideBBDeviceControllerFactory.java:28)
        at com.stripe.stripeterminal.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:23)
        at com.stripe.stripeterminal.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:9)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalModule_ProvideBbposBluetoothAdapterFactory.provideInstance(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:59)
        at com.stripe.stripeterminal.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:41)
        at com.stripe.stripeterminal.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.provideInstance(TerminalModule_ProvideMasterAdapterFactory.java:34)
        at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:26)
        at com.stripe.stripeterminal.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.provideInstance(TerminalModule_ProvideTerminalSessionFactory.java:57)
        at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.get(TerminalModule_ProvideTerminalSessionFactory.java:39)
        at com.stripe.stripeterminal.TerminalModule_ProvideTerminalSessionFactory.get(TerminalModule_ProvideTerminalSessionFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.provideInstance(TerminalModule_ProvideTraceFactoryFactory.java:33)
        at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.get(TerminalModule_ProvideTraceFactoryFactory.java:26)
        at com.stripe.stripeterminal.TerminalModule_ProvideTraceFactoryFactory.get(TerminalModule_ProvideTraceFactoryFactory.java:8)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.DaggerTerminalComponent.getTraceFactory(DaggerTerminalComponent.java:208)
        at com.stripe.stripeterminal.Terminal.initTerminal(Terminal.java:89)
        at com.stripe.example.MainActivity.initialize(MainActivity.kt:386)
        at com.stripe.example.MainActivity.safeInitialize(MainActivity.kt:376)
        at com.stripe.example.MainActivity.onCreate(MainActivity.kt:50)
        at android.app.Activity.performCreate(Activity.java:7802)
        at android.app.Activity.performCreate(Activity.java:7791)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1299)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3243)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3407)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
2019-08-01 12:44:50.988 18339-18339/com.stripe.example E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/base.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_dependencies_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_resources_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_0_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_1_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_2_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_3_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_4_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_5_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_6_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_7_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_8_apk.apk", zip file "/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        	... 46 more
    	Suppressed: java.io.IOException: No original dex files found for dex location /data/app/com.stripe.example-QZvxc5JgN8GrkZqMUTLJyg==/split_lib_resources_apk.apk
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:365)
        at dalvik.system.DexFile.<init>(DexFile.java:107)
        at dalvik.system.DexFile.<init>(DexFile.java:80)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:444)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:403)
        at dalvik.system.DexPathList.<init>(DexPathList.java:164)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:126)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:101)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:74)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:87)
        at com.android.internal.os.ClassLoaderFactory.createClassLoader(ClassLoaderFactory.java:116)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:114)
        at android.app.ApplicationLoaders.getClassLoaderWithSharedLibraries(ApplicationLoaders.java:60)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:851)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:950)
        at android.app.LoadedApk.getResources(LoadedApk.java:1188)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2462)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2454)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6330)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        		... 6 more
2019-08-01 12:44:51.000 18339-18339/com.stripe.example I/Process: Sending signal. PID: 18339 SIG: 9
```

**Comment by rscherf** [comment]
In the Example app, I'm seeing the crash outlined in #50, but can't seem to find a version of `stripeterminal` that gets by it.

**Comment by rscherf** [comment]
Any ideas for how to solve?

**Comment by Hofferic** [comment]
I got here via google because this is the only place this issue is described just as I encountered it in a different context. I first assumed it was linked to changes in Android Q, but the provided sample app for the library I use worked fine.

For me the problem was a kotlin-based library. The code used in the build includes lambda features which android does not like.
I managed to get the build toolchain to (i assume) desugar the library correctly by adding the following to my gradle.properties:

android {
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

**Comment by rscherf** [comment]
@Hofferic unfortunately, that didn't fix it for me. Still getting that same crash.

**Comment by Hofferic** [comment]
@rscherf I just noticed that I wrote gradle.properties, which is of course not the app buildscript. I assume you caught that and added it in the right file when you tried, but I thought I'd mention why I edited my comment above after a week.

**Comment by hardikbhalodi** [comment]
java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;

Same issue facing after update project to android X.

Error at Terminal.initTerminal(getApplicationContext(), logLevel, tokenProvider, listener)
Tested with Terminal sdk  b8, b9

Was working fine with support library and Terminal sdk b8.

Any fix?

**Comment by nikolay** [comment]
I can't believe that your example app does not run out of the box. I guess we have to stick with Square for the time being!

**Comment by chander-stripe** [comment]
Hi @nikolay and others - sorry for the delay, I can definitely understand the frustration. We've been working on the latest RC1, which was just released, and this issue should be fixed. Please re-open a new issue if you see it still happening. Apologies again, and thanks for your patience!
