### ISSUE TITLE
BACKEND_URL with a path fails for connection_token, you need relative paths to post for this to work.

### ISSUE THREAD

**Issue by sgehrman** [stripe/stripe-terminal-android#82]
I host a server here:
    const val BACKEND_URL = "https://stellarkit.io/ruby/"
and here for testing
    const val BACKEND_URL = "https://stellarkit.io/stripe/"

Your code is trying to access the url without the /stripe/ or /ruby/
url=https://stellarkit.io/connection_token  (this is wrong)

See:  https://stackoverflow.com/questions/32352159/retrofit-2-removes-characters-after-hostname-from-base-url

You must be sending an absolute path rather than a relative path for the post to connection_token.

it fails.
E/StripeTerminal: com.stripe.stripeterminal.model.external.ConnectionTokenException: Creating connection token failed
        at com.stripe.example.network.ApiClient.createConnectionToken$kotlinapp_debug(ApiClient.kt:55)
        at com.stripe.example.network.TokenProvider.fetchConnectionToken(TokenProvider.kt:15)
        at com.stripe.stripeterminal.ConnectionTokenManager$refreshToken$1.run(ConnectionTokenManager.kt:71)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
 
The Javascript terminal examples work just fine.  The Java version does not.

**Comment by chander-stripe** [comment]
Apologies for the delay, and thanks for reporting this! Investigating now.

**Comment by chander-stripe** [comment]
This will be fixed in 1.0.8 , thanks for the bug report.

**Comment by chander-stripe** [comment]
1.0.8 has been released with this fix.
