### ISSUE TITLE
E/BluetoothGatt:: android.os.DeadObjectException

### ISSUE THREAD

**Issue by anton8900** [stripe/stripe-terminal-android#84]
Have got this error when trying to disconnect the device

12-23 16:34:40.228 31915-32505/au.com.ticketbooth.rfid.android E/BluetoothGatt: android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:511)
        at android.bluetooth.IBluetoothGatt$Stub$Proxy.clientDisconnect(IBluetoothGatt.java:925)
        at android.bluetooth.BluetoothGatt.disconnect(BluetoothGatt.java:834)
        at com.stripe.bbpos.bbdevice001.aaa020zz.aaa009(SourceFile:39)
        at com.stripe.bbpos.bbdevice001.aaa022zz.aaa000(SourceFile:17)
        at com.stripe.bbpos.bbdevice001.aaa015zz.aaa012(SourceFile:7)
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa007(SourceFile:20)
        at com.stripe.bbpos.bbdevice.BBDeviceController.disconnectBTInternal(SourceFile:39)
        at com.stripe.bbpos.bbdevice.BBDeviceController.disconnectBT(SourceFile:2)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerImpl.disconnectBT(BbposDeviceControllerImpl.kt:44)
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter$DisconnectReaderOperation.execute$stripeterminal_release(BbposBluetoothAdapter.kt:510)
        at com.stripe.stripeterminal.adapter.BbposBluetoothAdapter.disconnectReader$stripeterminal_release(BbposBluetoothAdapter.kt:133)
        at com.stripe.stripeterminal.adapter.MasterAdapter.disconnectReader$stripeterminal_release(MasterAdapter.kt:67)
        at com.stripe.stripeterminal.TerminalSession$DisconnectReaderOperation.run$stripeterminal_release(TerminalSession.kt:565)
        at com.stripe.stripeterminal.TerminalSession$enqueueOperation$1.run(TerminalSession.kt:208)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by anton8900** [comment]
It fail with this error and i can't to disconnect the device

**Comment by anton8900** [comment]
collectPaymentMethod don't return any response

**Comment by anton8900** [comment]
for first connection all worked

**Comment by anton8900** [comment]
then i restarted app and all started to crash with the error

12-23 16:51:14.987 5804-6066/au.com.ticketbooth.rfid.android W/StripeTerminal: INTEGRATION_ERROR.NOT_CONNECTED_TO_READER: Cannot disconnect bluetooth because bluetooth is not connected.
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:573)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
12-23 16:51:14.987 5804-6066/au.com.ticketbooth.rfid.android E/StripeTerminal: READER_ERROR.BLUETOOTH_ERROR: BLE initialization no responsed
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)
12-23 16:51:14.993 5804-5804/au.com.ticketbooth.rfid.android E/TokenLogService: null
    com.stripe.stripeterminal.model.external.TerminalException
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.fail(BbposDeviceControllerListener.kt:757)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onError(BbposDeviceControllerListener.kt:598)
        at com.stripe.bbpos.bbdevice.BBDeviceController$aaa007zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:815)
        at android.os.Handler.dispatchMessage(Handler.java:104)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:5738)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:766)

**Comment by anton8900** [comment]
bluetooth was connected
then reconnected the network and all started to work again

**Comment by chander-stripe** [comment]
Could you write in to https://support.stripe.com/contact?
The team there can help you out!

Please include the following details when you write in:
1. The SDK version you are on
2. Any errors you see in Logcat
3. Is this on simulated reader or physical reader
4. Reproduction steps

Going to close this as Github Issues should be reserved for SDK feature requests or bugs.
Thanks!
