### ISSUE TITLE
You can only call initTerminal *before* requesting the Terminal instance for the first time

### ISSUE THREAD

**Issue by farrukhshj** [stripe/stripe-terminal-android#88]
I'm trying to switch accounts in the app and before calling Terminal.initTerminal() I'm doing : 

1. Terminal.getInstance().clearCachedCredentials(); 
2. OnDisconnectReader()
3. Terminal.initTerminal()
And I still get the exception:

> java.lang.IllegalStateException: You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method.

Don't know if this is an issue or if stripe does not let us change accounts within the app.

**Comment by chander-stripe** [comment]
@farrukhshj Hi, the SDK has no notion of 'accounts'. Accounts in your app are divorced from anything in the Terminal SDK, so you shouldn't have to call clearCachedCredentials or anything else.

What is your concern regarding sharing the same Terminal instance across 'accounts'?

More specifically, what is your app trying to do, and what does each 'account' represent?

**Comment by farrukhshj** [comment]
So when I have to connect my BBPOS with android sdk, I have to request for a connection token from backend which is specified in APIClient.java by variable BACKEND_URL. This token is then used by Terminal.initTerminal().

Lets say at some point I have to use Terminal.initTeriminal() again but with a different BASE_URL for TokenProvider() without having to quit the app, can I do that ? 

Basically I have two different accounts on stripe and I have deployed heroku backend for each of them. Depending on what the user chooses on the App i want the terminal to switch the backend_urls and get the token from that url.

**Comment by danwaters-stripe** [comment]
Ah, in that case, I would recommend that you pass in an implementation of `ConnectionTokenProvider` that looks something like this:

```
class VariableConnectionTokenProvider(var provider: ConnectionTokenProvider) : ConnectionTokenProvider {

    override fun fetchConnectionToken(callback: ConnectionTokenCallback) {
        provider.fetchConnectionToken(callback)
    }
}
```

That way you can create it with your initial token provider, pass it into `initTerminal`, then when you need to switch accounts:

1. Set the provider to the new provider you want (e.g. `variableConnectionTokenProvider.provider = newProvider`)
2. Call `disconnectReaders`
3. Call `clearCachedCredentials`
4. Call `discoverReaders` and it will pull the connection token from your new provider.

We haven't thought about this use case much. We'll have to look into if there's a better way to support this. We can at least document it a little better. Hope that helps!

**Comment by chander-stripe** [comment]
@farrukhshj closing this for now, as there isn't a bug w/ our SDK reported in this issue.

**Comment by LuckyPhz** [comment]
I reported an error when connecting the card reader, the error message is as follows


2023-05-08 15:17:17.969 Strip...minal com...rder_helper  D  class=ConnectionTokenRepository message=fetchConnectionToken.onSuccess
2023-05-08 15:17:18.232 Strip...minal com...rder_helper  I  class=BbposControllerListener message=onBTDisconnected
2023-05-08 15:17:18.236 Strip...minal com...rder_helper  I  class=TransactionStateMachine message="onStateChanged: DISCONNECT -> CANCELLED: null"
2023-05-08 15:17:18.236 Strip...minal com...rder_helper  D  class=BbposProxyDiscoveryController message=stopDiscover
2023-05-08 15:17:18.238 Strip...minal com...rder_helper  I  class=TransactionStateMachine message="onStateChanged: CANCELLED -> EMPTY: Transaction cancelled"
2023-05-08 15:17:18.239 Strip...minal com...rder_helper  I  class=TerminalStatusManager message=notConnected.
2023-05-08 15:17:18.240 Strip...minal com...rder_helper  D  class=ProxyTerminalListener message=onConnectionStatusChange(NOT_CONNECTED)
2023-05-08 15:17:18.240 Strip...minal com...rder_helper  W  class=BbposBluetoothAdapterLegacy message="skipping disconnectReader"
2023-05-08 15:17:18.244 Strip...minal com...rder_helper  E  class=TerminalSession
                                                            com.stripe.stripeterminal.external.models.TerminalException: Could not connect to Stripe. Please retry.
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient$Companion.decodeResponse(ApiClient.kt:237)
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient$Companion.decodeResponse$default(ApiClient.kt:219)
                                                            	at com.stripe.stripeterminal.internal.common.api.ApiClient.activateReader(ApiClient.kt:61)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.OnlineDirectResourceRepository.activateReader(OnlineDirectResourceRepository.kt:122)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.DirectResourceRepositoryRouter.activateReader(DirectResourceRepositoryRouter.kt:54)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:52)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository$activateReader$1.invoke(ProxyResourceRepository.kt:51)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.withCurrentRepository(ProxyResourceRepository.kt:147)
                                                            	at com.stripe.stripeterminal.internal.common.resourcerepository.ProxyResourceRepository.activateReader(ProxyResourceRepository.kt:51)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ConnectReaderOperation.execute(TerminalSession.kt:1417)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$ExternalOperation.run$terminalsession_release(TerminalSession.kt:853)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.enqueueOperation$lambda$2(TerminalSession.kt:715)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession.$r8$lambda$rYGQPNcZu27M8Fdv0ehwoLn0Un8(Unknown Source:0)
                                                            	at com.stripe.stripeterminal.internal.common.terminalsession.TerminalSession$$ExternalSyntheticLambda0.run(Unknown Source:4)
                                                            	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
                                                            	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
                                                            	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                            	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                            	at java.lang.Thread.run(Thread.java:923)

**Comment by ajithv11** [comment]
@danwaters-stripe   While running the tap to pay on my mobile device with NFC support, at some point I got the following error  message stating NFC reader connection the Stripe Terminal ConnectionToken has expired. Please download a new one using v1/terminal/connection_tokens

So I think I should call initTerminal on each payment, Unfortunately I couldn't able to call initTerminal multiple times , here I struck with the following error 
_You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method._

Without initTerminal, How can I generalte new token v1/terminal/connection_tokens
InitTerminal code I used is given below
    
    Terminal.initTerminal(
            applicationContext,
            LogLevel.VERBOSE,
            TokenProvider(tock), // token created from server for eg: stripe.terminal.connectionTokens.create();
            TerminalEventListener()
    )

Tokenprovider class is defined as given below

    class TokenProvider(
        var token: String
    ): ConnectionTokenProvider {
        override fun fetchConnectionToken(callback: ConnectionTokenCallback) {
            try { 
                callback.onSuccess(token)
            } catch (e: ConnectionTokenException) {
                callback.onFailure(e)
            }
        }
    }


After disconnectReader & clearCachedCredentials , I called Terminal.initTerminal as above, but receive error as below

_You can only call initTerminal *before* requesting the Terminal instance for the first time. If you are trying to switch accounts in your app, refer to the documentation for the `clearCachedCredentials` method._

**Comment by hassanShahzadNP** [comment]
@ajithv11 Have you found any solution for it? I am facing the same issue.
