### ISSUE TITLE
Example app crashes when user clicks "allow" in location permissions dialog

### ISSUE THREAD

**Issue by Jarrette** [stripe/stripe-terminal-android#89]
I'm getting the following issue in the 1.0.2 example app:

When app is first started and requests permission from the user for location, if the user hits allow, the app crashes:

`2020-01-26 13:26:02.514 31985-31985/com.stripe.example E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.stripe.example, PID: 31985
    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/content/ContextCompat;
        at com.stripe.bbpos.bbdevice.BBDeviceController.aaa002(SourceFile:126)
        at com.stripe.bbpos.bbdevice.aaa008zz.<init>(SourceFile:101)
        at com.stripe.bbpos.bbdevice.BBDeviceController.<init>(SourceFile:395)
        at com.stripe.bbpos.bbdevice.BBDeviceController.getInstance(SourceFile:17)
        at com.stripe.stripeterminal.dagger.BbposModule.provideBBDeviceController(BbposModule.kt:24)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.provideBBDeviceController(BbposModule_ProvideBBDeviceControllerFactory.java:37)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:27)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBBDeviceControllerFactory.get(BbposModule_ProvideBBDeviceControllerFactory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBbposDeviceControllerFactory.get(BbposModule_ProvideBbposDeviceControllerFactory.java:32)
        at com.stripe.stripeterminal.dagger.BbposModule_ProvideBbposDeviceControllerFactory.get(BbposModule_ProvideBbposDeviceControllerFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideBbposBluetoothAdapterFactory.get(TerminalModule_ProvideBbposBluetoothAdapterFactory.java:14)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:32)
        at com.stripe.stripeterminal.dagger.TerminalModule_ProvideMasterAdapterFactory.get(TerminalModule_ProvideMasterAdapterFactory.java:11)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:42)
        at com.stripe.stripeterminal.TerminalSession_Factory.get(TerminalSession_Factory.java:10)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.log.TraceFactory_Factory.get(TraceFactory_Factory.java:26)
        at com.stripe.stripeterminal.log.TraceFactory_Factory.get(TraceFactory_Factory.java:9)
        at dagger.internal.DoubleCheck.get(DoubleCheck.java:47)
        at com.stripe.stripeterminal.dagger.DaggerTerminalComponent.getTraceFactory(DaggerTerminalComponent.java:185)
        at com.stripe.stripeterminal.Terminal$Companion.initTerminal(Terminal.kt:448)
        at com.stripe.example.MainActivity.initialize(MainActivity.kt:164)
        at com.stripe.example.MainActivity.onRequestPermissionsResult(MainActivity.kt:76)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7976)
        at android.app.Activity.dispatchActivityResult(Activity.java:7798)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4636)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4685)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1970)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7156)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:975)
2020-01-26 13:26:02.514 31985-31985/com.stripe.example E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.content.ContextCompat" on path: DexPathList[[zip file "/data/app/com.stripe.example-2en1woUcHOjBIxwqzv7htQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.stripe.example-2en1woUcHOjBIxwqzv7htQ==/lib/arm, /system/lib, /vendor/lib]]`

**Comment by Jarrette** [comment]
ok, I just verified this is occurring in gradle:4.0.0-alpha09 but not in gradle:3.5.3

**Comment by chander-stripe** [comment]
Thanks for reporting - I'll try with the gradle alpha version and get back to you.

**Comment by chander-stripe** [comment]
Verified; investigating...

**Comment by chander-stripe** [comment]
Going to close this for now, as it's hard for us to support beta and alpha versions of gradle. If this happens once gradle 4.0 is stable, we'll look at it then.

**Comment by yogikorke** [comment]
I am facing this issue with stripe terminal version '2.8.1' and 'com.android.tools.build:gradle:7.2.2'. 
Any help appreciated.
