### ISSUE TITLE
CollectPayment caused kotlin.KotlinNullPointerException

### ISSUE THREAD

**Issue by udongeex** [stripe/stripe-terminal-android#96]
I'm using physical BBPOS device and everytime when I call CollectPayment and input my card, my app crash with kotlin.KotlinNullPointerException. The same happen for both my current application and the Example app.

Below is my log

>2020-02-11 02:19:47.849 32492-32492/com.tommy.loyote.tablet E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tommy.loyote.tablet, PID: 32492
    kotlin.KotlinNullPointerException
        at com.stripe.stripeterminal.model.internal.PaymentMethodData.<init>(PaymentMethodData.kt:26)
        at com.stripe.stripeterminal.model.internal.PaymentMethodData.<init>(PaymentMethodData.kt:9)
        at com.stripe.stripeterminal.model.internal.PaymentMethodData$Companion.newEmvData(PaymentMethodData.kt:56)
        at com.stripe.stripeterminal.bbpos.BbposDeviceControllerListener.onRequestOnlineProcess(BbposDeviceControllerListener.kt:363)
        at com.stripe.bbpos.bbdevice.BBDeviceController$bbb017zz.run(SourceFile:1)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:280)
        at android.app.ActivityThread.main(ActivityThread.java:6706)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by chander-stripe** [comment]
@udongeex couple follow up questions
1. did you get the BBPOS device from Stripe?
2. What version of Android Studio, what version of Android, and what version of the Terminal SDK are you using?

**Comment by chander-stripe** [comment]
Also, can you paste the full logcat when you do this? Thanks

**Comment by chander-stripe** [comment]
Ping :)

**Comment by chander-stripe** [comment]
@udongeex ^

**Comment by udongeex** [comment]
Sorry for late response @chander-stripe 
It happen due to our customer sent us another device and it not stripe.
